hydroflow/src/scheduled/mod.rs
Still working on the teer, it is proving trickier than I expected. This is some interim work which makes the "canonical" end of a handoff be the writer, rather than the reader.
=> make the writer construct the handoff instead of the reader

hydroflow/src/scheduled/ctx.rs, hydroflow/src/scheduled/handoff_list.rs, hydroflow/src/scheduled/input.rs, hydroflow/src/scheduled/mod.rs
=> Rename OpId to SubgraphId and update variables for consistent terminology

Cargo.lock, Cargo.toml, covid_tracing_dist/Cargo.toml, covid_tracing_dist/src/database.rs, covid_tracing_dist/src/main.rs, covid_tracing_dist/src/people.rs, covid_tracing_dist/src/tracker.rs, hydroflow/src/scheduled/mod.rs
This is a very rough first take of a Hydroflow app that crosses network
boundaries. Lots of stuff is bad here: the abstractions are wonky, the encoding
allocates too much, the message-passing is fragile, but I wanted to get this
merged so that stuff could be improved incrementally as we figure out what
actually good abstractions are here.
=> Add distributed Covid tracing app

covid_tracing_dist/src/database.rs, covid_tracing_dist/src/main.rs, covid_tracing_dist/src/tracker.rs
This implementation still has some extra copies, and doesn't re-use buffers
appropriately. In addition it still just encodes in JSON since that makes it a
bit easier to debug over the wire.
Rewrote this thing like twice and still not happy with it yet, will likely keep iterating a bit longer.
=> Eliminate some copies and batch networks sends

benches/benches/fan_in.rs, benches/benches/fan_out.rs, benches/benches/fork_join.rs, benches/benches/identity.rs, benches/benches/reachability.rs, covid_tracing/src/main.rs, covid_tracing_dist/src/database.rs, covid_tracing_dist/src/tracker.rs, hydroflow/src/scheduled/mod.rs, hydroflow/src/scheduled/net/mod.rs, hydroflow/src/scheduled/query.rs
A relatively simple, mechanical change, prerequisite for some improvements I want to do with how hydroflow handles Rust async/futures.
=> Update all hydroflow subgraphs to take a Context<'_>

hydroflow/src/scheduled/net/mod.rs
Add questions as code review
Formatted version here: https://www.mingweisamuel.com/hydroflow/doc/hydroflow/scheduled/net/#how-tokio-interacts-with-hydroflow-mingwei-2021-12-07
=> Add explanation of Tokio interfacing

hydroflow/src/scheduled/graph.rs, hydroflow/src/scheduled/graph_demux.rs, hydroflow/src/scheduled/mod.rs, hydroflow/tests/mux_demux.rs
Not 100% sure this is the right API, but seems sensible for some exploration.
=> Add a "demux" operator

benches/benches/arithmetic.rs, benches/benches/identity.rs, benches/benches/reachability.rs
=> Fix benchmarks for pusherator API

covid_tracing_dist/src/database.rs, covid_tracing_dist/src/tracker.rs, hydroflow/src/scheduled/net/mod.rs, hydroflow/tests/networked.rs
We want to start moving towards a usable "clustering" API, so this is a first
step there to make networking a little simpler/cleaner, and pull some stuff out
of the Hydroflow struct for now.
=> Add a real networked test and polish the API a bit

hydroflow/src/scheduled/graph.rs, hydroflow/src/scheduled/handoff/handoff_list.rs, hydroflow/src/scheduled/handoff/mod.rs, hydroflow/src/scheduled/mod.rs
Small organization change which I think makes sense
=> Move HandoffList into handoff module

covid_tracing_dist/src/database.rs, covid_tracing_dist/src/tracker.rs, hydroflow/src/scheduled/graph_demux.rs, hydroflow/src/scheduled/net/mod.rs, hydroflow/src/scheduled/net/network_vertex.rs, hydroflow/tests/networked.rs
This commit introduces some tools for more complex topologies and add a test
that has multiple graphs coordinating. I don't really like how much boilerplate
is involved in the setup of this graph but I think it's a good starting point
to figure out what these abstractions should look like.
=> Add more primitives to construct more complex graphs

hydroflow/src/scheduled/net/network_vertex.rs, hydroflow/tests/networked.rs
Still rough around the edges, connect_tcp in particular is not quite right, but
wanted to get this out there to unblock @jhellerstein.
=> Add an echo server test

hydroflow/src/scheduled/net/network_vertex.rs, hydroflow/tests/networked.rs
There's still some ergonomic issues to be worked out but I'd like to wait on
the API changes going in before trying to resolve that stuff (for example, you
can't build this into a compiled subgraph easily).
=> Clean up the TCP stuff a bit more

Cargo.lock, hydroflow/Cargo.toml, hydroflow/tests/networked.rs
I'm not really sure how best to generalize this, which is something we will
probably have to figure out.
=> First attempt at an exchange-like operator

hydroflow/src/builder/build/mod.rs, hydroflow/src/builder/build/pull_iter.rs, hydroflow/src/builder/connect/mod.rs, hydroflow/src/builder/connect/pull_null.rs, hydroflow/src/builder/surface/exchange.rs, hydroflow/src/builder/surface/mod.rs, hydroflow/src/builder/surface/pull_iter.rs, hydroflow/src/builder/surface/pull_join.rs, hydroflow/tests/networked.rs
Also includes the iterator-as-PullSurface stuff.
=> Exchange abstraction

hydroflow/src/builder/surface/exchange.rs
Not much to this one, basically just a simplification of exchange.
=> Add a `broadcast` operator

hydroflow/src/builder/build/pull_handoff.rs, hydroflow/src/builder/build/push_handoff.rs, hydroflow/src/builder/hydroflow_builder.rs, hydroflow/src/builder/surface/pull_handoff.rs, hydroflow/src/builder/surface/push_handoff.rs, hydroflow/src/scheduled/graph.rs, hydroflow/src/scheduled/graph_ext.rs, hydroflow/src/scheduled/net/mod.rs, hydroflow/src/scheduled/net/network_vertex.rs, hydroflow/src/scheduled/port.rs, hydroflow/src/scheduled/query.rs, hydroflow/tests/networked.rs, relalg/src/runtime.rs
Now they correspond directly with RecvCtx, SendCtx
=> Rename ports to RecvPort, SendPort

Cargo.lock, Cargo.toml, kvs/Cargo.toml, kvs/src/main.rs
This is a very basic version of an Anna-like KVS. It doesn't actually use the
Hydroflow dataflow mechanisms yet because I am still trying to understand how
the system works fundamentally. I think the translation into dataflow should be
pretty straightforward.
=> Initial pass of KVS

hydroflow/Cargo.toml, hydroflow/examples/graph_reachability/main.rs, hydroflow/src/builder/build/pull_iter.rs, hydroflow/src/builder/hydroflow_builder.rs, hydroflow/src/builder/into_hydroflow.rs, hydroflow/src/builder/mod.rs, hydroflow/src/builder/surface/pull_iter.rs
=> Simplify pull_iter generics, add graph reachability example

hydroflow/Cargo.toml, hydroflow/examples/two_pc/README.md, hydroflow/examples/two_pc/coordinator.rs, hydroflow/examples/two_pc/main.rs, hydroflow/examples/two_pc/members.json, hydroflow/examples/two_pc/protocol.rs, hydroflow/examples/two_pc/subordinate.rs
=> Add Two-Phase Commit example

hydroflow/src/builder/build/pull_batch.rs, hydroflow/src/builder/surface/mod.rs, hydroflow/src/builder/surface/pull_batch.rs, hydroflow/src/compiled/pull.rs, hydroflow/src/scheduled/mod.rs
This thing now eagerly merges lattices values and then releases the merged
value all at once.
=> Rework batcher to be lattice-based

Cargo.lock, hydroflow/src/builder/build/pull_half_hash_join.rs, hydroflow/src/builder/surface/mod.rs, hydroflow/src/builder/surface/pull_half_hash_join.rs, hydroflow/src/compiled/pull.rs, hydroflow/src/lang/collections.rs, hydroflow/src/lang/lattice/dom_pair.rs, kvs/Cargo.toml, kvs/src/main.rs
First two commits are courtesy of Mingwei to make some lattice stuff work.
=> Implement reads in KVS

Cargo.lock, hydroflow/Cargo.toml, hydroflow/examples/kvs/main.rs
Wrap up the interface in a struct behind get/set methods.
=> Add a nicer interface to KVS

hydroflow/src/builder/surface/filter.rs, hydroflow/src/builder/surface/filter_map.rs, hydroflow/src/builder/surface/flatten.rs, hydroflow/src/builder/surface/map.rs, hydroflow/src/builder/surface/push_pivot.rs, hydroflow/src/builder/surface/push_start.rs
To avoid errors in VS code, make sure you are on nightly rust-analyzer, at least version v0.3.970. You may have to full restart VSCode.
=> Update where clause position

README.md
=> Add dev setup to README.md

Cargo.lock, hydroflow/Cargo.toml, hydroflow/examples/kvs/main.rs
Still pretty simple, but the beginnings of a configurable benchmarking harness
for the KVS.
Next steps are that I'm gonna pull this into its own file, but I think it's still simple enough that it can just live here for this PR.
=> kvs: add a benchmarking harness

.github/gh-pages/.gitignore, .github/gh-pages/index.md, .github/workflows/ci.yml, design_docs/index.md
=> Publish design doc link, index on gh-pages

.vscode/launch.json, hydroflow/examples/chat/README.md, hydroflow/examples/chat/client.rs, hydroflow/examples/chat/main.rs, hydroflow/examples/chat/server.rs, hydroflow/examples/graph_reachability/README.md, hydroflow/examples/graph_reachability/main.rs, hydroflow/examples/three_clique/README.md, hydroflow/examples/three_clique/main.rs, hydroflow/examples/two_pc/README.md, hydroflow/examples/two_pc/coordinator.rs, hydroflow/examples/two_pc/main.rs, hydroflow/examples/two_pc/subordinate.rs, hydroflow/src/scheduled/graph.rs, hydroflow/src/scheduled/mod.rs
Generate dot (graphviz) graphs, in addition to mermaid.
Add line indentation for generated mermaid graphs.
=> dot graphs and indents for mermaid

hydroflow/examples/kvs/common.rs, hydroflow/examples/kvs/kvs_raw.rs, hydroflow/examples/kvs/main.rs
This one uses no Hydroflow at all. Similar to the original one, just factors
some stuff out.
=> Re-add the "raw" implementation of the KVS

hydroflow/src/builder/build/mod.rs, hydroflow/src/builder/build/pull_batch.rs, hydroflow/src/builder/build/pull_chain.rs, hydroflow/src/builder/build/pull_cross_join.rs, hydroflow/src/builder/build/pull_filter.rs, hydroflow/src/builder/build/pull_filter_map.rs, hydroflow/src/builder/build/pull_flatten.rs, hydroflow/src/builder/build/pull_fold_epoch.rs, hydroflow/src/builder/build/pull_half_hash_join.rs, hydroflow/src/builder/build/pull_handoff.rs, hydroflow/src/builder/build/pull_iter.rs, hydroflow/src/builder/build/pull_join.rs, hydroflow/src/builder/build/pull_map.rs, hydroflow/src/builder/build/push_filter.rs, hydroflow/src/builder/build/push_filter_map.rs, hydroflow/src/builder/build/push_flatten.rs, hydroflow/src/builder/build/push_for_each.rs, hydroflow/src/builder/build/push_handoff.rs, hydroflow/src/builder/build/push_map.rs, hydroflow/src/builder/build/push_partition.rs, hydroflow/src/builder/build/push_tee.rs
Turned out not to be so bad! Thanks @aliemjay!
=> Use `where Self: 'slf` clause to fix build

Cargo.lock, hydroflow/src/lib.rs, hydroflow/tests/surface_codegen.rs.wip, hydroflow/tests/surface_syntax.rs, hydroflow_core/src/graph/flat_graph.rs, hydroflow_core/src/graph/mod.rs, hydroflow_core/src/graph/ops/mod.rs, hydroflow_core/src/graph/partitioned_graph.rs, hydroflow_macro/Cargo.toml, hydroflow_macro/src/lib.rs
- Wip on codegen w/ some code cleanups
- Modularize ops, provide nicer arity errors and now warnings too.
=> Modularize ops, wip on codegen

hydroflow/src/scheduled/graph.rs, hydroflow/tests/surface_codegen.rs, hydroflow/tests/surface_echo.rs, hydroflow/tests/surface_stratum.rs, hydroflow_lang/src/graph/ops/mod.rs, hydroflow_lang/src/graph/partitioned_graph.rs
=> Add async write

hydroflow/tests/datalog_frontend.rs, hydroflow_datalog/src/join_plan.rs, hydroflow_datalog/src/lib.rs, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__local_constraints-2.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__local_constraints.snap, hydroflow_datalog/src/util.rs
=> Emit relation filters when there are local constraints

Cargo.lock, book/example_3_surface.md, book/example_4_surface.md, book/surface_data.md, book/surface_ops.md, hydroflow/Cargo.toml, hydroflow/examples/surface_syntax/main.rs, hydroflow/src/lib.rs, hydroflow/src/util/mod.rs, hydroflow/tests/datalog_frontend.rs, hydroflow/tests/surface_codegen.rs, hydroflow/tests/surface_echo.rs, hydroflow/tests/surface_stratum.rs, hydroflow/tests/surface_warnings.rs, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__join_with_other.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__join_with_self.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__local_constraints-2.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__local_constraints.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__minimal_program.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__multiple_contributors.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__single_column_program.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__triple_relation_join.snap, hydroflow_lang/src/graph/ops/mod.rs
=> Update `recv_stream` to handle all `Stream`s instead of just `tokio::mpsc::unbounded_channel`

hydroflow/src/declarative_macro.rs, hydroflow/src/lib.rs, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__join_with_other.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__join_with_self.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__local_constraints-2.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__local_constraints.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__minimal_program.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__multiple_contributors.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__single_column_program.snap, hydroflow_datalog/src/snapshots/hydroflow_datalog__tests__triple_relation_join.snap, hydroflow_datalog/src/snapshots/update.bash, hydroflow_lang/src/graph/partitioned_graph.rs
Incremental improvements to the surface syntax debugging experience
=> Add type guards, better spans to surface syntax codegen

hydroflow/tests/surface_codegen.rs, hydroflow_lang/src/graph/ops/mod.rs, pusherator/src/inspect.rs, pusherator/src/lib.rs
resting my brain with some of the easy qol stuff
=> Implement `inspect()` surface syntax operator

hydroflow/tests/surface_codegen.rs, hydroflow_lang/src/graph/ops/mod.rs
=> add unique operator to remove duplicates

hydroflow/examples/deadlock_detector/helpers.rs, hydroflow/examples/deadlock_detector/peer.rs, hydroflow/examples/deadlock_detector/protocol.rs, hydroflow/examples/two_pc/coordinator.rs, hydroflow/tests/surface_codegen.rs, hydroflow_lang/src/graph/ops/mod.rs
=> first version of groupby with test and example

hydroflow_datalog/src/join_plan.rs
Move parts of expand_join_plan into separate functions.
=>  Extract parts of expand_join_plan into new functions.

book/example_1_surface.md, book/example_2_surface.md, book/example_4_1_surface.md, book/example_4_surface.md, book/surface_flows.md, book/surface_syntax.md
Change references from ./surface_ops.gen.md to ./surface_ops.gen.md
=> Update book references to surface_ops

.github/workflows/ci.yml, book.toml, book/example_3_surface.md, book/surface_embedding.md, book/surface_syntax.md
=> Add `mdbook-linkcheck` to prevent dead book links

hydroflow/Cargo.toml, hydroflow/examples/kvs/README.md, hydroflow/examples/kvs/client.rs, hydroflow/examples/kvs/helpers.rs, hydroflow/examples/kvs/main.rs, hydroflow/examples/kvs/protocol.rs, hydroflow/examples/kvs/server.rs
Simplest implementation. Motivates the need for more control over join state lifetime!
=> initial kvs example

hydroflow/Cargo.toml, hydroflow/examples/echoserver/README.md, hydroflow/examples/echoserver/client.rs, hydroflow/examples/echoserver/helpers.rs, hydroflow/examples/echoserver/main.rs, hydroflow/examples/echoserver/protocol.rs, hydroflow/examples/echoserver/server.rs
Simple echo server. Maybe useful for book.
=> Echo Server example

Cargo.lock, hydroflow/Cargo.toml, hydroflow/examples/chat/main.rs, hydroflow/examples/deadlock_detector/main.rs, hydroflow/examples/echo_serde_json/main.rs, hydroflow/examples/echoserver/main.rs, hydroflow/examples/graph_reachability/main.rs, hydroflow/examples/graph_unreachability/main.rs, hydroflow/examples/kvs/main.rs, hydroflow/examples/three_clique/main.rs, hydroflow/examples/two_pc/main.rs, hydroflow/src/util/mod.rs, hydroflow_lang/src/graph/ops/dest_sink_serde.rs, hydroflow_lang/src/graph/ops/source_stream_serde.rs
Now clap will properly parse IP addresses from the command line
=> update clap crate, make ipv4_resolve return a Result

book/SUMMARY.md, book/concepts.md, book/ecosystem.md, book/todo.md, hydroflow_macro/build.rs
Reverts hydro-project/hydroflow#313
Adding in treatment of comments
=> Revert "refactor and print streaming/blocking for each op"

Cargo.lock, benches/Cargo.toml, hydroflow/Cargo.toml
=> update criterion, add html_reports feature as suggested by criterion

hydroflow_lang/src/graph/ops/unique.rs
=> implement `'tick`/`'static` for `unique()` #272

.github/workflows/ci.yml, benches/Cargo.toml, benches/benches/micro_ops.rs
Add more specific micro benchmarks for specific ops
=> Micro benchmarks

hydroflow/src/scheduled/graph.rs, hydroflow/tests/surface_difference.rs, hydroflow_lang/src/graph/ops/unique.rs
Temp, requires more thought
#348
=> Fix `run_tick()` semantics, fix `unique`'s `'static`

hydroflow_lang/src/graph/di_mul_graph.rs
=> fixup! Add `DiMulGraph`, use in `FlatGraph` (not compiling)

Cargo.lock, hydro_cli/Cargo.toml, hydro_cli/hydro/__init__.py, hydro_cli/src/async_wrapper.py, hydro_cli/src/core/deployment.rs, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/core/terraform.rs, hydro_cli/src/core/util.rs, hydro_cli/src/main.rs, hydro_cli/src/python_interface.rs, hydro_cli/test.hydro.py
Also switches over some parts to use anyhow for error reporting, although I will do more refactoring for this in a later PR.
=> Initial support for GCP deployments

Cargo.lock, Cargo.toml, hydroflow/Cargo.toml, hydroflow/tests/datalog_frontend.rs, hydroflow/tests/groupby.rs, hydroflow/tests/surface_book.rs, hydroflow/tests/surface_codegen.rs, hydroflow/tests/surface_context.rs, hydroflow/tests/surface_difference.rs, hydroflow/tests/surface_fold.rs, hydroflow/tests/surface_forwardref.rs, hydroflow/tests/surface_group_by.rs, hydroflow/tests/surface_parser.rs, hydroflow/tests/surface_reduce.rs, hydroflow/tests/surface_state_scheduling.rs, hydroflow/tests/surface_stratum.rs, hydroflow/tests/test.rs, hydroflow/wasm.md, multiplatform_test/Cargo.toml, multiplatform_test/README.md, multiplatform_test/src/lib.rs
=> Turn on tests for WASM and add instructions for running.

.github/workflows/ci.yml
~~Might be able to remove `--no-default-features` now, but will do that in another PR if possible.~~
Oops, shouldn't have `--no-default-features` on for testing.
=> Add hydroflow WASM tests and check to CI

hydroflow_datalog_core/src/join_plan.rs, hydroflow_datalog_core/src/lib.rs, hydroflow_lang/src/graph/flat_graph.rs, hydroflow_lang/src/graph/flat_graph_builder.rs, hydroflow_lang/src/graph/flat_to_partitioned.rs, hydroflow_lang/src/graph/mod.rs, hydroflow_lang/src/graph/partitioned_graph.rs, hydroflow_macro/src/lib.rs
Part of the parser graph refactor
=> Encapsulate `FlatGraph`, separate `FlatGraphBuilder`

hydroflow_lang/src/graph/flat_graph_builder.rs
Needed to show warnings/errors in playground
=> Add `try_build` to flat graph to expose diagnostics

hydroflow/Cargo.toml, hydroflow/examples/vector_clock/README.md, hydroflow/examples/vector_clock/client.rs, hydroflow/examples/vector_clock/main.rs, hydroflow/examples/vector_clock/protocol.rs, hydroflow/examples/vector_clock/server.rs
I created a standalone example of a VC-stamped echo server. When we have modularity it would be nice to "layer" a VC "module" into the standard echo server.
=> vector clock example

.github/workflows/ci.yml, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydroflow/examples/cli_receiver/main.rs, hydroflow/examples/cli_sender/main.rs, hydroflow/src/util/cli.rs, hydroflow/src/util/mod.rs
Extract common logic for establishing CLI-configured connections
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/437).
* __->__ #437
=> Extract common logic for establishing CLI-configured connections

hydroflow/src/scheduled/context.rs, hydroflow/src/scheduled/graph.rs, hydroflow/src/scheduled/reactor.rs, hydroflow/tests/surface_fold.rs, hydroflow/tests/surface_group_by.rs, hydroflow/tests/surface_state_scheduling.rs, hydroflow_lang/src/graph/ops/fold.rs, hydroflow_lang/src/graph/ops/group_by.rs, hydroflow_lang/src/graph/ops/reduce.rs, hydroflow_lang/src/graph/ops/repeat_iter.rs
=> Avoid spinning on internal state replay, fix #380

.cargo/config.toml, .github/workflows/build-cli.yml, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, hydro_cli/Cargo.toml, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydroflow/Cargo.toml, hydroflow/src/util/cli.rs, hydroflow_cli_integration/Cargo.toml, hydroflow_cli_integration/src/lib.rs
Build CLI wheels in CI and minimize CLI dependencies
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/452).
* #454
* #453
* __->__ #452
=> Build CLI wheels in CI and minimize CLI dependencies

.github/workflows/build-cli.yml
Add CI config for building CLI for Windows
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/454).
* __->__ #454
=> Add CI config for building CLI for Windows

.cargo/config.toml, .github/workflows/ci.yml, Cargo.lock, hydro_cli/Cargo.toml, hydro_cli/src/core/custom_service.rs, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/lib.rs, hydro_cli/test.hydro.py, hydroflow/src/util/cli.rs, hydroflow_cli_integration/Cargo.toml, hydroflow_cli_integration/src/lib.rs
Support networking topologies that mix local and cloud through SSH tunneling
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/461).
* #466
* #462
* __->__ #461
=> Support networking topologies that mix local and cloud through SSH tunneling

Cargo.lock, hydro_cli/Cargo.toml, hydro_cli/hydro/_core.pyi, hydro_cli/src/core/deployment.rs, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate/ports.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/core/terraform.rs, hydro_cli/src/lib.rs, hydro_cli_examples/dedalus_python_client.hydro.py, hydro_cli_examples/simple_dedalus.hydro.py
Add initial VPC configuration API and improve interrupt handling
=> Add initial VPC configuration API and improve interrupt handling

hydro_cli/src/core/gcp.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/core/ssh.rs
Extract common SSH host logic into a separate module
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/474).
* #479
* #477
* __->__ #474
=> Extract common SSH host logic into a separate module

Cargo.lock, hydro_cli/src/core/terraform.rs, hydro_cli/src/lib.rs, hydro_cli_examples/examples/dedalus_receiver/main.rs, hydro_cli_examples/examples/dedalus_sender/main.rs, hydro_cli_examples/examples/stdout_receiver/main.rs, hydro_cli_examples/hydro_python_client.hydro.py, hydro_cli_examples/simple_dedalus.hydro.py, hydroflow/tests/compile-fail/surface_dest_sink_badsink.stderr, hydroflow_cli_integration/Cargo.toml, hydroflow_cli_integration/src/lib.rs
Properly handle interrupts and fix non-flushing demux
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/477).
* #481
* #479
* __->__ #477
=> Properly handle interrupts and fix non-flushing demux

hydro_cli/src/lib.rs
Display Anyhow traces when using directly using CLI APIs
=> Display Anyhow traces when using directly using CLI APIs

hydroflow_lang/src/graph/ops/group_by.rs
This is a cherry-pick of mingwei's fix from the kvs-benchmark branch
=> Remove extra clone in groupby

hydroflow_lang/src/graph/ops/initialize.rs, hydroflow_lang/src/graph/ops/mod.rs
=> Add `initialize()` operator equivalent to `source_iter([()])`

hydroflow_lang/src/graph/ops/repeat_iter.rs
=> document repeat_iter

hydro_cli/hydro/_core.pyi, hydro_cli/src/core/custom_service.rs, hydro_cli/src/core/hydroflow_crate/mod.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/core/ssh.rs, hydro_cli/src/lib.rs, hydro_cli_examples/examples/dedalus_receiver/main.rs, hydro_cli_examples/examples/dedalus_sender/main.rs, hydro_cli_examples/examples/stdout_receiver/main.rs, hydro_cli_examples/simple_dedalus.hydro.py, hydroflow/src/util/cli.rs
Add API to gracefully shutdown services
=> Add API to gracefully shutdown services

hydroflow/tests/datalog_frontend.rs, hydroflow_datalog_core/src/grammar.rs, hydroflow_datalog_core/src/lib.rs
Add support for arithmetic expressions on LHS of Dedalus rules
=> Add support for arithmetic expressions on LHS of Dedalus rules

hydro_cli/src/core/custom_service.rs, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate/mod.rs, hydro_cli_examples/dedalus_python_receiver.hydro.py
Allow redeployment in CLI with updated services and hosts
=> Allow redeployment in CLI with updated services and hosts

hydroflow_datalog_core/src/lib.rs, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__send_to_node@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__send_to_node@surface_graph.snap
Deduplicate facts that are being sent over the network
=> Deduplicate facts that are being sent over the network

Cargo.lock, hydroflow/Cargo.toml, hydroflow/src/lib.rs, hydroflow/tests/datalog_compile_fail.rs, hydroflow/tests/datalog_frontend.rs, hydroflow_datalog/src/lib.rs, hydroflow_datalog_core/Cargo.toml, hydroflow_datalog_core/src/grammar.rs, hydroflow_datalog_core/src/lib.rs, relalg/Cargo.toml, relalg/src/codegen.rs
=> Datalog fixups

hydro_cli/hydro/_core.pyi, hydro_cli/src/core/custom_service.rs, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate/ports.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/lib.rs, hydroflow_cli_integration/src/lib.rs
Add `hydro.null` API to connect no-op sources and sinks
=> Add `hydro.null` API to connect no-op sources and sinks

hydroflow/.gitignore, hydroflow_internalmacro/src/lib.rs, hydroflow_lang/src/graph/ops/dest_file.rs, hydroflow_lang/src/graph/ops/dest_sink.rs, hydroflow_lang/src/graph/ops/dest_sink_serde.rs, hydroflow_lang/src/graph/ops/mod.rs, hydroflow_lang/src/graph/ops/source_file.rs
close #55
Also a bit of operator housekeeping
=> `source_file` and `dest_file` operators for reading/writing line-by-line

hydroflow/src/lang/lattice/last_write_wins.rs, hydroflow/src/lang/lattice/mod.rs
=> Last write wins

hydro_cli/hydro/_core.pyi, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/terraform.rs, hydro_cli/src/lib.rs
Add `existing` parameter to `GCPNetwork` to use existing VPCs
=> Add `existing` parameter to `GCPNetwork` to use existing VPCs

hydro_cli/src/core/deployment.rs, hydro_cli/src/core/gcp.rs, hydro_cli_examples/Cargo.toml, hydro_cli_examples/examples/topolotree/main.rs, hydro_cli_examples/toplotree.hydro.py
Initial TopoloTree actor implementation for binary tree
=> Initial TopoloTree actor implementation for binary tree

hydro_cli/src/lib.rs
Actually return a `GCPComputeEngineHost` when creating one
=> Actually return a `GCPComputeEngineHost` when creating one

hydro_cli/src/core/deployment.rs
Provision hosts even if they are not being used by a service
=> Provision hosts even if they are not being used by a service

hydro_cli/src/core/gcp.rs, hydro_cli/src/core/terraform.rs, hydro_cli/src/lib.rs
Allow specifying the user to sign in as on a GCP machine
=> Allow specifying the user to sign in as on a GCP machine

.github/workflows/ci.yml, hydro_cli/hydro/_core.pyi, hydro_cli/python_tests/basic.py, hydro_cli/python_tests/demux.py, hydro_cli/python_tests/mux.py, hydro_cli/python_tests/requirements.txt, hydro_cli/src/core/custom_service.rs, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate/mod.rs, hydro_cli/src/core/hydroflow_crate/ports.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/lib.rs, hydro_cli_examples/Cargo.toml, hydro_cli_examples/examples/mux_stdout_receiver/main.rs, hydro_cli_examples/mux_python_sender.hydro.py, hydroflow_cli_integration/src/lib.rs
Add `hydro.mux` operator and initial API tests
=> Add `hydro.mux` operator and initial API tests

hydroflow/tests/datalog_frontend.rs, hydroflow_datalog_core/src/grammar.rs, hydroflow_datalog_core/src/join_plan.rs, hydroflow_datalog_core/src/lib.rs, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_predicate@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_predicate@surface_graph.snap
Support arithmetic expressions and literals in Datalog predicates
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/540).
* #543
* #542
* #541
* __->__ #540
=> Support arithmetic expressions and literals in Datalog predicates

hydroflow/tests/snapshots/surface_persist__persist_replay_join@graphvis_dot.snap, hydroflow/tests/snapshots/surface_persist__persist_replay_join@graphvis_mermaid.snap, hydroflow/tests/surface_persist.rs, hydroflow_lang/src/graph/ops/persist.rs
=> Fix persist() operator not self-scheduling for replay

hydro_cli/hydro/async_wrapper.py, hydro_cli/src/lib.rs, hydro_cli_examples/spin.hydro.py
Have Python drive CLI cancellations to support interrupting loops
=> Have Python drive CLI cancellations to support interrupting loops

hydroflow/tests/datalog_frontend.rs, hydroflow_datalog_core/src/grammar.rs, hydroflow_datalog_core/src/join_plan.rs, hydroflow_datalog_core/src/lib.rs, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_lhs@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_lhs@surface_graph.snap
Add remainder operator to Dedalus expressions
=> Add remainder operator to Dedalus expressions

hydroflow/tests/datalog_frontend.rs, hydroflow_datalog_core/src/grammar.rs, hydroflow_datalog_core/src/lib.rs, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_group_by_expr@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_group_by_expr@surface_graph.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_lhs@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_lhs@surface_graph.snap
Add multiplication operator and test behavior of aggregations with grouping expressions
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/571).
* #572
* __->__ #571
=> Add multiplication operator and test behavior of aggregations with grouping expressions

Cargo.lock, hydroflow_cli_integration/src/lib.rs
Place a buffer over each sink of a demux to avoid serial message sending
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/575).
* #574
* __->__ #575
=> Place a buffer over each sink of a demux to avoid serial message sending

hydro_cli/README.md, hydro_cli_examples/topolotree.hydro.py, hydro_cli_examples/topolotree_latency.hydro.py, hydroflow/src/lib.rs, rust-toolchain.toml
Bump pinned nightly and fix build failures on latest nightly
=> Bump pinned nightly and fix build failures on latest nightly

hydroflow/tests/surface_async.rs
just a loose test worth merging
=> Add async repeat_repeat iter test

hydro_cli/hydro/async_wrapper.py, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate/mod.rs, hydro_cli/src/core/ssh.rs, hydro_cli/src/lib.rs, hydro_cli_examples/topolotree_latency.hydro.py
Improve CLI interrupt handling when subtasks are spawned
=> Improve CLI interrupt handling when subtasks are spawned

Cargo.lock, benches/Cargo.toml, hydro_cli/Cargo.toml, hydro_cli/pyproject.toml, hydro_cli_examples/Cargo.toml, hydroflow/Cargo.toml, hydroflow_cli_integration/Cargo.toml, hydroflow_datalog/Cargo.toml, hydroflow_datalog_core/Cargo.toml, hydroflow_internalmacro/Cargo.toml, hydroflow_lang/Cargo.toml, hydroflow_macro/Cargo.toml, hydroflow_macro/build.rs, multiplatform_test/Cargo.toml, pusherator/Cargo.toml, pusherator/src/lib.rs, relalg/Cargo.toml, variadics/Cargo.toml
Released manually, merging this before setting up CI release
=> Update `cargo.toml`s for release

Cargo.lock, hydro_cli/Cargo.toml, hydro_cli/src/core/deployment.rs, hydro_cli/src/core/gcp.rs, hydro_cli/src/core/hydroflow_crate/mod.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/core/progress.rs, hydro_cli/src/core/ssh.rs, hydro_cli/src/core/terraform.rs, hydro_cli_examples/topolotree_latency.hydro.py
Display rich progress for deployment tasks in console
=> Display rich progress for deployment tasks in console

.github/workflows/audit.yml, .github/workflows/build-cli.yml, .github/workflows/ci.yml, .github/workflows/examples-container.yml, .github/workflows/release.yml, hydroflow/CHANGELOG.md, hydroflow_cli_integration/CHANGELOG.md, hydroflow_datalog/CHANGELOG.md, hydroflow_datalog_core/CHANGELOG.md, hydroflow_internalmacro/CHANGELOG.md, hydroflow_lang/CHANGELOG.md, hydroflow_macro/CHANGELOG.md, multiplatform_test/CHANGELOG.md, pusherator/CHANGELOG.md, variadics/CHANGELOG.md
`act workflow_dispatch --input bump=patch --input execute=false -j release_job --secret CARGO_REGISTRY_TOKEN=<REDACTED>`
=> Setup release workflow (manually-triggered)

hydro_cli/src/core/hydroflow_crate/build.rs, hydro_cli/src/core/hydroflow_crate/mod.rs, hydro_cli/src/core/progress.rs, hydro_cli/src/core/ssh.rs
Display cargo build status formatted next to a progress bar
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/627).
* #628
* __->__ #627
=> Display cargo build status formatted next to a progress bar

hydro_cli/src/core/terraform.rs
Handle Terraform printing a log about reading existing resources
=> Handle Terraform printing a log about reading existing resources

hydro_cli/src/core/hydroflow_crate/build.rs, hydro_cli/src/core/hydroflow_crate/mod.rs, hydro_cli/src/core/progress.rs
Avoid clobbering Rust errors with the progress bar
=> Avoid clobbering Rust errors with the progress bar

hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__index@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist_uniqueness@datalog_program.snap, hydroflow_lang/src/graph/ops/keyed_fold.rs, hydroflow_lang/src/graph/ops/keyed_reduce.rs, rust-toolchain.toml
=> Update pinned nightly to `nightly-2023-05-03`

hydro_cli/Cargo.toml, hydro_cli/pyproject.toml
Fix Hydro CLI builds failing due to breaking Maturin change
=> Fix Hydro CLI builds failing due to breaking Maturin change

hydroflow/src/util/unsync/mod.rs, hydroflow/src/util/unsync/mpsc.rs
=> unsync mpsc Sink impl

lattices/src/fake.rs
@zzlk would this break anything?
this has extra requirement of `T: PartialEq<O>` in `Merge<Fake<O>> for Fake<T>`
=> Allow fake to merge, compare equal values

hydro_cli_examples/examples/ws_chat_server/main.rs, hydroflow_lang/src/graph/ops/mod.rs
Missed these in the previous PR
=> remove last instances of tokio::main

docs/src/pages/index.module.css, docs/src/pages/research.js, docs/static/img/hydro-logo.svg
Fix paper images and adjust colors
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/680).
* #681
* __->__ #680
=> Fix paper images and adjust colors

.github/workflows/ci.yml, Cargo.lock, hydro_cli/Cargo.toml, hydro_cli/src/core/hydroflow_crate/build.rs, hydro_cli/src/core/hydroflow_crate/mod.rs, hydro_cli/src/lib.rs
Only load converters helper module once in the CLI
=> Only load converters helper module once in the CLI

docs/docusaurus.config.js, docs/src/pages/people.module.css, docs/src/pages/research.js
Fix paper preview rendering in dark mode
=> Fix paper preview rendering in dark mode

.github/workflows/build-cli.yml
Fix CLI wheel building for Maturin 1.0 release
=> Fix CLI wheel building for Maturin 1.0 release

.github/workflows/ci.yml, README.md, docs/docs/lattices_crate/index.mdx, docs/docs/lattices_crate/lattice_math.md, docs/src/pages/playground.js, lattices/README.md
* docs: update links from old to new book
* docs(lattices): simplified explanations, fixed typos, removed dead named links
=> docs: re-add latest rustdoc to ci gh-pages, update old book links, improve `lattices` docs

Cargo.lock, hydro_cli/Cargo.toml, hydroflow/Cargo.toml, hydroflow_cli_integration/Cargo.toml, hydroflow_datalog/Cargo.toml, hydroflow_datalog_core/Cargo.toml, hydroflow_internalmacro/Cargo.toml, hydroflow_lang/Cargo.toml, hydroflow_macro/Cargo.toml
For release on crates.io for v0.1
=> chore: bump versions to 0.1.0 for release

docs/docusaurus.config.js
=> Add Algolia search

hydroflow/examples/shopping/README.md, hydroflow/examples/shopping/flows/orig_flow.rs
Put header on README
Remove diagnostic `inspect` from `orig_flow.rs`
=> minor cleanup for shopping example

.github/workflows/conventional_commits.yml
https://www.conventionalcommits.org/en/
This enables better automatic changelogs from the release workflow
=> Use conventional commits, enforce in CI

docs/docs/hydroflow/quickstart/example_4_neighbors.md, docs/docs/hydroflow/todo.md, hydroflow/tests/snapshots/surface_codegen__sort_by_key@graphvis_dot.snap, hydroflow/tests/snapshots/surface_codegen__sort_by_key@graphvis_mermaid.snap, hydroflow/tests/surface_codegen.rs, hydroflow_lang/src/graph/ops/fold_keyed.rs, hydroflow_lang/src/graph/ops/mod.rs, hydroflow_lang/src/graph/ops/reduce_keyed.rs, hydroflow_lang/src/graph/ops/sort_by_key.rs
=> _keyed, _by_key op renames, fix #705

hydroflow/Cargo.toml, hydroflow/src/lib.rs, hydroflow/src/util/monotonic_map.rs, hydroflow/tests/surface_codegen.rs, hydroflow/tests/surface_zip_unzip.rs, hydroflow_lang/src/graph/ops/mod.rs, hydroflow_lang/src/graph/ops/zip.rs, hydroflow_lang/src/graph/ops/zip_longest.rs
=> Add `zip` and `zip_longest` #707

.github/workflows/build-cli.yml, .github/workflows/release.yml, hydro_cli/Cargo.toml
Will bump versions for python pypi publish
=> ci(release): publish hydro_cli

hydro_cli/src/core/custom_service.rs, hydro_cli/src/lib.rs, hydro_cli_examples/examples/ws_chat_server/main.rs, hydro_cli_examples/examples/ws_chat_server/util.rs, hydro_cli_examples/ws_chat_server.py, hydroflow/src/util/cli.rs, hydroflow_cli_integration/src/lib.rs
feat(hydro_deploy): finish up WebSocket chat example and avoid deadlocks in network setup
=> feat(hydro_deploy): finish up WebSocket chat example and avoid deadlocks in network setup

hydroflow/tests/surface_persist.rs, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__index@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist@datalog_program.snap, hydroflow_lang/src/graph/ops/persist.rs
Add surface_double_handoff tests
=> fix(hydroflow_lang): fix `persist` releasing multiple times during the same tick

hydro_cli/src/core/hydroflow_crate/build.rs, hydro_cli/src/core/localhost.rs, hydro_cli/src/core/mod.rs, hydro_cli/src/core/ssh.rs
fix(deploy): don't create file copies on when deploying to localhost
This causes issues on M1, likely due to some signing issue?
=> fix(deploy): don't create file copies on when deploying to localhost

hydroflow_cli_integration/src/lib.rs
fix(deploy): fix CLI build on windows
=> fix(deploy): fix CLI build on windows

docs/README.md, docs/docs/deploy/your-first-deploy.md
fix(docs): add proper documentation on building the site locally and fix typo in deploy docs
Fixes #731
=> fix(docs): add proper documentation on building the site locally and fix typo in deploy docs

lattices/src/lib.rs, lattices/src/top.rs
this is almost an exact copy of bottom, maybe we can factor it out at some point
=> feat: add top lattice, opposite of bottom

hydroflow/tests/surface_scheduling.rs
Have a fix for the scheduling bug incoming
=> test(hydroflow): add `test_stratum/tick_loop` tests

hydroflow/examples/kvs_bench/protocol/mod.rs, hydroflow/examples/kvs_bench/protocol/serialization/lattices/point.rs, hydroflow/examples/kvs_bench/protocol/serialization/lattices/with_bot.rs, lattices/src/point.rs
BREAKING CHANGE: `Point` added `Provenance` generic param.
=> feat(lattices)!: Add `Provenance` generic param token to `Point`.

Cargo.lock
fix(hydroflow_datalog_core): bump webbrowser, which had a vulnerability
=> fix(hydroflow_datalog_core): bump webbrowser, which had a vulnerability

docs/docs/hydroflow/quickstart/example_4_neighbors.md, docs/docs/hydroflow/quickstart/example_5_reachability.md, docs/docs/hydroflow/quickstart/example_6_unreachability.md, docs/docs/hydroflow/quickstart/example_7_echo_server.md, docs/docs/hydroflow/quickstart/example_8_chat_server.md, docs/docs/hydroflow/quickstart/setup.md, docs/docs/hydroflow/syntax/surface_data.md, docs/docs/hydroflow/syntax/surface_flows.md, docs/package.json
I went through the Quickstart in the docs and tried to make sure all the code works, and the mermaid is consistent with the code. There were many bugs! 
I have some related complaints here: issues #734, #736 and #737.
=> fix up quickstart docs

Cargo.lock, hydroflow/Cargo.toml, hydroflow/deprecated_examples/covid_tracing/main.rs, hydroflow/src/lib.rs, hydroflow/src/scheduled/graph.rs, hydroflow_cli_integration/src/lib.rs, hydroflow_datalog/Cargo.toml, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__index@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist_uniqueness@datalog_program.snap, hydroflow_lang/Cargo.toml, hydroflow_lang/src/diagnostic.rs, hydroflow_lang/src/graph/flat_graph_builder.rs, hydroflow_lang/src/graph/ops/fold_keyed.rs, hydroflow_lang/src/graph/ops/reduce_keyed.rs, hydroflow_lang/src/lib.rs, hydroflow_macro/Cargo.toml, hydroflow_macro/src/lib.rs, lattices/src/lib.rs, pusherator/src/lib.rs
=> Enable hydroflow on stable rust

.github/workflows/ci.yml, build_docs.bash, docs/README.md
feat(docs): add instructions for adding papers and build the site in GitHub actions
=> feat(docs): add instructions for adding papers and build the site in GitHub actions

.github/workflows/ci.yml, Cargo.lock, hydroflow/Cargo.toml, hydroflow/examples/python_udf/main.rs, hydroflow/tests/snapshots/surface_python__python_basic@graphvis_dot.snap, hydroflow/tests/snapshots/surface_python__python_basic@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_python__python_too_many_args@graphvis_dot.snap, hydroflow/tests/snapshots/surface_python__python_too_many_args@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_python__python_two_args@graphvis_dot.snap, hydroflow/tests/snapshots/surface_python__python_two_args@graphvis_mermaid.snap, hydroflow/tests/surface_python.rs, hydroflow_lang/build.rs, hydroflow_lang/src/graph/ops/mod.rs, hydroflow_lang/src/graph/ops/py_udf.rs
right now set it up to only accept single-argument python func s
bit experimental for now
=> add `py_udf` operator [wip]

build_docs.bash, docs/README.md, docs/docs/hydroflow/quickstart/example_4_neighbors.mdx, docs/docs/hydroflow/quickstart/example_6_unreachability.mdx, docs/docusaurus.config.js, docs/src/pages/playground.js, docs/wasm-plugin.js
feat(docs): allow building docs without playground
=> feat(docs): allow building docs without playground

docs/README.md, website_playground/Cargo.toml
fix(docs): build Hydroflow for playground demo with only WASM features
=> fix(docs): build Hydroflow for playground demo with only WASM features

hydroflow/Cargo.toml, hydroflow/src/declarative_macro.rs, hydroflow/src/lib.rs, hydroflow_lang/src/graph/ops/py_udf.rs
Refs: #792, 7dbd5e24d6e71cf8fab7c3ce09d5937c0f301456
=> fix: `py_udf` operator feature gating

hydroflow/tests/snapshots/surface_batch__basic_2@graphvis_dot.snap, hydroflow/tests/snapshots/surface_batch__basic_2@graphvis_mermaid.snap, hydroflow/tests/surface_batch.rs, hydroflow/tests/surface_codegen.rs, hydroflow_lang/src/graph/ops/batch.rs
fixes https://github.com/hydro-project/hydroflow/issues/724
=> feat: make batch take two inputs [input] and [signal]

.github/workflows/ci.yml, hydroflow/Cargo.toml, website_playground/Cargo.toml
fixes https://github.com/hydro-project/hydroflow/issues/811
example: https://github.com/hydro-project/hydroflow/actions/runs/5491587234/jobs/10008253130
=> fix: remove python from default features, add it to ci

hydroflow/examples/chat/server.rs, hydroflow/examples/deadlock_detector/peer.rs, hydroflow/examples/kvs/server.rs, hydroflow/examples/shopping/flows/bp_flow.rs, hydroflow/examples/shopping/flows/client_state_flow.rs, hydroflow/examples/shopping/flows/orig_flow.rs, hydroflow/examples/shopping/flows/push_group_flow.rs, hydroflow/examples/shopping/flows/rep_server_flow.rs, hydroflow/examples/shopping/flows/server_state_flow.rs, hydroflow/examples/shopping/flows/ssiv_flow.rs, hydroflow/examples/three_clique/main.rs, hydroflow/examples/two_pc/coordinator.rs, hydroflow/examples/two_pc/subordinate.rs, hydroflow/tests/surface_persist.rs, hydroflow_lang/src/graph/ops/cross_join.rs, hydroflow_lang/src/graph/ops/enumerate.rs, hydroflow_lang/src/graph/ops/fold.rs, hydroflow_lang/src/graph/ops/fold_keyed.rs, hydroflow_lang/src/graph/ops/join.rs, hydroflow_lang/src/graph/ops/lattice_fold.rs, hydroflow_lang/src/graph/ops/lattice_join.rs, hydroflow_lang/src/graph/ops/lattice_reduce.rs, hydroflow_lang/src/graph/ops/reduce.rs, hydroflow_lang/src/graph/ops/reduce_keyed.rs, hydroflow_lang/src/graph/ops/unique.rs
fixes https://github.com/hydro-project/hydroflow/issues/786
=> fix: make all operators 'tick by default

hydroflow/examples/chat/main.rs, hydroflow/examples/echo_serde_json/main.rs, hydroflow/examples/echoserver/main.rs, hydroflow/examples/kvs/main.rs, hydroflow/examples/lamport_clock/main.rs, hydroflow/examples/vector_clock/main.rs, hydroflow/tests/compile-fail/surface_conflicting_name.stderr, hydroflow/tests/compile-fail/surface_use_bad1.rs, hydroflow/tests/compile-fail/surface_use_bad1.stderr, hydroflow/tests/compile-fail/surface_use_bad2.rs, hydroflow/tests/compile-fail/surface_use_bad2.stderr, hydroflow/tests/compile-fail/surface_use_bad3.rs, hydroflow/tests/compile-fail/surface_use_bad3.stderr, hydroflow/tests/compile-fail/surface_use_unknown.rs, hydroflow/tests/compile-fail/surface_use_unknown.stderr, hydroflow_datalog_core/src/join_plan.rs, hydroflow_datalog_core/src/lib.rs, hydroflow_lang/build.rs, hydroflow_lang/src/graph/flat_graph_builder.rs, hydroflow_lang/src/graph/hydroflow_graph.rs, hydroflow_lang/src/graph/mod.rs, hydroflow_lang/src/graph/ops/lattice_join.rs, hydroflow_lang/src/graph/ops/py_udf.rs, hydroflow_lang/src/graph/ops/source_stdin.rs, hydroflow_lang/src/parse.rs, hydroflow_macro/src/lib.rs, website_playground/src/lib.rs
And use in doc tests.
Fix #783
Fix #838
=> feat(hydroflow_lang): Add `use` statements to hydroflow syntax

docs/docs/hydroflow/quickstart/example_8_chat_server.mdx, hydroflow/examples/chat/client.rs, hydroflow_lang/src/graph/ops/cross_join.rs, hydroflow_lang/src/graph/ops/defer_tick.rs, hydroflow_lang/src/graph/ops/demux.rs, hydroflow_lang/src/graph/ops/dest_sink_serde.rs, hydroflow_lang/src/graph/ops/difference.rs, hydroflow_lang/src/graph/ops/fold_keyed.rs, hydroflow_lang/src/graph/ops/lattice_join.rs, hydroflow_lang/src/graph/ops/lattice_reduce.rs, hydroflow_lang/src/graph/ops/multiset_delta.rs, hydroflow_lang/src/graph/ops/persist.rs, hydroflow_lang/src/graph/ops/reduce.rs, hydroflow_lang/src/graph/ops/reduce_keyed.rs, hydroflow_lang/src/graph/ops/sort.rs, hydroflow_lang/src/graph/ops/sort_by_key.rs, hydroflow_lang/src/graph/ops/source_file.rs, hydroflow_lang/src/graph/ops/source_interval.rs, hydroflow_lang/src/graph/ops/source_stream_serde.rs, hydroflow_lang/src/graph/ops/spin.rs
Further edits to the book, focusing on operator documentation.
=> book updates

lattices/README.md, lattices/src/lib.rs
=> docs(lattices): Improve `Atomize` docs

docs/docs/hydroflow/quickstart/example_8_chat_server.mdx, docs/docs/hydroflow/todo.md, hydroflow/examples/chat/client.rs
=> fix: change "gated buffer" discussion from `cross_join` to `defer_signal`

benches/benches/join.rs, benches/benches/reachability.rs, hydroflow/tests/test.rs, hydroflow_datalog_core/src/join_plan.rs
Clippy lint `unwrap_or_default` complaining on latest nightly
=> chore: Replace `or_insert_with(Vec::new)` with `or_default()`

lattices/README.md, lattices/src/lib.rs, lattices/src/map_union.rs, lattices/src/set_union.rs, lattices/src/test.rs, lattices/src/union_find.rs, lattices/src/unit.rs, lattices/src/with_bot.rs, lattices/src/with_top.rs
<a href="https://en.wikipedia.org/wiki/File:Set_partitions_4;_Hasse;_circles.svg">
</a>
=> Add `UnionFind` lattice, cleanup some of the lattice crate

Cargo.lock, hydroflow/Cargo.toml, hydroflow_lang/Cargo.toml, hydroflow_lang/src/graph/hydroflow_graph_debugging.rs, hydroflow_lang/src/graph/mod.rs
* `HydroflowGraph::open_mermaid()` opens https://mermaid.live/
* `HydroflowGraph::open_dot()` opens https://dreampuf.github.io/GraphvizOnline/
Behind the `hydroflow/debugging`/`hydroflow_lang/debugging` feature gate.
=> feat(hydroflow_lang): open mermaid/dot graph in browser

hydro_cli/src/core/hydroflow_crate/ports.rs
fixes https://github.com/hydro-project/hydroflow/issues/877
=> fix: better error message when using wrong port types

hydroflow_lang/src/graph/graph_write.rs, hydroflow_lang/src/graph/hydroflow_graph.rs
=> fix(hydroflow_lang): fix/improve rendering with `--no-handoffs` and double-labelled edges

hydroflow/tests/compile-fail/surface_degenerate_null.stderr, hydroflow/tests/compile-fail/surface_null.stderr, hydroflow_lang/src/graph/hydroflow_graph.rs
=> fix(hydroflow_lang): avoid panic-ing on degen `null()`

benches/benches/micro_ops.rs, hydro_cli_examples/examples/pn_counter/main.rs, hydro_cli_examples/examples/pn_counter_delta/main.rs, hydro_cli_examples/examples/topolotree/main.rs, hydroflow/examples/deadlock_detector/peer.rs, hydroflow/examples/lamport_clock/client.rs, hydroflow/examples/lamport_clock/server.rs, hydroflow/examples/two_pc/coordinator.rs, hydroflow/examples/vector_clock/client.rs, hydroflow/examples/vector_clock/server.rs, hydroflow/tests/snapshots/surface_fold__fold_sort@graphvis_dot.snap, hydroflow/tests/snapshots/surface_fold__fold_sort@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_fold__fold_static@graphvis_dot.snap, hydroflow/tests/snapshots/surface_fold__fold_static@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_fold__fold_tick@graphvis_dot.snap, hydroflow/tests/snapshots/surface_fold__fold_tick@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_persist__persist_basic@graphvis_dot.snap, hydroflow/tests/snapshots/surface_persist__persist_basic@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_persist__persist_pull@graphvis_dot.snap, hydroflow/tests/snapshots/surface_persist__persist_pull@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_persist__persist_push@graphvis_dot.snap, hydroflow/tests/snapshots/surface_persist__persist_push@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_persist__persist_replay_join@graphvis_dot.snap, hydroflow/tests/snapshots/surface_persist__persist_replay_join@graphvis_mermaid.snap, hydroflow/tests/surface_fold.rs, hydroflow/tests/surface_lattice_fold.rs, hydroflow/tests/surface_persist.rs, hydroflow/tests/surface_state_scheduling.rs, hydroflow_lang/src/graph/ops/fold.rs, hydroflow_lang/src/graph/ops/lattice_fold.rs
fixes https://github.com/hydro-project/hydroflow/issues/903
=> fix: fold takes initial value by closure rather than by value

hydroflow/tests/surface_multiset_delta.rs, hydroflow_lang/src/graph/ops/multiset_delta.rs
Introduced in #906
Also adds more `multiset_delta` tests.
Refs: #958, #906
=> fix(hydroflow_lang): `multiset_delta` incorrect `is_first_run_this_tick` check, fixes #958

hydro_cli/src/core/deployment.rs, hydro_cli/src/core/hydroflow_crate/ports.rs, topolotree/src/latency_measure.rs, topolotree/src/main.rs, topolotree/src/protocol.rs, topolotree/src/tests.rs, topolotree/topolotree_latency.hydro.py
feat(topolotree): implement core fault tolerance protocol
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/910).
* #914
* __->__ #910
=> feat(topolotree): implement core fault tolerance protocol

.github/workflows/build-cli.yml
fix(hydro_deploy): paths for building wheels in CI
=> fix(hydro_deploy): paths for building wheels in CI

docs/docs/hydroflow_plus/distributed.mdx, hydro_deploy/core/src/deployment.rs, hydro_deploy/core/src/hydroflow_crate/mod.rs, hydro_deploy/core/src/hydroflow_crate/ports.rs, hydro_deploy/core/src/lib.rs, hydro_deploy/hydro_cli/src/lib.rs, hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs, hydroflow_plus_test/examples/first_ten_distributed.rs, hydroflow_plus_test/examples/map_reduce.rs, hydroflow_plus_test/examples/networked_basic.rs, hydroflow_plus_test/examples/simple_cluster.rs, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/first_ten.rs, hydroflow_plus_test/src/networked.rs
feat(hydro_deploy): improve Rust API for defining services
=> feat(hydro_deploy): improve Rust API for defining services

docs/docs/hydroflow_plus/distributed.mdx, hydro_deploy/core/src/custom_service.rs
fix(hydroflow_plus): fix docs and remove unnecessary async_trait
=> fix(hydroflow_plus): fix docs and remove unnecessary async_trait

Cargo.lock, Dockerfile, hydro_deploy/core/Cargo.toml, hydro_deploy/hydro_cli/Cargo.toml
fix(hydro_deploy): don't vendor openssl and fix docker build
=> fix(hydro_deploy): don't vendor openssl and fix docker build

hydroflow_plus/src/cycle.rs, hydroflow_plus/src/lib.rs, hydroflow_plus/src/node/mod.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/lib.rs
feat(hydroflow_plus): require explicit batching for aggregation operators
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/991).
* #996
* #995
* #993
* __->__ #991
=> feat(hydroflow_plus): require explicit batching for aggregation operators

hydroflow_plus/src/builder.rs, hydroflow_plus/src/node/graphs.rs, hydroflow_plus_test/src/first_ten.rs, hydroflow_plus_test/src/lib.rs
feat(hydroflow_plus): split API for building single-node graphs
=> feat(hydroflow_plus): split API for building single-node graphs

docs/docs/hydroflow_plus/distributed.mdx, docs/docs/hydroflow_plus/structure.mdx, hydro_deploy/core/src/hydroflow_crate/mod.rs, hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs, hydro_deploy/hydroflow_plus_cli_integration/src/lib.rs, hydro_deploy/hydroflow_plus_cli_integration/src/runtime.rs, hydroflow_plus/src/builder.rs, hydroflow_plus/src/cycle.rs, hydroflow_plus/src/lib.rs, hydroflow_plus/src/node/graphs.rs, hydroflow_plus/src/node/mod.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/examples/first_ten_distributed.rs, hydroflow_plus_test/examples/map_reduce.rs, hydroflow_plus_test/examples/networked_basic.rs, hydroflow_plus_test/examples/simple_cluster.rs, hydroflow_plus_test/src/bin/first_ten_distributed.rs, hydroflow_plus_test/src/bin/many_to_many.rs, hydroflow_plus_test/src/bin/map_reduce.rs, hydroflow_plus_test/src/bin/networked_basic.rs, hydroflow_plus_test/src/bin/simple_cluster.rs, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/first_ten.rs, hydroflow_plus_test/src/lib.rs, hydroflow_plus_test/src/networked.rs
feat(hydroflow_plus): improve API naming and eliminate wire API for builders
=> feat(hydroflow_plus): improve API naming and eliminate wire API for builders

.github/workflows/build-cli.yml
fix(hydro_deploy): openssl builds in manylinux containers
=> fix(hydro_deploy): openssl builds in manylinux containers

.github/workflows/build-cli.yml
fix(hydro_deploy): i686 Python package builds in CI
=> fix(hydro_deploy): i686 Python package builds in CI

hydroflow_lang/src/graph/di_mul_graph.rs
fix(hydroflow_lang): clippy lints on latest nightly
=> fix(hydroflow_lang): clippy lints on latest nightly

hydroflow_plus/src/stream.rs
fix(hydroflow_plus): disallow joining streams on different nodes
=> fix(hydroflow_plus): disallow joining streams on different nodes

hydroflow_plus/Cargo.toml, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/bin/map_reduce.rs
fix(hydroflow_plus): rewrite uses of alloc crate in bincode operators
=> fix(hydroflow_plus): rewrite uses of alloc crate in bincode operators

docs/docs/hydroflow_plus/clusters.mdx, docs/docs/hydroflow_plus/distributed.mdx, docs/docs/hydroflow_plus/structure.mdx
docs(hydroflow_plus): add docs for using clusters
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1002).
* #1007
* __->__ #1002
=> docs(hydroflow_plus): add docs for using clusters

docs/docs/hydroflow_plus/aggregations.mdx, docs/docs/hydroflow_plus/clusters.mdx, docs/docs/hydroflow_plus/cycles.mdx, docs/docs/hydroflow_plus/index.mdx, docs/docs/hydroflow_plus/nodes_streams.mdx, docs/docs/hydroflow_plus/quickstart/_category_.json, docs/docs/hydroflow_plus/quickstart/clusters.mdx, docs/docs/hydroflow_plus/quickstart/distributed.mdx, docs/docs/hydroflow_plus/quickstart/index.mdx, docs/docs/hydroflow_plus/quickstart/structure.mdx, docs/docs/hydroflow_plus/stageleft.mdx, hydroflow_plus_test/src/cluster.rs
docs(hydroflow_plus): explain clusters and aggregation semantics
=> docs(hydroflow_plus): explain clusters and aggregation semantics

docs/docusaurus.config.js, docs/src/pages/index.js, docs/src/pages/index.module.css, docs/src/pages/research.js, docs/src/pages/research.module.css
feat(docs): clean up landing page
Improves readability of the homepage, especially on mobile.
=> feat(docs): clean up landing page

docs/docusaurus.config.js
fix(docs): respect OS dark mode
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1019).
* #1020
* __->__ #1019
=> fix(docs): respect OS dark mode

docs/docs/hydroflow/quickstart/index.md, docs/docs/hydroflow_plus/index.mdx, docs/docs/hydroflow_plus/quickstart/clusters.mdx, docs/docs/hydroflow_plus/quickstart/distributed.mdx, docs/docs/hydroflow_plus/quickstart/index.mdx, docs/docs/hydroflow_plus/quickstart/structure.mdx
docs(hydroflow_plus): make bash snippets copyable and link from Hydroflow landing
=> docs(hydroflow_plus): make bash snippets copyable and link from Hydroflow landing

Cargo.lock, hydroflow_lang/src/graph/ops/reduce.rs, hydroflow_plus/Cargo.toml, hydroflow_plus/build.rs, hydroflow_plus/src/builder.rs, hydroflow_plus/src/cycle.rs, hydroflow_plus/src/lib.rs, hydroflow_plus/src/location/mod.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/Cargo.toml, hydroflow_plus_test/examples/compute_pi.rs, hydroflow_plus_test/src/bin/compute_pi.rs, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__tests__chat_app_no_replay@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__tests__chat_app_no_replay@graphvis_mermaid.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__tests__chat_app_replay@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__tests__chat_app_replay@graphvis_mermaid.snap, hydroflow_plus_test_macro/Cargo.toml, stageleft/src/runtime_support.rs, stageleft_macro/src/quote_impl/free_variable/mod.rs, stageleft_tool/src/lib.rs
feat(hydroflow_plus): push down persists and implement Pi example
Also fixes type inference issues with reduce the same way as we did for fold.
=> feat(hydroflow_plus): push down persists and implement Pi example

docs/docs/hydroflow_plus/clusters.mdx, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/cluster.rs
feat(hydroflow_plus): add interleaved shortcut when sending from a cluster
=> feat(hydroflow_plus): add interleaved shortcut when sending from a cluster

hydroflow/src/compiled/pull/anti_join.rs, hydroflow/tests/snapshots/surface_examples__example_6_unreachability.snap, hydroflow/tests/surface_codegen.rs, hydroflow/tests/surface_difference.rs, hydroflow_lang/src/graph/ops/anti_join.rs, hydroflow_lang/src/graph/ops/difference.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/lib.rs, hydroflow_plus_test/src/negation.rs, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__anti_join_static_static@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__anti_join_static_static@graphvis_mermaid.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__anti_join_static_tick@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__anti_join_static_tick@graphvis_mermaid.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__anti_join_tick_static@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__anti_join_tick_static@graphvis_mermaid.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__anti_join_tick_tick@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__anti_join_tick_tick@graphvis_mermaid.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__difference_static_static@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__difference_static_static@graphvis_mermaid.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__difference_static_tick@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__difference_static_tick@graphvis_mermaid.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__difference_tick_static@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__difference_tick_static@graphvis_mermaid.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__difference_tick_tick@graphvis_dot.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__negation__tests__difference_tick_tick@graphvis_mermaid.snap
feat(hydroflow_plus): add core negation operators
This also adjusts difference/anti_join to have multi-set semantics on pos inputs and preserve order for new elements received in the current tick.
=> feat(hydroflow_plus): add core negation operators

lattices/src/collections.rs, lattices/src/lib.rs, lattices/src/map_union_with_tombstones.rs
=> feat(lattices): add map_union_with_tombstones, fix #336

hydroflow/tests/surface_lattice_join.rs, hydroflow_lang/src/graph/ops/_lattice_join_fused_join.rs
=> fix(hydroflow_lang): fix coloring of `_lattice_join_fused_join`, fix #943

.github/workflows/ci.yml
ci: make sure we have fmt and clippy and don't cache latest nightly
=> ci: make sure we have fmt and clippy and don't cache latest nightly

.github/workflows/ci.yml
ci: don't fail fast lints and tests
=> ci: don't fail fast lints and tests

docs/docs/hydroflow_plus/clusters.mdx, hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs, hydro_deploy/hydroflow_plus_cli_integration/src/runtime.rs, hydroflow_plus/src/builder.rs, hydroflow_plus/src/location/graphs.rs, hydroflow_plus/src/location/mod.rs, hydroflow_plus/src/location/network.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/networked.rs, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__networked__tests__networked_basic.snap
feat(hydroflow_plus): unify send/demux/tagged APIs
=> feat(hydroflow_plus): unify send/demux/tagged APIs

Cargo.lock, hydroflow_plus/Cargo.toml, hydroflow_plus/src/builder.rs, hydroflow_plus/src/ir.rs, hydroflow_plus/src/lib.rs, hydroflow_plus/src/persist_pushdown.rs, hydroflow_plus/src/snapshots/hydroflow_plus__persist_pushdown__tests__persist_pullup_behind_tee-2.snap, hydroflow_plus/src/snapshots/hydroflow_plus__persist_pushdown__tests__persist_pullup_behind_tee.snap, hydroflow_plus/src/snapshots/hydroflow_plus__persist_pushdown__tests__persist_pullup_through_map-2.snap, hydroflow_plus/src/snapshots/hydroflow_plus__persist_pushdown__tests__persist_pullup_through_map.snap, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/first_ten.rs, hydroflow_plus_test/src/lib.rs, hydroflow_plus_test/src/negation.rs, hydroflow_plus_test/src/networked.rs, stageleft_tool/src/lib.rs
feat(hydroflow_plus): add APIs for running optimization passes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1083).
* #1098
* __->__ #1083
=> feat(hydroflow_plus): add APIs for running optimization passes

hydroflow/tests/datalog_frontend.rs, hydroflow_datalog_core/src/grammar.rs, hydroflow_datalog_core/src/lib.rs, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__collect_vec@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__collect_vec@surface_graph.snap
feat(hydroflow_datalog): add aggregation for collecting values into a vector
=> feat(hydroflow_datalog): add aggregation for collecting values into a vector

docs/docs/hydroflow_plus/quickstart/distributed.mdx, docs/docs/hydroflow_plus/quickstart/structure.mdx
docs(hydroflow_plus): fix references to old APIs
=> docs(hydroflow_plus): fix references to old APIs

hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__compute_pi_ir.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__compute_pi_ir@surface_graph_0.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__compute_pi_ir@surface_graph_1.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__map_reduce_ir.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__map_reduce_ir@surface_graph_0.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__map_reduce_ir@surface_graph_1.snap, stageleft_macro/src/quote_impl/free_variable/mod.rs, stageleft_macro/src/quote_impl/mod.rs, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_copy_local@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_copy_local_block@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_copy_local_block_let@macro_tokens.snap
fix(stageleft): handle multiple references to copy-able free variables
Fixes #1103
=> fix(stageleft): handle multiple references to copy-able free variables

lattices/Cargo.toml, lattices/src/algebra.rs, lattices/src/lib.rs
initial commit of the algebra library with the basic properties and algebraic structures
=> Initial Algebra Library

Cargo.lock, docs/docs/hydroflow_plus/aggregations.mdx, docs/docs/hydroflow_plus/clusters.mdx, docs/docs/hydroflow_plus/cycles.mdx, docs/docs/hydroflow_plus/process_streams.mdx, docs/docs/hydroflow_plus/quickstart/clusters.mdx, docs/docs/hydroflow_plus/quickstart/distributed.mdx, docs/docs/hydroflow_plus/quickstart/structure.mdx, hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs, hydro_deploy/hydroflow_plus_cli_integration/src/runtime.rs, hydroflow_plus/Cargo.toml, hydroflow_plus/src/builder.rs, hydroflow_plus/src/cycle.rs, hydroflow_plus/src/location/graphs.rs, hydroflow_plus/src/location/mod.rs, hydroflow_plus/src/location/network.rs, hydroflow_plus/src/persist_pullup.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/first_ten.rs, hydroflow_plus_test/src/lib.rs, hydroflow_plus_test/src/negation.rs, hydroflow_plus_test/src/networked.rs, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__compute_pi_ir.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__compute_pi_ir@surface_graph_0.snap
feat(hydroflow_plus): simplify Location trait to remove lifetimes
Summary:
Test Plan:
=> feat(hydroflow_plus): simplify Location trait to remove lifetimes

hydroflow_datalog_core/src/lib.rs
fix(hydroflow_datalog): leftover comments
Merged too soon.
=> fix(hydroflow_datalog): leftover comments

docs/docs/hydroflow_plus/quickstart/distributed.mdx, hydroflow/src/util/cli.rs, hydroflow_plus_test/examples/compute_pi.rs, hydroflow_plus_test/src/bin/compute_pi.rs, hydroflow_plus_test/src/bin/first_ten_distributed.rs, hydroflow_plus_test/src/bin/many_to_many.rs, hydroflow_plus_test/src/bin/map_reduce.rs, hydroflow_plus_test/src/bin/networked_basic.rs, hydroflow_plus_test/src/bin/simple_cluster.rs, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__compute_pi_ir.snap, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__compute_pi_ir@surface_graph_0.snap
feat(hydroflow_plus): switch launch to be a macro to enable borrowing locals
Summary:
Test Plan:
=> feat(hydroflow_plus): switch launch to be a macro to enable borrowing locals

docs/src/pages/playground.js, hydroflow/tests/snapshots/surface_singleton__state_ref@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__state_ref@graphvis_mermaid.snap, hydroflow_lang/src/graph/graph_write.rs, hydroflow_lang/src/graph/hydroflow_graph.rs, website_playground/src/lib.rs
=> feat(hydroflow_lang): Render singleton references in graphvis

hydroflow/tests/snapshots/surface_singleton__reduce_singleton@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__reduce_singleton@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_singleton__reduce_singleton_push@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__reduce_singleton_push@graphvis_mermaid.snap, hydroflow/tests/surface_lattice_fold.rs, hydroflow/tests/surface_singleton.rs, hydroflow_lang/src/graph/ops/fold.rs, hydroflow_lang/src/graph/ops/lattice_fold.rs, hydroflow_lang/src/graph/ops/lattice_reduce.rs, hydroflow_lang/src/graph/ops/reduce.rs
fixed bug: accumulator closures could have return values, which would be ignored
updated docs
=> feat(hydroflow_lang): allow `reduce()` to be referenceable as a singleton, fix docs and bugs

hydroflow_plus_test/src/lib.rs, hydroflow_plus_test_macro/Cargo.toml, hydroflow_plus_test_macro/src/lib.rs, stageleft/README.md, stageleft/src/lib.rs, stageleft_macro/src/lib.rs, stageleft_macro/src/quote_impl/mod.rs, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_copy_local@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_copy_local_block@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_copy_local_block_let@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_in_macro@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_local@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__capture_local_mut@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__non_capture_enum_creation@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__non_capture_local@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__non_capture_struct_creation@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__prelude_enum_variants@macro_tokens-2.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__prelude_enum_variants@macro_tokens-3.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__prelude_enum_variants@macro_tokens-4.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__prelude_enum_variants@macro_tokens.snap, stageleft_macro/src/quote_impl/snapshots/stageleft_macro__quote_impl__tests__simple@macro_tokens.snap, stageleft_test/src/lib.rs, stageleft_test_macro/Cargo.toml, stageleft_test_macro/src/lib.rs, stageleft_tool/src/lib.rs
feat(stageleft): re-compile staged sources for the macro at the top level
Summary:
Test Plan:
=> feat(stageleft): re-compile staged sources for the macro at the top level

Cargo.lock, design_docs/2021-10_architecture_design_doc.md, hydro_deploy/hydro_cli/Cargo.toml, hydro_deploy/hydro_cli/src/lib.rs, hydroflow/Cargo.toml, hydroflow/examples/rga/datalog_agg.rs, hydroflow/tests/compile-fail/datalog_join_badtypes.stderr, hydroflow/tests/compile-fail/surface_demuxenum_notenum.stderr, hydroflow/tests/compile-fail/surface_identity_wronggeneric.stderr, hydroflow/tests/compile-fail/surface_join_badtypes.stderr, hydroflow/tests/compile-fail/surface_merge_badtypes.stderr, hydroflow/tests/compile-fail/surface_source_iter_badtype.stderr, hydroflow_lang/src/graph/flat_graph_builder.rs, hydroflow_lang/src/graph/hydroflow_graph.rs, hydroflow_lang/src/graph/ops/sort.rs, hydroflow_lang/src/graph/ops/source_iter.rs, hydroflow_plus_test/src/networked.rs, rust-toolchain.toml, stageleft_test/src/submodule.rs
TODO: update tests - investigate why a couple compile-fail tests are making massive error messages.
=> Bump pinned rust version, update lints, tests, etc

hydro_deploy/core/src/localhost/launched_binary.rs, hydro_deploy/core/src/localhost/mod.rs
fix(hydro_deploy): end processes with SIGTERM instead of SIGKILL
=> fix(hydro_deploy): end processes with SIGTERM instead of SIGKILL

hydroflow/src/scheduled/graph.rs, hydroflow/tests/scheduled_teeing_handoff.rs
=> fix(hydroflow): fix `TeeingHandoff` not scheduling outputs `tee()`d after send port is already used via `add_subgraph*`, fix #1163

hydroflow/src/lib.rs, hydroflow/src/scheduled/reactor.rs, hydroflow_datalog_core/build.rs, hydroflow_lang/build.rs, stageleft_tool/src/lib.rs, website_playground/build.rs
See https://doc.rust-lang.org/nightly/cargo/reference/build-scripts.html#rustc-check-cfg
=> chore: expect custom config names to prevent warnings

hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs, hydro_deploy/hydroflow_plus_cli_integration/src/lib.rs, hydro_deploy/hydroflow_plus_cli_integration/src/runtime.rs, hydroflow_plus/src/location/graphs.rs, hydroflow_plus/src/location/mod.rs, hydroflow_plus_test/src/cluster.rs, hydroflow_plus_test/src/snapshots/hydroflow_plus_test__cluster__tests__simple_cluster.snap
feat(hydroflow_plus): add API to get the cluster ID of the current node
=> feat(hydroflow_plus): add API to get the cluster ID of the current node

hydroflow/tests/compile-fail/surface_singleton_nostate.rs, hydroflow/tests/compile-fail/surface_singleton_nostate.stderr, hydroflow/tests/compile-fail/surface_singleton_nostate_undefined.rs, hydroflow/tests/compile-fail/surface_singleton_nostate_undefined.stderr, hydroflow/tests/compile-fail/surface_singleton_undefined.rs, hydroflow/tests/compile-fail/surface_singleton_undefined.stderr, hydroflow/tests/compile-fail/surface_singleton_undefined_nostate.rs, hydroflow/tests/compile-fail/surface_singleton_undefined_nostate.stderr, hydroflow/tests/snapshots/surface_singleton__fold_cross@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__fold_cross@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_singleton__fold_singleton@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__fold_singleton@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_singleton__fold_singleton_push@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__fold_singleton_push@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_singleton__reduce_singleton@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__reduce_singleton@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_singleton__reduce_singleton_push@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__reduce_singleton_push@graphvis_mermaid.snap, hydroflow/tests/snapshots/surface_singleton__state@graphvis_dot.snap, hydroflow/tests/snapshots/surface_singleton__state@graphvis_mermaid.snap, hydroflow/tests/surface_singleton.rs, hydroflow_lang/src/graph/flat_graph_builder.rs, hydroflow_lang/src/graph/hydroflow_graph.rs
=> feat(hydroflow_lang): insert `persist()` before singleton referencers to enable replay

CONTRIBUTING.md, precheck.bash, website_playground/README.md
=> docs: Add CONTRIBUTING.md, fix #1118

lattices/src/lib.rs
Address https://github.com/hydro-project/hydroflow/issues/1229.
=> feat(lattices): Expose PairBimorphism public.

.github/workflows/build-cli.yml, .github/workflows/ci.yml, .github/workflows/conventional_commits.yml, .github/workflows/examples-container.yml, Cargo.lock, Cargo.toml, datastores/gossip_kv/Cargo.toml, datastores/gossip_kv/README.md, datastores/gossip_kv/examples/server/Dockerfile, datastores/gossip_kv/examples/server/README.md, datastores/gossip_kv/examples/server/baseimage.Dockerfile, datastores/gossip_kv/examples/server/deployment/local/deployment.yaml, datastores/gossip_kv/examples/server/deployment/local/service.yaml, datastores/gossip_kv/examples/server/deployment/patch.yaml, datastores/gossip_kv/examples/server/main.rs, datastores/gossip_kv/src/lib.rs
Included in this commit:
* Elementary kubernetes YAMLs
* Instructions in `README.md` to install, build images and deploy to minikube
* Overall `README.md` (extremely rough draft) of the architecture of the system
=> feat(anna_v2): Setup basic project directory structure

.github/workflows/build-cli.yml, .github/workflows/ci.yml, .github/workflows/examples-container.yml, CONTRIBUTING.md, hydroflow/tests/snapshots/surface_lattice_bimorphism__join@graphvis_dot.snap, hydroflow/tests/snapshots/surface_lattice_bimorphism__join@graphvis_mermaid.snap, hydroflow/tests/surface_lattice_bimorphism.rs, lattices/src/map_union.rs
Also updating GitHub workflows to run on feature branches as well.
=> docs: Updating CONTRIBUTING.md with some info about feature branches

variadics/src/lib.rs
This adds a way to convert a reference to a variadic into a variadic of references. I.e. `&var_expr!(a, b, c) -> var_expr!(&a, &b, &c)`
=> feat(variadics): add traits for referencing variadics

Cargo.lock, datastores/gossip_kv/Cargo.toml, datastores/gossip_kv/cli/main.rs, datastores/gossip_kv/protocol/lib.rs, datastores/gossip_kv/server/main.rs, datastores/gossip_kv/server/model.rs, hydroflow_lang/src/graph/ops/state.rs
With this change, the water flows through the pipes, with Gets, Sets & Deletes primarily working. Some minor issues remain, but I'll do those separately.
Next steps:
https://github.com/hydro-project/hydroflow/issues/1253
https://github.com/hydro-project/hydroflow/issues/1257
https://github.com/hydro-project/hydroflow/issues/1256
https://github.com/hydro-project/hydroflow/issues/1255
https://github.com/hydro-project/hydroflow/issues/1254
=> feat(anna): Added a working CLI

datastores/gossip_kv/protocol/lib.rs
It was not the most critical thing to get in, but it bothered me a bit. This code change allows '/' to be used in table and row names. This doesn't affect memory layout in any way.
The most critical part of this change is the additional tests to check for empty table names and row keys.
=> feat(anna): Escaping of keys

hydroflow_lang/src/graph/ops/dest_sink.rs
=> docs(hydroflow_lang): fix `dest_sink` tokio links

hydroflow/src/scheduled/graph.rs
=> fix(hydroflow): make sure tasks are spawned!!!!

.idea/hydroflow.iml
=> chore(hydroflow): Checkin RustRover IDE files.

Cargo.lock, datastores/gossip_kv/Cargo.toml, datastores/gossip_kv/cli/main.rs, datastores/gossip_kv/protocol/membership.rs, datastores/gossip_kv/server/.gitignore, datastores/gossip_kv/server/config/default.toml, datastores/gossip_kv/server/config/mod.rs, datastores/gossip_kv/server/main.rs, datastores/gossip_kv/server/membership.rs, datastores/gossip_kv/server/server.rs
* Added support for hierarchical configuration using `config` crate & used it to set seed node information
* Some cleanup for types & interfaces
=> feat(anna): Adding configurable seed nodes.

precheck.bash
small change, so we get exit code 0 on success
=> refactor: rearrange `precheck.bash` conditions for exit code 0

benches/README.md, hydroflow/src/scheduled/context.rs, hydroflow/src/scheduled/graph.rs, hydroflow/tests/snapshots/surface_lattice_bimorphism__cartesian_product_tick_state@graphvis_dot.snap, hydroflow/tests/snapshots/surface_lattice_bimorphism__cartesian_product_tick_state@graphvis_mermaid.snap, hydroflow/tests/surface_lattice_bimorphism.rs, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__anti_join@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__collect_vec@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__index@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__join_with_other@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__join_with_self@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__single_column_program@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__transitive_closure@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__triple_relation_join@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_fields@datalog_program.snap, hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_join_count@datalog_program.snap, hydroflow_lang/src/graph/ops/anti_join.rs, hydroflow_lang/src/graph/ops/anti_join_multiset.rs, hydroflow_lang/src/graph/ops/enumerate.rs, hydroflow_lang/src/graph/ops/fold.rs, hydroflow_lang/src/graph/ops/fold_keyed.rs, hydroflow_lang/src/graph/ops/join.rs, hydroflow_lang/src/graph/ops/multiset_delta.rs, hydroflow_lang/src/graph/ops/persist.rs, hydroflow_lang/src/graph/ops/persist_mut.rs, hydroflow_lang/src/graph/ops/persist_mut_keyed.rs, hydroflow_lang/src/graph/ops/reduce.rs, hydroflow_lang/src/graph/ops/reduce_keyed.rs, hydroflow_lang/src/graph/ops/state.rs
=> fix(hydroflow): add `add_state_tick` to state API, reset at end of each tick, fix #1298

hydroflow/tests/compile-fail/surface_singleton_badexpr.rs, hydroflow/tests/compile-fail/surface_singleton_badexpr.stderr, hydroflow/tests/compile-fail/surface_singleton_nostate.stderr, hydroflow/tests/compile-fail/surface_singleton_nostate_undefined.stderr, hydroflow/tests/compile-fail/surface_singleton_undefined.stderr, hydroflow/tests/compile-fail/surface_singleton_undefined_nostate.stderr, hydroflow_lang/src/graph/hydroflow_graph.rs, hydroflow_lang/src/graph/mod.rs, hydroflow_lang/src/process_singletons.rs
Another small spanning improvement
=> fix(hydroflow_lang): improve spanning of singleton substitution code, add compile-fail test, fix #1294

docs/docusaurus.config.js
Hello, Andre here from RunLLM.
This pull request updates your RunLLM widget to use our new widget URL. 
Once merged, you will be able to stay up to date with our widget's changes and get all the latest AI assistant goodies.
=> chore: Update RunLLM Configuration

.github/workflows/build-cli.yml
fix(hydro_deploy): link with system linker for macOS wheels
LLD doesn't support the options we need yet
=> fix(hydro_deploy): link with system linker for macOS wheels

hydro_deploy/core/src/localhost/launched_binary.rs, hydro_deploy/core/src/localhost/mod.rs, hydro_deploy/core/src/progress.rs, hydro_deploy/core/src/ssh.rs, hydro_deploy/core/src/terraform.rs
A small refactor pulled out of the perf tracing work, barely related to #1359
=> refactor(hydro_deploy): adjust `ProgressTracker::println`

hydroflow/src/util/mod.rs, hydroflow/src/util/simulation.rs
Will move it out of the blind gossip PR next.
=> feat(hydroflow): Added simulation framework.

hydroflow_plus_test/examples/paxos.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1419).
* #1418
* #1417
* __->__ #1419
=> fix(hydroflow_plus): merge issue in paxos

Cargo.lock, hydro_deploy/hydro_cli_examples/Cargo.toml, hydroflow/Cargo.toml, hydroflow_datalog_core/Cargo.toml, hydroflow_lang/Cargo.toml, topolotree/Cargo.toml
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1417).
* #1418
* __->__ #1417
=> chore: drop unused dependencies

hydroflow_plus/src/builder/mod.rs, hydroflow_plus/src/cycle.rs, hydroflow_plus/src/ir.rs, hydroflow_plus/src/persist_pullup.rs, hydroflow_plus/src/singleton.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/cluster/paxos.rs, hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos__tests__paxos_ir.snap, hydroflow_plus_test_local/src/local/graph_reachability.rs, hydroflow_plus_test_local/src/local/snapshots/hydroflow_plus_test_local__local__graph_reachability__tests__reachability@graphvis_dot.snap, hydroflow_plus_test_local/src/local/snapshots/hydroflow_plus_test_local__local__graph_reachability__tests__reachability@graphvis_mermaid.snap
Towards making it more clear which parts of a program depend on ticks versus don't.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1441).
* #1445
* #1443
* __->__ #1441
=> feat(hydroflow_plus)!: provide an API for creating cycles across tick iterations

hydroflow_plus_test/src/cluster/paxos.rs, hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos__tests__paxos_ir.snap, stageleft_macro/src/quote_impl/free_variable/mod.rs
=> fix(stageleft): support tuple patterns

Cargo.lock, datastores/gossip_kv/Cargo.toml, datastores/gossip_kv/Makefile, datastores/gossip_kv/server/deployment/aws/terraform/main.tf, datastores/gossip_kv/server/deployment/aws/terraform/outputs.tf, datastores/gossip_kv/server/deployment/aws/terraform/variables.tf, datastores/gossip_kv/server/main.rs, datastores/gossip_kv/server/server.rs
=> feat(anna): Grafana and Prometheus working and talking to each other

hydroflow/src/compiled/pull/anti_join.rs, hydroflow/src/compiled/pull/cross_join.rs, hydroflow/src/compiled/pull/symmetric_hash_join.rs, hydroflow/src/scheduled/graph.rs, hydroflow/src/scheduled/graph_ext.rs, hydroflow/src/scheduled/net/mod.rs, hydroflow/src/util/simulation.rs, hydroflow_lang/src/graph/ops/anti_join_multiset.rs, hydroflow_plus/src/builder/built.rs, hydroflow_plus/src/builder/mod.rs, hydroflow_plus/src/deploy/deploy_graph.rs, hydroflow_plus/src/deploy/in_memory_graph.rs, hydroflow_plus/src/deploy/macro_runtime.rs, hydroflow_plus/src/lib.rs, hydroflow_plus/src/location.rs, lattices/src/collections.rs, lattices/src/test.rs, lattices/src/vec_union.rs, stageleft/src/lib.rs, variadics/src/lib.rs, variadics/tests/boxed_refed.rs
a couple few spurious `too_many_arguments` and a spurious `zombie_processes` still on current nightly (`clippy 0.1.84 (4392847410 2024-10-21)`)
=> style: fixes for nightly clippy

hydroflow_plus/src/singleton.rs, hydroflow_plus_test/src/cluster/paxos.rs, hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1485).
* #1493
* #1492
* #1489
* #1488
* #1487
* #1486
* __->__ #1485
=> refactor(paxos): start splitting out leader election into a separate module

hydroflow_plus/src/cycle.rs, hydroflow_plus/src/lib.rs, hydroflow_plus/src/location.rs, hydroflow_plus/src/singleton.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/cluster/paxos.rs, hydroflow_plus_test/src/cluster/paxos_bench.rs, hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap, hydroflow_plus_test_local/src/local/graph_reachability.rs, stageleft_tool/src/lib.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1486).
* #1514
* #1493
* #1492
* #1489
* #1488
* #1487
* __->__ #1486
=> refactor(paxos): complete split into leader election and sequencing phases

hydroflow_plus_test/src/cluster/paxos.rs, hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1487).
* #1514
* #1493
* #1492
* #1489
* #1488
* __->__ #1487
=> refactor(paxos): rearrange code to reflect order of phases

hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/cluster/paxos_bench.rs, hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1515).
* #1517
* #1516
* __->__ #1515
=> refactor(paxos_bench): simplify latency calculations

hydroflow_plus/src/location.rs, hydroflow_plus_test/src/cluster/mod.rs, hydroflow_plus_test/src/cluster/paxos.rs, hydroflow_plus_test/src/cluster/paxos_bench.rs, hydroflow_plus_test/src/cluster/paxos_kv.rs, hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1516).
* #1517
* __->__ #1516
=> refactor(hydroflow_plus, paxos)!: simplify intervals and split Paxos-KV into separate module

hydroflow_plus/src/lib.rs, hydroflow_plus/src/location.rs, hydroflow_plus/src/singleton.rs, hydroflow_plus/src/stream.rs, hydroflow_plus_test/src/cluster/paxos.rs, hydroflow_plus_test/src/cluster/paxos_kv.rs, hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1521).
* #1527
* #1526
* #1525
* #1524
* #1523
* __->__ #1521
=> refactor(paxos): use `usize` for slot numbers

hydroflow_plus/src/lib.rs, hydroflow_plus/src/location/cluster.rs, hydroflow_plus/src/location/mod.rs, hydroflow_plus/src/stream.rs, stageleft_tool/src/lib.rs
=> fix(stageleft): properly handle `crate::` imports

.idea/hydroflow.iml, datastores/gossip_kv/server/main.rs
=> feat(Gossip KV): Cleanup code duplication in main.rs

datastores/gossip_kv/README.md
=> chore(Gossip KV): Update main README.md

docs/docs/hydroflow_plus/index.mdx
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1552).
* #1553
* __->__ #1552
=> fix(docs): add a note saying that HF+ docs are WIP

datastores/gossip_kv/Cargo.toml, datastores/gossip_kv/server/main.rs, datastores/gossip_kv/server/membership.rs
=> feat(Gossip KV): Make member random suffix length configurable.

docs/docs/hydroflow/quickstart/example_1_simplest.mdx, docs/src/util.ts, hydroflow/examples/example_1_simplest.rs
Fix #1320 suggested in https://github.com/hydro-project/hydroflow/pull/1318#pullrequestreview-2137476550
=> docs: `getLines` support named section markers, fix #1320

Cargo.lock, dfir_rs/tests/surface_examples.rs, hydro_deploy/core/src/deployment.rs, hydro_deploy/core/src/hydroflow_crate/tracing_options.rs, multiplatform_test/src/lib.rs, stageleft/src/lib.rs, stageleft_tool/src/lib.rs
Testing in https://github.com/MingweiSamuel/hydroflow
https://github.com/MingweiSamuel/hydroflow/actions/runs/12777967961/job/35619880542
=> style: fix all unexpected cfgs

.github/workflows/ci.yml, benches/benches/words_diamond.rs
=> ci(benches): fix benchmarking of hydroflow->dfir_rs [ci-bench]

.github/workflows/build-cli.yml
=> ci(hydro_cli): fix matrix clobbering the same artifact path

hydro_lang/src/builder/built.rs, hydro_lang/src/builder/deploy.rs, hydro_lang/src/builder/mod.rs, hydro_lang/src/deploy/in_memory_graph.rs, hydro_lang/src/deploy/mod.rs, hydro_lang/src/ir.rs, hydro_lang/src/test_util.rs
This makes it easy to implement patterns like deploying everything to localhost.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/1676).
* #1677
* #1678
* __->__ #1676
=> feat(hydro_lang): provide APIs for blanket-deploying locations

docs/src/pages/people.js
in recognition of sustained excellence
=> docs: change Mingwei's title

dfir_lang/src/graph/meta_graph.rs, dfir_lang/src/graph/ops/dest_sink.rs, dfir_lang/src/graph/ops/mod.rs
So we can see CPU usage from sending messages in perf
=> feat(dfir_lang): Print dest_sink sink_feed_flush with tag

Cargo.lock, hydro_test/Cargo.toml, hydro_test/src/cluster/bench_client.rs, hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
Much more meaningful than just median + mean.
=> feat(hydro_test): emit confidence intervals for benchmark metrics

hydro_lang/src/cycle.rs, hydro_lang/src/location/mod.rs, hydro_lang/src/location/tick.rs
=> fix(hydro_lang)!: raise a panic if a user forgets to complete a cycle

lattices/src/algebra.rs
after upgrading to edition 2024
=> style: fix small format issue

hydro_deploy/core/src/hydroflow_crate/build.rs
From debugging today
Main useful one is the STDERR output
Uses more memory
=> refactor(hydro_deploy): show a lot more error info on build failure

hydro_deploy/core/src/progress.rs, hydro_deploy/core/src/ssh.rs, hydro_deploy/core/src/terraform.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/1777).
* #1778
* __->__ #1777
=> feat(hydro_deploy): copy down remote perf raw data and shift Terraform logs to stderr

hydro_lang/src/ir.rs, hydro_lang/src/location/external_process.rs, hydro_lang/src/location/mod.rs, hydro_lang/src/rewrites/decoupler.rs, hydro_lang/src/stream.rs
=> fix(hydro_lang): decrease size of IR enums to prevent stack overflow on windows, fix #1801

hydro_lang/src/deploy/trybuild.rs
Previously, if launching code from `hydro_test`, we would fail to resolve relative paths originating inside `hydro_test` code, since the `__staged` module in the trybuild is empty (unless in test mode, which is why we missed this). Now, when we are not in test mode, we set up the trybuild `__staged` to redirect to the `__staged` of the crate the trybuild is being generated for, so that the correct path is resolved.
=> fix(hydro_lang): correctly resolve `__staged` paths for the crate being launched

.github/workflows/build-cli.yml
Handles Linux, Windows seems to be a different issue.
=> fix(hydro_cli): fix cross-compilation to Linux aarch64

Cargo.lock, hydro_test/Cargo.toml, hydro_test/examples/chat.rs, hydro_test/examples/echo_server.rs, hydro_test/src/cluster/chat.rs, hydro_test/src/cluster/echo_server.rs, hydro_test/src/cluster/mod.rs
These are so simple and similar it merits a nice walk-through discussion in the docs.
=> feat(hydro): chat and echo examples

dfir_lang/src/graph/ops/zip.rs, dfir_rs/src/scheduled/graph.rs, dfir_rs/tests/surface_zip_unzip.rs
=> fix(dfir_lang,dfir_rs): fix loop hooks triggered too often, implement lifetimes for `zip`

.vscode/extensions.json, Cargo.lock, Cargo.toml, dfir_rs/Cargo.toml, dfir_rs/examples/chat/main.rs, dfir_rs/examples/deadlock_detector/main.rs, dfir_rs/examples/echo_serde_json/main.rs, dfir_rs/examples/echo_server/main.rs, dfir_rs/examples/kvs/main.rs, dfir_rs/examples/kvs_bench/main.rs, dfir_rs/examples/kvs_mut/main.rs, dfir_rs/examples/kvs_replicated/main.rs, dfir_rs/examples/lamport_clock/main.rs, dfir_rs/examples/rga/main.rs, dfir_rs/examples/shopping/main.rs, dfir_rs/examples/three_clique/main.rs, dfir_rs/examples/two_pc_hf/main.rs, dfir_rs/examples/vector_clock/main.rs, dfir_rs/src/util/mod.rs, example_test/Cargo.toml, example_test/src/lib.rs, hydro_test/Cargo.toml, hydro_test/examples/first_ten_distributed.rs
To prep for testing of hydro_deploy #1374 #1810
=> refactor(dfir_rs): move example testing code into separate crate

Cargo.lock, dfir_rs/examples/chat/main.rs, dfir_rs/examples/deadlock_detector/main.rs, dfir_rs/examples/echo_serde_json/main.rs, dfir_rs/examples/echo_server/main.rs, dfir_rs/examples/kvs/main.rs, dfir_rs/examples/kvs_bench/main.rs, dfir_rs/examples/kvs_mut/main.rs, dfir_rs/examples/kvs_replicated/main.rs, dfir_rs/examples/lamport_clock/main.rs, dfir_rs/examples/rga/main.rs, dfir_rs/examples/shopping/main.rs, dfir_rs/examples/three_clique/main.rs, dfir_rs/examples/two_pc_hf/main.rs, dfir_rs/examples/vector_clock/main.rs, example_test/src/lib.rs, hydro_test/Cargo.toml, hydro_test/examples/compute_pi.rs, hydro_test/examples/first_ten_distributed.rs, hydro_test/examples/map_reduce.rs
Fix #1374
Not a breaking change as the `example_test` crate is not yet released
=> test(hydro_deploy): test some hydro examples on localhost, fix #1374

hydro_lang/src/builder/mod.rs, hydro_lang/src/location/mod.rs, hydro_lang/src/location/tick.rs, hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
=> feat(hydro_lang): Assign cycles IDs that are globally unique (across clusters/processes)

hydro_test/examples/two_pc.rs, hydro_test/src/cluster/mod.rs, hydro_test/src/cluster/paxos_bench.rs, hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir@acceptor_mermaid.snap, hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_ir.snap, hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_ir@coordinator_mermaid.snap, hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_ir@participants_mermaid.snap, hydro_test/src/cluster/two_pc.rs, hydro_test/src/cluster/two_pc_bench.rs
Does not log to disk yet, would need #1922
=> feat(hydro_test): Connect 2PC implementation to bench_client

hydro_lang/src/ir.rs, hydro_lang/src/stream.rs, hydro_optimize/src/deploy_and_analyze.rs, hydro_optimize/src/lib.rs
=> feat(hydro_lang): add `scan` operator

hydro_deploy/core/src/rust_crate/service.rs
Has not been used for a long while...
=> refactor(hydro_deploy)!: remove deprecated `add_connection` API

hydro_deploy/hydro_deploy_integration/src/multi_connection.rs, hydro_lang/src/deploy/deploy_graph.rs, hydro_lang/src/location/mod.rs, hydro_test/examples/echo.rs, hydro_test/examples/http_hello.rs, hydro_test/src/external_client/echo.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/1981).
* #1983
* #1982
* __->__ #1981
=> feat(hydro_lang)!: expose a stream of membership events for bidi externals

hydro_lang/src/ir.rs, hydro_lang/src/location/mod.rs, hydro_optimize/src/debug.rs, hydro_optimize/src/decouple_analysis.rs, hydro_optimize/src/decoupler.rs, hydro_optimize/src/parse_results.rs, hydro_optimize/src/partition_node_analysis.rs, hydro_optimize/src/partition_syn_analysis.rs, hydro_optimize/src/partitioner.rs, hydro_optimize/src/repair.rs, hydro_optimize/src/rewrites.rs
Also cleans up some remaining references to "leaf".
=> refactor(hydro_lang): share `HydroIrOpMetadata` between roots and nodes

.github/workflows/ci.yml
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
=> ci: use Hydro bot to trigger CI for generated PRs

hydro_lang/src/live_collections/optional.rs, hydro_lang/src/live_collections/singleton.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/2112).
* #2117
* #2116
* #2115
* #2114
* __->__ #2112
=> docs(hydro_lang): `Singleton::zip` and `Optional::zip`

hydro_lang/src/live_collections/stream/mod.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/2126).
* #2136
* #2129
* #2127
* __->__ #2126
=> fix(hydro_lang): ensure that `Stream::scan` actually remembers state with unbounded input

hydro_lang/src/live_collections/boundedness.rs, hydro_lang/src/live_collections/keyed_singleton.rs, hydro_lang/src/live_collections/keyed_stream/mod.rs, hydro_lang/src/live_collections/optional.rs, hydro_lang/src/live_collections/singleton.rs, hydro_lang/src/live_collections/stream/mod.rs
=> refactor(hydro_lang): Convert traits `fn prop_kind() -> PropKind` to associated `const`
