hydro-project/hydro

- Cargo.lock
- covid_tracing/Cargo.toml
- covid_tracing/src/main.rs
- covid_tracing/src/people.rs
This commit extends the Covid tracing demo to run in real-time. Includes a
bunch of randomly generated data to give it some texture.
> Extend Covid tracing demo

- hydroflow/src/scheduled/input.rs
- hydroflow/src/scheduled/mod.rs
This also does some minor optimization to make it less expensive to constantly
schedule the same operator. Only did a thread-local version for now, just to
try to get it working, I think it's easy to extend to a version that can be
cross-thread from here.
> Introduce an "Input" for ingressing data

- hydroflow/src/scheduled/mod.rs
- hydroflow/src/scheduled/query.rs
- hydroflow/src/scheduled/subgraph.rs
Also removes a few more unneccesary `&mut`s
less code is better code
> Replace concrete Subgraph types with FnMut()

- Cargo.lock
- Cargo.toml
- relalg/Cargo.toml
- relalg/src/lib.rs
- relalg/src/runtime.rs
- relalg/src/sexp.rs
- relalg/testdata/build/rel
- relalg/testdata/run/run
This is a WIP implementation of relational algebra that runs in Hydroflow.
Right now it only uses scheduled components and is only at runtime, no codegen,
just for simplicity. It's also not how I would design a non-proof-of-concept IR
but I think for our purposes for now it will be fine.
The sexp parser is one I had from another unpublished project that I just copy-pasted in here. I didn't love any of the libraries I tried and I already had this one written, so I just vendored it.
> Add a basic implementation of relational algebra

- .github/workflows/ci.yml
- Cargo.lock
- relalg/Cargo.toml
- relalg/src/codegen.rs
- relalg/src/lib.rs
- relalg/src/main.rs
- relalg/testdata/compile/compile
This currently only handles some very simple patterns, and doesn't invoke
scheduled components at all, but this is the general pattern I was thinking for
now. Comments on the overall design welcome, you can see examples of the
generated code in testdata/compile/compile.
What's more, I think this PR will probably fail on CI since it shells out to
rustfmt to format the generated code. Suggestions welcome for how to fix, I
might just make it skip running the test (probably with a warning) if rustfmt
does not just work.
Next step is to introduce a let binding layer to the language, to force the
codegen to use scheduled components/invoke Hydroflow.
I'll add some docs for this, but if you want to regenerate the output for the tests you can run
```
env REWRITE=1 cargo test -p relalg
```
to …
> Add a simple codegen path for relational algebra

- hydroflow/src/scheduled/net/network_vertex.rs
- hydroflow/tests/networked.rs
This version only uses data-based addresses, which means we pass around a lot
of heap-allocated data. Needs some more iteration to be ergonomic.
Some stuff I haven't figured out yet about how to handle some of the async stuff within operators, but it's functional right now if not super stable.
Also removed the star test for now.
> Iterate on TCP connections

- Cargo.lock
- hydroflow/Cargo.toml
- hydroflow/src/scheduled/net/mod.rs
- hydroflow/src/scheduled/net/network_vertex.rs
- hydroflow/tests/networked.rs
This commit tidies up the TCP stuff more. There's still more to be done in
terms of ergonomics but I want to wait for the API change to work on that. I
think the next steps are that, and also writing a benchmark against a
hand-coded server, since I think there's a lot of low-hanging fruit in terms of
stuff like buffer reuse.
> Switch from a bespoke format -> bincode

- hydroflow/src/builder/hydroflow_builder.rs
- hydroflow/src/scheduled/net/network_vertex.rs
- hydroflow/tests/networked.rs
Sort of minimal use of it so far since the logic here is pretty simple, but
should provide a foundation for things like address interning.
Wasn't sure if the wrap_{input,output} stuff aligns with your vision? LMK if
there's a cleaner/existing way to do that?
> Rewrite echo server using the surface API

- covid_tracing_dist/src/tracker.rs
- hydroflow/src/scheduled/net/mod.rs
This commit fixes two problems:
* There was an inconsistency with how the address was expected, and
* the endianness of the sender was changed, and was not changed for the receiver.
> Get the distributed covid app running again

- hydroflow/Cargo.toml
Lacking this was causing `cargo test -p` to fail, even though `cargo test`
succeeded, since running the full `cargo test` would take the union of feature
flags across the workspace, even for individual packages.
> Enable the derive feature on hydroflow's serde

- hydroflow/src/builder/build/mod.rs
- hydroflow/src/builder/build/pull_chain.rs
- hydroflow/src/builder/build/pull_cross_join.rs
- hydroflow/src/builder/build/pull_filter.rs
- hydroflow/src/builder/build/pull_filter_map.rs
- hydroflow/src/builder/build/pull_flatten.rs
- hydroflow/src/builder/build/pull_handoff.rs
- hydroflow/src/builder/build/pull_iter.rs
- hydroflow/src/builder/build/pull_join.rs
- hydroflow/src/builder/build/pull_map.rs
- hydroflow/src/builder/build/push_filter.rs
- hydroflow/src/builder/build/push_filter_map.rs
- hydroflow/src/builder/build/push_flatten.rs
- hydroflow/src/builder/build/push_for_each.rs
- hydroflow/src/builder/build/push_handoff.rs
- hydroflow/src/builder/build/push_map.rs
- hydroflow/src/builder/build/push_partition.rs
- hydroflow/src/builder/build/push_tee.rs
- hydroflow/src/builder/surface/mod.rs
- hydroflow/src/builder/surface/pull_chain.rs
- hydroflow/src/builder/surface/pull_cross_join.rs
- hydroflow/src/builder/surface/pull_join.rs
- hydroflow/src/builder/surface/push_partition.rs
- hydroflow/src/builder/surface/push_tee.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/src/scheduled/handoff/handoff_list.rs
- hydroflow/src/scheduled/handoff/mod.rs
- hydroflow/src/scheduled/port.rs
In the big refactor I used true/false const generics to differentiate between send/recv ports. This switches to use more descriptive tag types (same setup as the tag types in the lattice types).
> Use SEND/RECV type tags instead of true/false const generics for `Port`s/`PortCtx`s

- hydroflow/src/builder/build/mod.rs
- hydroflow/src/builder/build/pull_chain.rs
- hydroflow/src/builder/build/pull_cross_join.rs
- hydroflow/src/builder/build/pull_filter.rs
- hydroflow/src/builder/build/pull_filter_map.rs
- hydroflow/src/builder/build/pull_flatten.rs
- hydroflow/src/builder/build/pull_handoff.rs
- hydroflow/src/builder/build/pull_iter.rs
- hydroflow/src/builder/build/pull_join.rs
- hydroflow/src/builder/build/pull_map.rs
- hydroflow/src/builder/build/push_filter.rs
- hydroflow/src/builder/build/push_filter_map.rs
- hydroflow/src/builder/build/push_flatten.rs
- hydroflow/src/builder/build/push_for_each.rs
- hydroflow/src/builder/build/push_handoff.rs
- hydroflow/src/builder/build/push_map.rs
- hydroflow/src/builder/build/push_partition.rs
- hydroflow/src/builder/build/push_tee.rs
- hydroflow/src/builder/hydroflow_builder.rs
This will be needed once more features are added to context.
We also have the option to remove the wonky handoff list structure via
this.
> Add context to surface build

- hydroflow/src/builder/build/mod.rs
- hydroflow/src/builder/build/pull_batch.rs
- hydroflow/src/builder/surface/mod.rs
- hydroflow/src/builder/surface/pull_batch.rs
- hydroflow/src/compiled/pull.rs
- hydroflow/src/scheduled/mod.rs
This commit introduces a "batching" operator, that buffers up data on one side until provoked to flush by the other side. I think the most common mode for this will be using unit as the key, but you can also partition up the batches by key and flush them independently.
> Batch join

- .github/workflows/ci.yml
- rust-toolchain.toml
This reverts commit 92b4cfb043c6789497f74d429d7f3fa045d87355.
Rust nightly fixed by https://github.com/rust-lang/rust/pull/93892#event-6104854781
> Revert "Temporarily pin toolchain to nightly-2022-02-09" due to nightly fixes

- hydroflow/src/scheduled/context.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/src/scheduled/reactor.rs
This replaces the std mpsc event channels with tokio unbounded channels
so we can .await them.
Fixes #87
> Fix hf.run_async() busy spinning.

- Cargo.lock
- hydroflow/src/builder/build/mod.rs
- hydroflow/src/builder/build/pull_half_hash_join.rs
- hydroflow/src/builder/surface/mod.rs
- hydroflow/src/builder/surface/pull_half_hash_join.rs
- hydroflow/src/compiled/pull.rs
- kvs/Cargo.toml
- kvs/src/main.rs
This is a first pass at a dataflow based KVS. It is missing a bunch of clock
stuff, but I was getting anxious about not merging this so here's an early
version of it.
The structure of the program is roughly as follows:
```mermaid
graph BT
Y[Read Requests] --> Z[Streaming Join]
X[Received Batches] --> Z
Z --> Q[Respond to Read Request]
F[Write Requests] --> B
A[Epoch Timer] --> B[Batcher / Merger]
B --> C[Join]
G[Ownership] --> C
C --> E[Network Shuffle]
```
> Rewrite KVS in dataflow

- hydroflow/src/builder/surface/mod.rs
- hydroflow/tests/groupby.rs
Add ad-hoc core groupby test
Add scan to surface API
- Also add groupby_surface_monotonic test
For now the `scan` API provides little benefit over just using a manual
`move` closure, but in the future we can integrate it with the State API
as well as with lattice types.
> Add groupby tests/examples

- hydroflow/src/lang/lattice/dom_pair.rs
- hydroflow/src/lang/lattice/map_union.rs
The Compare implementations for DomPair and MapUnion were incorrect.  I'd like
to add some tests around this but I think maybe there's something more holistic
to be done here, given all the algebraic properties we have of lattices this
seems like it should be very amenable to property-based-testing.
The MapUnion implementation in particular feels very...icky. We probably want
something a bit more specialized for various tags that permit a better
implementation, like exploiting order or fast random lookups. But maybe there's
a nicer way to implement it here? Not sure, couldn't think of anything.
> Fix some Compare implementations

- hydroflow/src/builder/hydroflow_builder.rs
- hydroflow/src/scheduled/context.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/tests/groupby.rs
- Users can now optionally specify a _stratum number_ when adding a compiled subgraph, with the new `add_..._stratified()` methods. When not specified stratum number is zero.
- Scheduler will run each stratum to fixed point before continuing to the next strata (loop to beginning after final stratum)
- Scheduler keeps track of `epoch` -- number of times we've looped around strata.
- New `Hydroflow.run_stratum()` method runs only the current stratum.
- New `Hydroflow.next_stratum()` method increments to the next stratum with work available.
> Implement strata, enabling per-tick non-monotonic aggregations

- hydroflow/src/builder/build/mod.rs
- hydroflow/src/builder/build/pull_batch.rs
- hydroflow/src/builder/build/pull_chain.rs
- hydroflow/src/builder/build/pull_cross_join.rs
- hydroflow/src/builder/build/pull_filter.rs
- hydroflow/src/builder/build/pull_filter_map.rs
- hydroflow/src/builder/build/pull_flatten.rs
- hydroflow/src/builder/build/pull_half_hash_join.rs
- hydroflow/src/builder/build/pull_handoff.rs
- hydroflow/src/builder/build/pull_iter.rs
- hydroflow/src/builder/build/pull_join.rs
- hydroflow/src/builder/build/pull_map.rs
- hydroflow/src/builder/build/push_filter.rs
- hydroflow/src/builder/build/push_filter_map.rs
- hydroflow/src/builder/build/push_flatten.rs
- hydroflow/src/builder/build/push_for_each.rs
- hydroflow/src/builder/build/push_handoff.rs
- hydroflow/src/builder/build/push_map.rs
- hydroflow/src/builder/build/push_partition.rs
- hydroflow/src/builder/build/push_tee.rs
- hydroflow/src/scheduled/graph.rs
Some find-replace refactoring, prerequisite for providing surface API with `Context`
> Combine old 'hof with context under new 'ctx lifetime

- hydroflow/examples/kvs/kvs.rs
- hydroflow/examples/kvs/main.rs
Also remove the reporting of latency information for now, since it was
vulnerable to coordinated omission and is not reliable.
> kvs: pull benchmark into separate file

- hydroflow/src/scheduled/context.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/src/scheduled/handoff/handoff_list.rs
- hydroflow/src/scheduled/mod.rs
- hydroflow/src/scheduled/reactor.rs
To prevent them from being mixed up with each other.
Replaces #88
> Use newtypes for Subgraph/Handoff/State IDs

- hydroflow/examples/kvs/common.rs
- hydroflow/examples/kvs/kvs_compiled.rs
- hydroflow/examples/kvs/kvs_scheduled.rs
- hydroflow/examples/kvs/main.rs
This one doesn't use the surface API directly, and just uses the scheduled
layer. It gets about the same performance, and flame graphs for both
implementations show a lot of time spent in tokio scheduling.  I'm going to
bring back the old non-hydroflow version and see what kind of perf that gets,
for comparison.
> Add another implementation of KVS

- hydroflow/src/scheduled/graph.rs
- hydroflow/src/scheduled/subgraph.rs
For now does not affect any external API, but is a preqrequisite for
`&mut Context` in the surface API
> Provide `&mut Context` to subgraph closure, instead of just ref

- hydroflow/src/builder/build/pull_filter.rs
- hydroflow/src/builder/build/pull_filter_map.rs
- hydroflow/src/builder/build/pull_fold_epoch.rs
- hydroflow/src/builder/build/pull_map.rs
- hydroflow/src/builder/build/push_filter.rs
- hydroflow/src/builder/build/push_filter_map.rs
- hydroflow/src/builder/build/push_for_each.rs
- hydroflow/src/builder/build/push_map.rs
- hydroflow/src/builder/build/push_partition.rs
- hydroflow/src/builder/surface/map_scan.rs
- hydroflow/src/builder/surface/mod.rs
- hydroflow/src/compiled/pull/cross_join.rs
Fix #150
https://github.com/rust-lang/rust/pull/96899
> Fix build by adding trait bounds to existential types

- hydroflow/tests/surface_codegen.rs
- hydroflow_lang/src/graph/flat_to_partitioned.rs
- hydroflow_macro/src/lib.rs
```
commit 7603c5fa947f2b3c8899416b0532dcaa86e9b3a9 (HEAD -> surface-syntax-fixes, fork/surface-syntax-fixes)
Author: Mingwei Samuel <mingwei.samuel@gmail.com>
Date:   Mon Sep 26 17:47:17 2022 -0700
Surface syntax fix handling of wildcard linear chains which might cause later pull-push conflicts    
commit c256d0f965c0862062757847ba856dad8ec40c3a
Author: Mingwei Samuel <mingwei.samuel@gmail.com>
Date:   Mon Sep 26 17:29:49 2022 -0700
Add surface diamond tests
To check subgraph partitioning bug in linear chains
commit 82e3076e6724b2159d2bb535873d741d78d75c2e
Author: Mingwei Samuel <mingwei.samuel@gmail.com>
Date:   Mon Sep 26 17:28:22 2022 -0700
Enable partitioned output on hydroflow_parser!
```
> Surface syntax fixes

- hydroflow/examples/chat/client.rs
- hydroflow/examples/chat/server.rs
- hydroflow/examples/graph_reachability/main.rs
- hydroflow/examples/three_clique/main.rs
- hydroflow/examples/two_pc/coordinator.rs
- hydroflow/examples/two_pc/subordinate.rs
Seems there are two code paths. For surface syntax:
```rust
hf.serde_graph().unwrap().to_mermaid()
```
For deprecated surface API. And core API, kinda
```rust
hf.generate_mermaid()
```
ref #219
> Fix example graph printing

- hydroflow/examples/chat/README.md
- hydroflow/examples/chat/chat_driver.py
Clients can take messages in on stdin from any process, but in order to drive them autonomously we need a reliable and continuous source of input that's less spammy than commands like 'yes'. This diff adds a chat driver that spits out a random phrase every few seconds to serve as this driver.
> Add a driver for the chat example

- .dockerignore
- Cargo.toml
- Dockerfile
- scripts/build_dist_release.sh
- scripts/multiplatform-docker-build.sh
This diff implements a script for building Hydroflow's examples for multiple platforms. At the moment, it supports macOS and Linux running on arm64 and x86_64 architectures. 
Subsequent diffs will incorporate this script into the repo's CI process.
> Multiplatform example builds

- hydroflow/tests/compile-fail/surface_degenerate_null.rs
- hydroflow_lang/src/graph/ops/null.rs
In principle `null()` should be able to handle any combination of inputs and outputs, but in reality this makes it a huge edge case and causes lots of problems.... For now it is easier to limit null to [0,1] inputs and outputs (3 non-degenerate combos).
* Fixes #243
* Fixes #244
> Limit `null()` to up to one input and/or output.

- hydroflow/examples/chat/client.rs
- hydroflow/examples/chat/helpers.rs
- hydroflow/examples/chat/server.rs
In many circumstances when testing chat in a distributed setting, we won't know the right IP address to either bind or connect to in advance. This diff allows the chat client and server to bind to DNS names, which (coupled with the distributed runtime's service discovery mechanism) should make it easier for clients and servers to find each other.
> Allow the chat example to bind and connect to DNS names

- .github/workflows/examples-container.yml
- Dockerfile
- README.md
- scripts/build_dist_release.sh
This diff introduces a CI process that builds multi-platform example containers on every commit to `main`.
> CI workflow for multiplatform example container builds

- book/example_7_echo_server.md
- book/example_8_chat_server.md
- hydroflow/Cargo.toml
- hydroflow/examples/chat/main.rs
- hydroflow/examples/echo_serde_json/README.md
- hydroflow/examples/echo_serde_json/client.rs
- hydroflow/examples/echo_serde_json/helpers.rs
- hydroflow/examples/echo_serde_json/main.rs
- hydroflow/examples/echo_serde_json/protocol.rs
- hydroflow/examples/echo_serde_json/server.rs
- hydroflow/examples/kvs/main.rs
- hydroflow/examples/two_pc/main.rs
- hydroflow/src/util/mod.rs
- hydroflow_lang/src/graph/ops/dest_sink_serde.rs
- hydroflow_lang/src/graph/ops/source_stream_serde.rs
resolve #214. Since the time that issue was opened, the default is to use `udp_bytes` and a `bincode` encoder. So we switch to providing an explicit example, `echo_serde_json` that uses `udp_lines` and a JSON encoder.
> explicit serde example, resolve #214

- Cargo.lock
- benches/Cargo.toml
- benches/benches/arithmetic.rs
- benches/benches/fan_in.rs
- benches/benches/fan_out.rs
- benches/benches/identity.rs
- benches/benches/reachability.rs
fork_join example still missing, not sure how to write it in surface.
```
test arithmetic/hydroflow/compiled ...              bench:      433822 ns/iter (+/- 2914)
test arithmetic/hydroflow/compiled_no_cheating ...  bench:     4008118 ns/iter (+/- 57048)
test arithmetic/hydroflow/surface ...               bench:     3565224 ns/iter (+/- 225604)
test fan_in/hydroflow ...                           bench:   139897374 ns/iter (+/- 1018220)
test fan_in/hydroflow/surface ...                   bench:   139589814 ns/iter (+/- 1242085)
test fan_out/hydroflow/scheduled ...                bench:    90996904 ns/iter (+/- 1011161)
test fan_out/hydroflow/surface ...                  bench:     4630026 ns/iter (+/- 11125)
test identity/hydroflow ...                         bench:    43572595 ns/iter …
```
> Add surface versions of existing micro benchmarks

- Cargo.lock
- benches/Cargo.toml
- benches/benches/symmetric_hash_join.rs
- hydroflow/Cargo.toml
- hydroflow/src/compiled/pull/symmetric_hash_join.rs
1. add microbenchmark for symmetric hash join.
2. change hash function to fxhash from siphash.
3. reduce redundant hash calculations in symmetric hash join code.
changing the hash function results in perf gains like this:
```
symmetric_hash_join/no_match
time:   [204.11 µs 204.71 µs 205.65 µs]
change: [-34.654% -34.157% -33.792%] (p = 0.00 < 0.05)
symmetric_hash_join/match_keys_diff_values
time:   [513.84 µs 514.51 µs 515.30 µs]
change: [-27.268% -26.017% -25.009%] (p = 0.00 < 0.05)
symmetric_hash_join/match_keys_same_values
time:   [567.36 µs 576.55 µs 587.08 µs]
change: [-20.294% -18.403% -16.310%] (p = 0.00 < 0.05)
symmetric_hash_join/zipf_keys_low_contention_unique_values
time:   [342.10 µs 347.09 µs 353.79 µs]
change: [-39.596% -38.597% -37.407%] (p = 0.00 < 0.05) …
```
> symmetric hash join improvements

- .github/workflows/ci.yml
- rust-toolchain.toml
Also:
1. Add rustfmt and clippy to the list of toolchain components.
2. Add wasm32-unknown-unknown to the list of toolchain targets.
3. Change GitHub CI to run checks, tests, check-wasm, and lints on both
the pinned nightly release and the latest nightly release. Benchmarks
and docs run on the pinned nightly release.
Context: Currently GitHub CI uses the latest nightly release. Nightly
compilers sometimes change their compile error messages, which breaks
compile-fail tests and our CI.
Also, we recently added WASM support (https://github.com/hydro-project/hydroflow/pull/371) so adding WASM to the list
of targets means that cargo/rustup will install the WASM target
automatically.
In the future we can use renovatebot to send PRs to bump the toolchain
version automatically. …
> Pin Rust toolchain version to nightly-2023-02-01

- hydroflow/tests/datalog_frontend.rs
- hydroflow_datalog_core/src/grammar.rs
- hydroflow_datalog_core/src/join_plan.rs
- hydroflow_datalog_core/src/lib.rs
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__simple_filter@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__simple_filter@surface_graph.snap
We only support expressions between identifiers currently. In the future we will add literal support and arithmetic expression support to both the LHS and RHS of the boolean expression.
We use | to denote the start of the filtering operator because using a comma introduces ambiguity with starting another Atom.
Filtering expressions also currently do not affect codegen.
> Add filtering expressions to Dedalus rules. #178

- hydroflow/src/scheduled/context.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/src/scheduled/state.rs
- hydroflow/src/scheduled/subgraph.rs
- hydroflow/tests/surface_codegen.rs
- hydroflow/tests/surface_context.rs
Move handoffs out of the context struct to allow us to keep a separate `&mut Context` around for subgraphs to use (alongside the handoffs).
> Provide `&mut Context` alongside handoffs to subgraphs, surface syntax

- hydroflow/src/scheduled/context.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/src/scheduled/query.rs
- hydroflow/tests/surface_fold.rs
- hydroflow/tests/surface_group_by.rs
- hydroflow/tests/surface_reduce.rs
- hydroflow/tests/surface_state_scheduling.rs
- hydroflow_internalmacro/src/lib.rs
- hydroflow_lang/src/graph/ops/fold.rs
- hydroflow_lang/src/graph/ops/group_by.rs
- hydroflow_lang/src/graph/ops/reduce.rs
- hydroflow_lang/src/graph/ops/repeat_iter.rs
commit 955167119249895e3cf1eb472c57f334abfb95e6
Author: Mingwei Samuel <mingwei.samuel@gmail.com>
Date:   Wed Feb 8 11:18:31 2023 -0800
Only receive external events at the start of a tick, before stratum 0
Start for #143 #364
Supersedes #353
Related #348 #357
commit e0d243d9ab918d12d30f353372de4cab6260949d
Author: Mingwei Samuel <mingwei.samuel@gmail.com>
Date:   Wed Feb 8 11:19:49 2023 -0800
Remove unnecessary `mut` from `repeat_iter`
commit e4ef406c53d54cad9a2607b1cb89a39002ee202b
Author: Mingwei Samuel <mingwei.samuel@gmail.com>
Date:   Wed Feb 8 11:32:20 2023 -0800
`repeat_iter` now repeats via self-scheduling #143 #364
commit 95042015eb297071098ad9d220030a8cf3fc5878 (HEAD -> event-timing-2, fork/event-timing-2)
Author: Mingwei Samuel <mingwei.samuel@gmail.com>
Date:   Wed Feb 8 …
> Receive events at tick start only, implement operator self-scheduling for replay #364

- hydroflow/src/scheduled/graph.rs
- hydroflow/src/util/mod.rs
- hydroflow/tests/surface_async.rs
- hydroflow_lang/src/graph/ops/dest_sink.rs
Also adds `hydroflow::util::collect_ready_async` due to 128-batching issue with `collect_ready` while in a tokio runtime.
> Fix `run_async()` not yielding with replay (stateful) operators

- hydroflow/examples/rga/datalog_agg.rs
- hydroflow/tests/compile-fail/surface_demux_port_elided.stderr
- hydroflow/tests/compile-fail/surface_port_join.stderr
- hydroflow/tests/compile-fail/surface_port_naked_overwrite_knot_a.rs
- hydroflow/tests/compile-fail/surface_port_naked_overwrite_knot_a.stderr
- hydroflow/tests/compile-fail/surface_port_naked_overwrite_knot_b_inn.rs
- hydroflow/tests/compile-fail/surface_port_naked_overwrite_knot_b_inn.stderr
- hydroflow/tests/compile-fail/surface_port_naked_overwrite_knot_b_out.rs
- hydroflow/tests/compile-fail/surface_port_naked_overwrite_knot_b_out.stderr
- hydroflow/tests/compile-fail/surface_port_naked_overwrite_simple.rs
- hydroflow/tests/compile-fail/surface_port_naked_overwrite_simple.stderr
- hydroflow/tests/surface_parser.rs
- hydroflow_datalog_core/src/lib.rs
- hydroflow_lang/src/graph/flat_graph.rs
- hydroflow_lang/src/graph/mod.rs
- hydroflow_lang/src/parse.rs
Port indexing (`[0]my_var` or `my_var[2]`) is now associated with the
pipeline (variable name or operator[s]) rather than the arrow connector.
Handled as such in parsing and graph assembly.
Limitation: variable names that are only (naked) aliases of other names
will not show up in visualization graphs for the sake of #327. This is
because only operators and not edges are associated with variable names.
closes #266
> Allow alias name assignment without any arrow in surface syntax, closes #266

- hydroflow_lang/src/graph/di_mul_graph.rs
- hydroflow_lang/src/graph/flat_to_partitioned.rs
Improve documentation and use consistent language, i.e. `vertex` instead
of `node`.
quick little refactor
> Make `DiMulGraph` fields private for encapsulation

- Cargo.lock
- Cargo.toml
- hydroflow/Cargo.toml
- hydroflow/src/scheduled/net/mod.rs
- hydroflow/src/scheduled/net/network_vertex.rs
- hydroflow/src/util/mod.rs
- hydroflow/src/util/tcp.rs
- hydroflow/src/util/udp.rs
- hydroflow/tests/surface_async.rs
- hydroflow_datalog/Cargo.toml
- hydroflow_datalog_core/Cargo.toml
- hydroflow_internalmacro.d
- hydroflow_internalmacro/Cargo.toml
- hydroflow_lang/Cargo.toml
- hydroflow_macro/Cargo.toml
Tests do not work yet; I have a followup PR.
1. Turn off diagnostics for non-proc-macro crates. Diagnostics don't work when building for WASM. The proc-macro crates that are compiled at compile time still enable diagonstics because they target the (presumably non-WASM) host architecture where diagonstics work.
2. Use version 2 for the Cargo feature resolver. The version 1 resolver does not treat proc-macro edges differently from regular dependency edges. That is, suppose we depend on package P transitively via both a proc-macro edge and a regular edge, and the proc-macro edge enables feature X but the regular edge does not.
With the version 1 resolver, Cargo will compile P only once with X enabled (assuming same host and target arch). With the v2 resolver, Cargo will compile P (at least) …
> Get hydroflow to compile to WASM (#329)

- Cargo.lock
- hydro_cli/Cargo.toml
- hydro_cli/hydro/__init__.py
- hydro_cli/src/async_wrapper.py
- hydro_cli/src/core/custom_service.rs
- hydro_cli/src/core/deployment.rs
- hydro_cli/src/core/gcp.rs
- hydro_cli/src/core/hydroflow_crate.rs
- hydro_cli/src/core/localhost.rs
- hydro_cli/src/core/mod.rs
- hydro_cli/src/core/terraform.rs
- hydro_cli/src/main.rs
- hydro_cli/src/python_interface.rs
- hydro_cli/test.hydro.py
- hydroflow/examples/cli_receiver/main.rs
- hydroflow/examples/cli_sender/main.rs
- hydroflow/src/util/connection.rs
Also cleans up a bunch of downcasts due to poor `Arc` usage (evidently, `Arc<A> where A: B` can be used as an `Arc<dyn B>` (I need to really refine my understanding of `dyn`)
> Add API for defining custom services in deployment

- hydroflow/examples/cli_receiver/main.rs
- hydroflow/examples/cli_sender/main.rs
- hydroflow/tests/datalog_frontend.rs
- hydroflow_datalog_core/src/grammar.rs
- hydroflow_datalog_core/src/lib.rs
Require users to specify Hydroflow pipelines at the edges of a Dedalus program
Rather than hardcoding, which bakes in a lot of assumptions, this allows flexibility for sending data locally or over the network. Also updates the CLI example to use Dedalus.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/442).
* #445
* #443
* __->__ #442
> Require users to specify Hydroflow pipelines at the edges of a Dedalus program

- hydroflow/examples/cli_receiver/main.rs
- hydroflow/examples/cli_sender/main.rs
- hydroflow/tests/datalog_frontend.rs
- hydroflow_datalog_core/src/grammar.rs
- hydroflow_datalog_core/src/lib.rs
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__send_to_node@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__send_to_node@surface_graph.snap
Add `.async` Dedalus directive to specify pipeline for inter-Dedalus messaging
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/443).
* #445
* __->__ #443
> Add `.async` Dedalus directive to specify pipeline for inter-Dedalus messaging

- .github/workflows/ci.yml
Only skipped pinned Rust builds if nothing has changed when merging a PR
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/447).
* __->__ #447
> Only skipped pinned Rust builds if nothing has changed when merging a PR

- Cargo.lock
- relalg/Cargo.toml
- relalg/src/codegen.rs
- relalg/testdata/compile/compile
Use `prettyplease` in relalg tests to avoid `rustfmt` dependency
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/449).
* __->__ #449
> Use `prettyplease` in relalg tests to avoid `rustfmt` dependency

- hydro_cli/README.md
- hydro_cli/src/core/gcp.rs
- hydro_cli/src/core/hydroflow_crate.rs
- hydro_cli/src/core/localhost.rs
- hydro_cli/src/core/mod.rs
Enable local deployments on non-Linux hosts
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/451).
* #454
* #453
* #452
* __->__ #451
> Enable local deployments on non-Linux hosts

- .github/workflows/build-cli.yml
Add CI config for cross-building CLI to ARM Linux
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/453).
* #454
* __->__ #453
> Add CI config for cross-building CLI to ARM Linux

- .github/workflows/build-cli.yml
Fix cross-build Linux and Windows not uploading wheels
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/457).
* __->__ #457
> Fix cross-build Linux and Windows not uploading wheels

- Cargo.lock
- hydro_cli/Cargo.toml
- hydro_cli/hydro/__init__.py
- hydro_cli/src/core/gcp.rs
- hydro_cli/src/core/hydroflow_crate.rs
- hydro_cli/src/core/localhost.rs
- hydro_cli/src/core/mod.rs
- hydro_cli/src/lib.rs
- hydro_cli/test.hydro.py
- hydroflow/examples/cli_sender/main.rs
Allow specifying args to launch `HydroflowCrate` with. Fixes #422
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/460).
* #466
* #462
* #461
* __->__ #460
> Allow specifying args to launch `HydroflowCrate` with

- hydroflow_lang/src/graph/hydroflow_graph.rs
- hydroflow_lang/src/graph/ops/mod.rs
- hydroflow_lang/src/graph/ops/null.rs
Since `HydroflowGraph::as_code()` always returns regardless of errors, we should do our best to make the returned code as sensible as possible in the face of errors.
> Use `null` write fn when operator codegen errors

- benches/benches/micro_ops.rs
- hydroflow/src/lib.rs
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_and_comments@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max_all@datalog_program.snap
- hydroflow_lang/src/graph/ops/group_by.rs
This is a much faster hash function but it is not dos resistant.
groupby started to show up on the profile for the kvs benchmark so I made this change which greatly improved the perf of the kvs benchmark.
```
micro/ops/group_by      time:   [13.960 µs 14.044 µs 14.153 µs]
change: [-52.734% -52.343% -51.936%] (p = 0.00 < 0.05)
Performance has improved.
```
> Even faster groupby

- Cargo.lock
- hydroflow/tests/compile-fail/surface_dest_sink_badsink.stderr
- hydroflow_datalog_core/Cargo.toml
Update Rust Sitter to fix Dedalus parser on WASM
> Update Rust Sitter to fix Dedalus parser on WASM

- hydroflow/tests/compile-fail/surface_lattice_merge_badgeneric.rs
- hydroflow/tests/compile-fail/surface_lattice_merge_badgeneric.stderr
- hydroflow/tests/compile-fail/surface_lattice_merge_nogeneric.rs
- hydroflow/tests/compile-fail/surface_lattice_merge_nogeneric.stderr
- hydroflow/tests/compile-fail/surface_lattice_merge_wronggeneric.rs
- hydroflow/tests/compile-fail/surface_lattice_merge_wronggeneric.stderr
- hydroflow/tests/surface_lattice_merge.rs
- hydroflow_lang/src/graph/ops/lattice_merge.rs
- hydroflow_lang/src/graph/ops/mod.rs
Baby steps
I guess for now all the lattice-based operators will be prefixed with `lattice_`
> Add specialized `lattice_merge::<MyLatRepr>()` operator

- hydro_cli/src/core/gcp.rs
Ignore GCP port requests for ports that have already been allocated
> Ignore GCP port requests for ports that have already been allocated

- hydro_cli/src/core/custom_service.rs
- hydro_cli/src/core/hydroflow_crate/mod.rs
- hydro_cli/src/core/hydroflow_crate/ports.rs
Generalize null source support into `SourcePath` abstraction
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/532).
* #533
* __->__ #532
> Generalize null source support into `SourcePath` abstraction

- hydroflow/src/util/cli.rs
- hydroflow/tests/compile-fail/surface_lattice_merge_badgeneric.stderr
- hydroflow_cli_integration/src/lib.rs
Start accepting connections in the background of CLI initialization to avoid deadlocks
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/541).
* #543
* #542
* __->__ #541
> Start accepting connections in the background of CLI initialization to avoid deadlocks

- hydro_cli/python_tests/basic.py
- hydro_cli/src/core/gcp.rs
- hydro_cli/src/core/hydroflow_crate/mod.rs
- hydro_cli/src/core/hydroflow_crate/ports.rs
- hydro_cli/src/core/localhost.rs
- hydro_cli/src/core/mod.rs
- hydro_cli/src/core/terraform.rs
- hydro_cli/src/lib.rs
- hydro_cli_examples/Cargo.toml
- hydro_cli_examples/examples/empty_program/main.rs
Avoid deadlock in port loading when a service connects to itself
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/542).
* #543
* __->__ #542
> Avoid deadlock in port loading when a service connects to itself

- hydroflow/tests/datalog_frontend.rs
- hydroflow_datalog_core/src/join_plan.rs
- hydroflow_datalog_core/src/lib.rs
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_fields@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_fields@surface_graph.snap
Support `_` as a wildcard variable in Dedalus rules that is not joined on
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/549).
* #551
* __->__ #549
> Support `_` as a wildcard variable in Dedalus rules that is not joined on

- hydroflow/src/lang/monotonic_map.rs
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__anti_join@datalog_program.snap
- hydroflow_lang/src/graph/ops/anti_join.rs
micro/ops/anti_join     time:   [13.142 µs 13.184 µs 13.232 µs]
change: [-69.713% -69.428% -68.945%] (p = 0.00 < 0.05)
Performance has improved.
> antijoin uses FxHash instead of SipHash

- hydroflow/src/lang/clear.rs
- hydroflow/src/lang/monotonic_map.rs
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_and_comments@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__anti_join@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_lhs@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_predicate@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__join_with_other@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__join_with_self@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__local_constraints@datalog_program-2.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__local_constraints@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max_all@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__minimal_program@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__multiple_contributors@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__non_copy_but_clone@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist_uniqueness@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__send_to_node@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__simple_filter@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__single_column_program@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__transitive_closure@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__triple_relation_join@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_fields@datalog_program.snap
- hydroflow_lang/src/graph/ops/unique.rs
micro/ops/unique        time:   [84.333 µs 84.933 µs 85.651 µs]
change: [-68.397% -68.069% -67.798%] (p = 0.00 < 0.05)
Performance has improved.
> unique uses FxHash instead of SipHash

- hydro_cli_examples/examples/dedalus_sender/main.rs
Fix hang in Hydro CLI tests due to change in `repeat_iter` semantics
Fixes #580
> Fix hang in Hydro CLI tests due to change in `repeat_iter` semantics

- Cargo.toml
This caused a 25% perf improvement in the paxos benchmark, but it seems to cause some slowdowns in the micro benchmarks. I think that the more complex a benchmark gets, the more likely it is to benefit from this. So, I think those slowdowns are more a reflection of a bad benchmark than this change causing slowdowns in general.
Additionally, this change seems to remove the performance penalty for introducing the additional function calls to tag operators for better profiles.
This change will slow down build times a little bit.
> set lto = fat in release profile

- hydroflow/Cargo.toml
- hydroflow/src/compiled/pull/half_join_state/multiset.rs
- hydroflow/src/compiled/pull/half_join_state/set.rs
joins are a nested structure, they are hash maps with vecs in them. We already re-added Clear impls everywhere to avoid freeing the hash table memory, but when clear() is called it still deletes all the values in the hash map, which causes the vecs to drop and free their memory. If we use a smallvec instead then, at least for the paxos case, most of the allocations never happen and also none of the subsequent frees happen either. This results in a pretty decent speedup for the paxos test.
> add smallvec for multiset join

- hydroflow/examples/hello_world/README.md
- hydroflow/examples/hello_world/main.rs
Add a very simple example to the examples folder for two reasons.
The first is that the current simplest example we have is 'graph reachability' which is somewhat simple from a hydroflow standpoint but relatively conceptually heavy. Traditionally there would be a 'hello world' example that does almost nothing as a real from-nothing starting point.
The second reason is that I often find myself editing graph reachability to run some simple hydroflow program to use cargo expand or to profile with, if I could edit this simpler program instead it would save me some minor annoyances.
> add Hello World hydroflow example

- .github/workflows/ci.yml
- Cargo.lock
- hydro_cli/Cargo.toml
- hydro_cli/README.md
- hydro_cli/src/core/hydroflow_crate/build.rs
- hydro_cli/src/core/hydroflow_crate/mod.rs
- hydro_cli_examples/pn_counter.hydro.py
- hydro_cli_examples/topolotree.hydro.py
- hydro_cli_examples/topolotree_latency.hydro.py
Replace using `cargo` as a library to shell out with `cargo-metadata` instead
This eliminates the need to do `rustup run` incantations to use the right toolchain, because now we just pick up the `rustup`-wrapped `cargo` instead!
> Replace using `cargo` as a library to shell out with `cargo-metadata` instead

- hydroflow/src/lang/collections.rs
- hydroflow/src/lang/lattice/set_union.rs
- hydroflow/src/lang/lattice2/mod.rs
- hydroflow/src/lang/lattice2/ord.rs
- hydroflow/src/lang/lattice2/set_union.rs
- Fix `Min` compare reversed
- Impl compare for `Max`
- Fix `SetUnion` compare logical error (long standing old bug)
- Add `NaiveCompare` trait based on merge fn
- Improve `SetUnion` tests
> lattice2: Add `NaiveCompare`, fix `Ord` & `SetUnion` bugs

- Cargo.lock
- hydroflow/Cargo.toml
- hydroflow/src/lang/lattice/dom_pair.rs
- hydroflow/src/lang/lattice/map_union.rs
- hydroflow/src/lang/lattice/pair.rs
- hydroflow/src/lang/lattice/set_union.rs
- hydroflow/src/lib.rs
- Remove unused `async-trait`, `crdts`, `serde-big-array`
- Move `rand_distr`, `regex`, `static_assertions` to `dev-dependencies`
> Cleanup `hydroflow` dependencies

- hydroflow_macro/build.rs
Wasn't building because the `.gitignore`d output file didn't exist. Instead check if that file's parent folder exists.
Fixup: a78ff9aace6771787c2b72aad83be6ad8d49a828
> Fix book operators build

- hydroflow/src/util/mod.rs
- hydroflow_lang/src/graph/ops/dest_sink.rs
- hydroflow_lang/src/graph/ops/dest_sink_serde.rs
Also loosens some bounds in `hydroflow::util::{serialize_to_bytes, deserialize_from_bytes}`
First commit working towards backpressure
> Deduplicate `dest_sink_serde` code by using `dest_sink`'s `write_fn`

- .github/workflows/ci.yml
Adjust CLI core dump collection logic
We had a crash in a recent build, but no core dump was uploaded. This will hopefully help.
> Adjust CLI core dump collection logic

- hydroflow/tests/compile-fail/surface_lattice_merge_badgeneric.stderr
- hydroflow_lang/src/graph/ops/lattice_merge.rs
`Default` no longer needed
#710
> refactor(hydroflow_lang): change `lattice_merge` to use `reduce` instead of `fold`, fix #710

- hydroflow/tests/surface_multiset_delta.rs
- hydroflow_lang/src/graph/ops/multiset_delta.rs
fix(hydroflow_lang): multiset_delta not correctly tracking counts beyond two ticks
We were swapping the `RefCell`s, but we need to swap what's _behind_ them.
> fix(hydroflow_lang): multiset_delta not correctly tracking counts beyond two ticks

- hydroflow/src/util/cli.rs
fix(hydroflow): clippy fails on latest nightly in CLI integration
> fix(hydroflow): clippy fails on latest nightly in CLI integration

- lattices/src/bottom.rs
This came up when trying to merge a `Top<Bottom<SetUnionSingletonSet>` into a `Top<Bottom<SetUnionHashSet>>`
> fix: fix ConvertFrom for bottom to actually convert the type

- .vscode/settings.json
- Cargo.lock
- hydroflow/Cargo.toml
- multiplatform_test/Cargo.toml
- multiplatform_test/README.md
- multiplatform_test/src/lib.rs
- multiplatform_test/tests/test.rs
* Adds `tokio` for `#[tokio::test]`.
* Adds `async_std` for `#[async_std::test]`.
* Adds `hydroflow` for `#[hydroflow::test]`.
* Adds `env_logging` for `env_logger` registering.
* Adds `env_tracing` for `EnvFilter` `FmtSubscriber` `tracing`.
BREAKING CHANGE: `default` is renamed to `test` (for `#[test]`)
> feat(multiplatform_test)!: `hydroflow`, `logging`/`tracing` features

- hydroflow/examples/shopping/lattices.rs
- hydroflow/src/compiled/pull/symmetric_hash_join_lattice.rs
- hydroflow_lang/src/graph/ops/lattice_batch.rs
- hydroflow_lang/src/graph/ops/lattice_join.rs
- lattices/README.md
- lattices/src/dom_pair.rs
- lattices/src/lib.rs
- lattices/src/map_union.rs
- lattices/src/ord.rs
- lattices/src/pair.rs
- lattices/src/point.rs
- lattices/src/seq.rs
- lattices/src/set_union.rs
- lattices/src/with_bot.rs
- lattices/src/with_top.rs
BREAKING CHANGE: `ConvertFrom::from` renamed to `LatticeFrom::lattice_from` to better reflect its usage.
> refactor(lattices)!: Rename `ConvertFrom::from` -> `LatticeFrom::lattice_from`

- .github/workflows/build-cli.yml
fix(cli): cross build to glibc linux instead of musl for ARM platforms
> fix(cli): cross build to glibc linux instead of musl for ARM platforms

- hydroflow/examples/hello_world/main.rs
- hydroflow/examples/kvs_bench/protocol/serialization/lattices/map_union.rs
- hydroflow/examples/kvs_bench/protocol/serialization/lattices/my_last_write_wins.rs
- hydroflow/examples/kvs_bench/server.rs
- hydroflow/examples/lamport_clock/client.rs
- hydroflow/examples/lamport_clock/server.rs
- hydroflow/examples/vector_clock/client.rs
- hydroflow/examples/vector_clock/server.rs
- hydroflow/src/compiled/pull/symmetric_hash_join_lattice.rs
- hydroflow_lang/src/graph/ops/lattice_merge.rs
- lattices/src/conflict.rs
- lattices/src/dom_pair.rs
- lattices/src/map_union.rs
- lattices/src/ord.rs
- lattices/src/pair.rs
- lattices/src/seq.rs
- lattices/src/set_union.rs
- lattices/src/with_bot.rs
- lattices/src/with_top.rs
fix #768
BREAKING CHANGE: changes some fields from `pub` to private.
> feat(lattices)!: Add `reveal` methods, make fields private (#789)

- README.md
- docs/src/pages/playground.js
- hydroflow/examples/example_2_simple_1.rs
- hydroflow_lang/src/graph/ops/inspect.rs
`*` derefs are easier for Rust beginners to comprehend.
> docs: remove pattern deref from inspect, filter examples

- benches/benches/reachability.rs
- docs/docs/hydroflow/quickstart/example_5_reachability.mdx
- hydroflow/examples/example_5_reachability.rs
- hydroflow/examples/example_6_unreachability.rs
- hydroflow/tests/snapshots/surface_codegen__covid_tracing@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_codegen__covid_tracing@graphvis_mermaid.snap
- hydroflow/tests/snapshots/surface_examples__example_5_reachability.snap
- hydroflow/tests/snapshots/surface_examples__example_6_unreachability.snap
- hydroflow/tests/surface_codegen.rs
- hydroflow_lang/src/graph/ops/join.rs
- hydroflow_lang/src/graph/ops/join_multiset.rs
- hydroflow_lang/src/graph/ops/mod.rs
also remove documentation about HalfJoinMultiset, the way to access that now is to use join_multiset()
fixes https://github.com/hydro-project/hydroflow/issues/802
> feat: add join_multiset()

- .github/workflows/build-cli.yml
fix(cli): use auto manylinux for aarch64-linux CLI builds
Should fix the failing builds on main
> fix(cli): use auto manylinux for aarch64-linux CLI builds

- .github/workflows/build-cli.yml
fix(cli): skip installing the wheel when cross-building for Linux ARM
> fix(cli): skip installing the wheel when cross-building for Linux ARM

- benches/benches/fork_join.rs
- hydroflow/examples/shopping/driver.rs
- hydroflow/examples/three_clique/main.rs
- hydroflow/src/scheduled/net/mod.rs
- hydroflow/src/scheduled/state.rs
- hydroflow/tests/test.rs
- hydroflow_lang/build.rs
- hydroflow_lang/src/graph/di_mul_graph.rs
- hydroflow_lang/src/graph/flat_graph_builder.rs
- hydroflow_lang/src/graph/hydroflow_graph.rs
- hydroflow_lang/src/graph/ops/demux.rs
- lattices/src/seq.rs
- multiplatform_test/src/lib.rs
- pusherator/src/lib.rs
rustfmt formats let-else statements
clippy lints unnecessary vecs, unnecessary into_iter calls
In nightly version (d9c13cd45 2023-07-05)
> chore: fix lint, format errors for latest nightly version (without updating pinned)

- hydroflow/src/util/mod.rs
- hydroflow/tests/surface_codegen.rs
- hydroflow_lang/src/graph/ops/assert_eq.rs
* Also tightens up a bit of `assert_eq`'s code
> feat(hydroflow): add `iter_batches_stream` util to break up iterator into per-tick batches

- lattices/README.md
- lattices/src/lib.rs
- lattices/src/vec_union.rs
BREAKING CHANGE: Renames public struct `Seq` -> `VecUnion`
> refactor(lattices)!: Rename `Seq` -> `VecUnion`

- lattices/src/lib.rs
- lattices/src/map_union.rs
- lattices/src/set_union.rs
- lattices/src/test.rs
- lattices/src/unit.rs
- lattices/src/with_bot.rs
- lattices/src/with_top.rs
Hmm, if we just define atomize as returning some maximal, ideally-strong antichain, then it _is_ implementable for all lattices (although not unambiguous)
tests incoming
> feat(lattices): Add atomize trait

- hydroflow/examples/deadlock_detector/peer.rs
replace 'static join with explicit persist operators that replay. workaround for #519
> fix: livelock in deadlock detector #810

- lattices/src/collections.rs
- lattices/src/conflict.rs
- lattices/src/lib.rs
- lattices/src/map_union.rs
- lattices/src/ord.rs
- lattices/src/pair.rs
- lattices/src/set_union.rs
- lattices/src/test.rs
- lattices/src/vec_union.rs
- lattices/src/with_bot.rs
- lattices/src/with_top.rs
* `WithBot(Some(BOTTOM))` and `WithBot(None)` are now considered to be equal. Also, `MapUnion({})` and `MapUnion({key: BOTTOM})` are considered to be equal.
* `check_lattice_bot/top` now check that `is_bot` and `is_top` must be consistent between all equal elements
BREAKING CHANGE:
* `Set/MapUnionOption` renamed to `Set/MapUnionOptionSet/Map`
* `MapUnion` and `WithBot` containing nested bottom value is now considered to be bottom as well.
> feat(lattices)!: Add bottom collapsing, implement `IsBot` for all lattice types

- lattices/src/lib.rs
- lattices/src/map_union.rs
- lattices/src/set_union.rs
- lattices/src/test.rs
- lattices/src/with_bot.rs
Previously was the opposite, `Atomize` always had to return non-empty.
Not breaking since `Atomize` has not yet been published.
> refactor(lattices): Change `Atomize` to require returning empty iff lattice is bottom

- docs/docs/deploy/index.md
fix(docs): move warning about Hydro Deploy docs to the top of the intro
> fix(docs): move warning about Hydro Deploy docs to the top of the intro

- hydroflow_lang/src/graph/hydroflow_graph.rs
https://github.com/rust-lang/rust-clippy/issues/11290
> chore(hydroflow_lang): Allow `clippy::redundant_locals`, for latest nightlies

- hydroflow/src/compiled/pull/half_join_state/mod.rs
- hydroflow/src/compiled/pull/half_join_state/multiset.rs
- hydroflow/src/compiled/pull/half_join_state/set.rs
- hydroflow/src/compiled/pull/symmetric_hash_join.rs
evidence for this change is pretty weak:
```
micro/ops/join          time:   [113.65 µs 114.38 µs 115.80 µs]
change: [-0.0148% +1.0042% +2.3994%] (p = 0.12 > 0.05)
No change in performance detected.
micro/ops/crossjoin     time:   [152.13 µs 153.46 µs 155.27 µs]
change: [+2.3725% +3.6797% +5.3980%] (p = 0.00 < 0.05)
Performance has regressed.
micro/ops/anti_join     time:   [12.927 µs 12.957 µs 12.994 µs]
change: [-0.4503% +0.1853% +0.7231%] (p = 0.57 > 0.05)
No change in performance detected.
symmetric_hash_join/no_match
time:   [126.19 µs 126.68 µs 127.37 µs]
change: [-4.5148% -0.9976% +2.6660%] (p = 0.59 > 0.05)
No change in performance detected.
symmetric_hash_join/match_keys_diff_values
time:   [174.17 µs 174.47 µs 174.78 µs]
change: [-6.0184% -3.7568% -1.7607%] (p = 0.00 < 0.05) …
```
> optimization: join probe returns first item directly

- lattices/README.md
- lattices/src/conflict.rs
- lattices/src/dom_pair.rs
- lattices/src/ord.rs
- lattices/src/test.rs
- lattices/src/with_top.rs
Not a breaking change since changed names were introduced only in this version
> feat(lattices): formalize `Default::default()` as returning bottom for lattice types

- hydroflow/examples/kvs_bench/server.rs
- hydroflow/tests/surface_lattice_batch.rs
- hydroflow/tests/surface_lattice_join.rs
- hydroflow_lang/src/graph/ops/_lattice_fold_batch.rs
- hydroflow_lang/src/graph/ops/_lattice_join_fused_join.rs
- hydroflow_lang/src/graph/ops/mod.rs
- hydroflow_macro/build.rs
fixes https://github.com/hydro-project/hydroflow/issues/832
> fix: separate internal compiler operators in docs name/category/sort order

- hydroflow/tests/compile-fail/surface_degenerate_null.stderr
- hydroflow/tests/compile-fail/surface_null.stderr
- hydroflow_lang/src/graph/hydroflow_graph.rs
Makes the pinned and latest nightly version have the same stderr output for consistent testing.
> fix(hydroflow_lang): Clean up degenerate subgraph error message for consistency

- hydroflow/src/scheduled/context.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/tests/snapshots/surface_join_fused__static_static_lhs_streaming_rhs_blocking@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_join_fused__static_static_lhs_streaming_rhs_blocking@graphvis_mermaid.snap
- hydroflow/tests/surface_join_fused.rs
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__anti_join@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__index@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__join_with_other@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__join_with_self@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist_uniqueness@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__single_column_program@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__transitive_closure@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__triple_relation_join@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_fields@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_join_count@datalog_program.snap
- hydroflow_lang/src/graph/ops/anti_join.rs
- hydroflow_lang/src/graph/ops/anti_join_multiset.rs
- hydroflow_lang/src/graph/ops/join.rs
- hydroflow_lang/src/graph/ops/join_fused_lhs.rs
- hydroflow_lang/src/graph/ops/multiset_delta.rs
- hydroflow_lang/src/graph/ops/persist.rs
- hydroflow_lang/src/graph/ops/persist_mut.rs
- hydroflow_lang/src/graph/ops/persist_mut_keyed.rs
fixes https://github.com/hydro-project/hydroflow/issues/875
> feat: add context.is_first_time_subgraph_is_scheduled to simplify replaying operators

- .github/workflows/ci.yml
Speeds up CI testing from about 23m to 12m
20 is the max number of parallel jobs running, this change results in 12 jobs per PR
Build seems to take about 4m, so that is fastest lower bound without upgrading to beefier gh-actions machines
before:
after:
> ci: parallelize target selection to speed up `cargo test`ing

- rust-toolchain.toml
> fix: bump pinned Rust to fix ICE in surface syntax type inference, fix #951

- hydroflow/examples/chat/server.rs
- hydroflow/examples/two_pc/coordinator.rs
- hydroflow/examples/two_pc/subordinate.rs
- lattices/README.md
- In chat's main join, use `'tick` lifetime for messages.
- Add a `persist_mut_keyed` to track phases in 2PC, to avoid resending messages endlessly. In future would be a good challenge to rewrite monotonically.
- 2PC still contains one `fold` that accumulates state indefinitely.
> chat and two_pc no longer replay

- hydroflow/examples/chat/main.rs
chat example was failing tests, seems to be due to missed message. adding a 100ms sleep helps.
> add 100ms sleep to chat example to avoid dropped packet

- hydroflow_plus/src/builder.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/lib.rs
- hydroflow_plus_test/src/snapshots/hydroflow_plus_test__tests__teed_join_multi_node@graphvis_dot.snap
- hydroflow_plus_test/src/snapshots/hydroflow_plus_test__tests__teed_join_multi_node@graphvis_mermaid.snap
feat(hydroflow): allow Hydroflow+ programs to emit multiple graphs
This PR adds support for tagging elements of Hydroflow+ graphs with a node ID, an integer which specifies which Hydroflow graph the computation should be emitted to. The generated code includes the Hydroflow graph for each node ID, so that the appropriate graph can be selected at runtime.
At a larger scale, this is a precursor to adding network operators to Hydroflow+, which will allow distributed logic to be described in a single Hydroflow+ program by specifying points at which data is transferred between different graphs.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/976).
* #982
* #981
* #978
* __->__ #976
> feat(hydroflow): allow Hydroflow+ programs to emit multiple graphs

- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/python_tests/basic.py
- hydroflow_plus_test/src/networked.rs
feat(hydroflow): add preliminary `send_to` operator for multi-node graphs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/981).
* #982
* __->__ #981
> feat(hydroflow): add preliminary `send_to` operator for multi-node graphs

- hydroflow_plus_test/examples/networked_basic.rs
- stageleft/README.md
- stageleft/src/lib.rs
- stageleft/src/runtime_support.rs
- stageleft_macro/src/lib.rs
- stageleft_macro/src/quote_impl/free_variable/mod.rs
- stageleft_tool/src/lib.rs
feat(stageleft): support crates that have no entrypoints
Also includes various bugfixes needed for Hydroflow+.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/983).
* #984
* #982
* __->__ #983
> feat(stageleft): support crates that have no entrypoints

- Cargo.lock
- docs/docs/hydroflow_plus/distributed.mdx
- hydro_deploy/core/src/hydroflow_crate/mod.rs
- hydro_deploy/hydroflow_plus_cli_integration/Cargo.toml
- hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs
- hydro_deploy/hydroflow_plus_cli_integration/src/lib.rs
- hydro_deploy/hydroflow_plus_cli_integration/src/runtime.rs
- hydroflow/src/util/cli.rs
- hydroflow_plus_test/examples/first_ten_distributed.rs
- hydroflow_plus_test/examples/map_reduce.rs
- hydroflow_plus_test/examples/networked_basic.rs
- hydroflow_plus_test/examples/simple_cluster.rs
- hydroflow_plus_test/src/bin/first_ten_distributed.rs
- hydroflow_plus_test/src/bin/many_to_many.rs
- hydroflow_plus_test/src/bin/map_reduce.rs
- hydroflow_plus_test/src/bin/networked_basic.rs
- hydroflow_plus_test/src/bin/simple_cluster.rs
- hydroflow_plus_test/src/cluster.rs
- hydroflow_plus_test/src/first_ten.rs
- hydroflow_plus_test/src/networked.rs
feat(hydroflow_plus): pass subgraph ID through deploy metadata
> feat(hydroflow_plus): pass subgraph ID through deploy metadata

- Dockerfile
- scripts/build_dist_release.sh
fix(hydro_deploy): exclude from Dockerfile build
Should fix the Docker image build, _for realz_.
> fix(hydro_deploy): exclude from Dockerfile build

- Cargo.lock
- docs/docs/hydroflow_plus/distributed.mdx
- hydroflow/src/util/cli.rs
- hydroflow/src/util/mod.rs
- hydroflow_plus/Cargo.toml
- hydroflow_plus_test/Cargo.toml
- hydroflow_plus_test/examples/networked_basic.rs
- hydroflow_plus_test/src/bin/first_ten_distributed.rs
- hydroflow_plus_test/src/bin/many_to_many.rs
- hydroflow_plus_test/src/bin/map_reduce.rs
- hydroflow_plus_test/src/bin/networked_basic.rs
- hydroflow_plus_test/src/bin/simple_cluster.rs
- hydroflow_plus_test/src/cluster.rs
- hydroflow_plus_test/src/first_ten.rs
- hydroflow_plus_test/src/networked.rs
- hydroflow_plus_test_macro/Cargo.toml
feat(hydroflow_plus): provide simpler API for launching and minimize dependencies
The new `hydroflow::cli::util::launch` API takes a function from the `HydroCLI` config to a `Hydroflow`, which allows us to wait until the `Hydroflow` struct is instantiated (and all network connections are established) before returning the "ack start" message. This is also why this PR is stacked, because it triggers the race condition much more consistently.
This also disables depending on default features of Hydroflow from Hydroflow+, which should speed up builds because we no longer load the Hydroflow / Datalog macros.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1003).
* #1004
* __->__ #1003
> feat(hydroflow_plus): provide simpler API for launching and minimize dependencies

- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster.rs
- hydroflow_plus_test/src/lib.rs
feat(hydroflow_plus): tweak naming of windowing operators
persist -> all_ticks
batched -> tick_batch
seems to help with legibility
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1006).
* #1007
* #1002
* __->__ #1006
> feat(hydroflow_plus): tweak naming of windowing operators

- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_and_comments@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_fold_keyed_expr@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__index@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max_all@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist_uniqueness@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_join_count@datalog_program.snap
- hydroflow_lang/src/graph/ops/fold_keyed.rs
- hydroflow_lang/src/graph/ops/reduce_keyed.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster.rs
feat(hydroflow_plus): implement keyed fold and reduce
> feat(hydroflow_plus): implement keyed fold and reduce

- hydroflow_plus/src/stream.rs
fix(hydroflow_plus): persist cluster IDs for broadcast
I'll follow this up with a unit test for this, but want to get this fixed ASAP first.
> fix(hydroflow_plus): persist cluster IDs for broadcast

- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_and_comments@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_fold_keyed_expr@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__anti_join@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_lhs@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__expr_predicate@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__index@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__join_with_self@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max_all@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist_uniqueness@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__send_to_node@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_fields@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_join_count@datalog_program.snap
- hydroflow_lang/src/graph/hydroflow_graph.rs
Before, prologue code would be emitted before its subgraph, resulting in interleaving between subgraphs.
> refactor(hydroflow_lang): emit prologue code before all subgraph code

- docs/docs/hydroflow_plus/quickstart/clusters.mdx
- docs/docs/hydroflow_plus/quickstart/structure.mdx
* Fixes undeclared variable in one of the quickstart code snippets. With this change all snippets work for me.
* Minor copyedit in the structure section.
> docs: Fix undeclared quickstart variable

- README.md
- docs/docs/hydroflow/quickstart/example_1_simplest.mdx
- docs/docs/hydroflow/quickstart/example_2_simple.mdx
- docs/docs/hydroflow/quickstart/example_5_reachability.mdx
1. Simplest example: one of the links wasn't rendering. The line containing the link needs to be in a separate paragraph from <CodeBlock> for the link to work.
2. Simple example: `flat_map` generates a `RangeInclusive`. Existing code probably generated a `Vec`. Updated.
3. Graph Reachability: Code block now shows the line where `origin` vertex is input into `reached_vertices`.
4. Added `README.md` instructions to enable ligatures.
> docs: Few improvements to the quickstart guides

- .gitignore
- benches/build.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/src/scheduled/handoff/handoff_list.rs
- hydroflow/src/scheduled/handoff/tee.rs
- hydroflow/src/scheduled/mod.rs
- hydroflow/src/scheduled/port.rs
- hydroflow/tests/scheduled_teeing_handoff.rs
- hydroflow/tests/scheduled_test.rs
- Add `tee()` method for `RecvPort<TeeingHandoff<T>>` so it can be cloned accordingly, I'm not sure if I made prec and succ fields right though.
- Added `add_handoff` and `get_handoff_by_id` for Hydroflow for a more detailed control of handoffs
- also added test `test_auto_tee` back. So `tee` method is tested.
> feat: tee port for scheduled API

- docs/docs/hydroflow_plus/clusters.mdx
- docs/docs/hydroflow_plus/process_streams.mdx
- docs/docs/hydroflow_plus/quickstart/clusters.mdx
- docs/docs/hydroflow_plus/quickstart/distributed.mdx
- docs/docs/hydroflow_plus/quickstart/structure.mdx
- hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs
- hydro_deploy/hydroflow_plus_cli_integration/src/runtime.rs
- hydroflow_plus/src/builder.rs
- hydroflow_plus/src/cycle.rs
- hydroflow_plus/src/lib.rs
- hydroflow_plus/src/location/graphs.rs
- hydroflow_plus/src/location/mod.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster.rs
- hydroflow_plus_test/src/first_ten.rs
- hydroflow_plus_test/src/lib.rs
- hydroflow_plus_test/src/negation.rs
- hydroflow_plus_test/src/networked.rs
- stageleft/README.md
- stageleft/src/lib.rs
- stageleft_macro/src/lib.rs
- stageleft_test/src/lib.rs
- stageleft_test/src/submodule.rs
feat(hydroflow_plus): simplify lifetime bounds for processes and clusters
This allows `extract` to move the flow builder, which is a prerequisite for having developers run the optimizer during deployment as well in case it changes the network topology.
> feat(hydroflow_plus): simplify lifetime bounds for processes and clusters

- hydroflow_plus_test/src/first_ten.rs
- stageleft_macro/src/lib.rs
fix(stageleft): ignore unnecessary lifetime lint on entrypoints
> fix(stageleft): ignore unnecessary lifetime lint on entrypoints

- hydroflow_plus/src/builder.rs
fix(hydroflow_plus): allow BuiltFlow to be cloned even if the deploy flavor can't
> fix(hydroflow_plus): allow BuiltFlow to be cloned even if the deploy flavor can't

- hydroflow/tests/snapshots/surface_singleton__fold_singleton@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_singleton__fold_singleton@graphvis_mermaid.snap
- hydroflow/tests/snapshots/surface_singleton__fold_singleton_push@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_singleton__fold_singleton_push@graphvis_mermaid.snap
- hydroflow/tests/surface_singleton.rs
- hydroflow_lang/src/graph/hydroflow_graph.rs
- hydroflow_lang/src/graph/ops/fold.rs
- hydroflow_lang/src/process_singletons.rs
> feat(hydroflow_lang): allow `fold()` to be referenceable as a singleton (3/x)

- .github/workflows/ci.yml
ci: enable sccache on windows
Due to cross-platform incompatibilities with `GITHUB_ENV` it was never enabled on Windows.
> ci: enable sccache on windows

- hydroflow/examples/chat/README.md
- hydroflow/examples/chat/client.rs
- hydroflow/examples/chat/main.rs
- hydroflow/examples/chat/randomized_gossiping_server.rs
- hydroflow/examples/chat/server.rs
Added a gossip-based backend for the chat example.
The implementation is based on ["Epidemic algorithms for replicated database maintenance"](https://dl.acm.org/doi/epdf/10.1145/41840.41841). Specifically, it implements push-based "rumor-mongering" with a blind-coin removal process.
> Extend Chat Example w/ Gossip Based Backend

- docs/docs/hydroflow/syntax/surface_data.mdx
- hydroflow/tests/surface_book.rs
- hydroflow_lang/src/graph/ops/source_interval.rs
Addresses #1186.
`source_interval` emits instances of `tokio::time::instant`. Clocks in the Context (like `current_tick_start`) also indicate the time the tick started. There's some potential for users to confuse these timestamps or fall into the trap of reasoning about the semantics of these clocks/comparability, etc.
`source_interval` should just emit unit instances `()` when it has data. If someone still needs a clock reading, they can `map` it to something that makes sense for their application.
> `source_interval` no longer emits Instant instances on output.

- hydroflow/examples/kvs_bench/server.rs
- hydroflow/src/scheduled/context.rs
- hydroflow/src/scheduled/graph.rs
- hydroflow/src/scheduled/mod.rs
- hydroflow/src/scheduled/ticks.rs
- hydroflow/tests/snapshots/surface_scheduling__stratum_loop@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_scheduling__stratum_loop@graphvis_mermaid.snap
- hydroflow/tests/snapshots/surface_scheduling__tick_loop@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_scheduling__tick_loop@graphvis_mermaid.snap
- hydroflow/tests/surface_codegen.rs
- hydroflow/tests/surface_fold.rs
- hydroflow/tests/surface_join.rs
- hydroflow/tests/surface_join_fused.rs
- hydroflow/tests/surface_keyed_fold.rs
- hydroflow/tests/surface_persist.rs
- hydroflow/tests/surface_reduce.rs
- hydroflow/tests/surface_scheduling.rs
- hydroflow/tests/surface_singleton.rs
- hydroflow/tests/surface_state_scheduling.rs
- hydroflow_lang/src/graph/ops/defer_tick.rs
- hydroflow_lang/src/graph/ops/zip.rs
- topolotree/src/main.rs
- topolotree/src/pn.rs
- topolotree/src/pn_delta.rs
Addresses #1185.
This change introduces a couple of newtypes and associated arithmetic operations:
1. `TickInstant`
2. `TickDuration`
Using newtypes should prevent mixing/accidental swap of clock values in user code.
Additionally, the numeric type of the clock has been changed from `usize`, which can be of a different size based on compilation target. It has been replaced by `u64`.
> feat(hydroflow)!: Introduce newtypes for working with ticks

- hydroflow/tests/snapshots/surface_lattice_bimorphism__join@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_lattice_bimorphism__join@graphvis_mermaid.snap
- hydroflow/tests/surface_lattice_bimorphism.rs
- lattices/src/map_union.rs
BREAKING CHANGE: use `KeyedBimorphism::new` instead of `KeyedBimorphism::from`
> fix(lattices)!: use `new()` instead of `From::from` for `KeyedBimorphism` to prevent bad type inference, fix #1228

- hydro_deploy/hydroflow_plus_cli_integration/Cargo.toml
- hydroflow/Cargo.toml
- hydroflow_plus/Cargo.toml
https://github.com/Byron/cargo-smart-release/issues/16
> chore: use workaround for `cargo smart-release` not properly ordering `dev-`/`build-dependencies`

- hydroflow/examples/kvs_bench/protocol/serialization/lattices/with_bot.rs
- lattices/src/with_bot.rs
- lattices/src/with_top.rs
`Option<T>` is not a lattice, so it is unsafe to expose as public.
I also updated documentation to lead with intention before implementation (minor cleanup).
> fix(lattices): Make inner for `WithTop` & `WithBot` private

- .vscode/settings.json
- Cargo.lock
- Cargo.toml
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_and_comments@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__aggregations_fold_keyed_expr@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__collect_vec@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__index@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__max_all@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__persist_uniqueness@datalog_program.snap
- hydroflow_datalog_core/src/snapshots/hydroflow_datalog_core__tests__wildcard_join_count@datalog_program.snap
- lattices/Cargo.toml
- lattices/src/lib.rs
- lattices/src/map_union.rs
- lattices/src/map_union_with_tombstones.rs
- lattices/src/pair.rs
- lattices/tests/compile-fail/non_lattice_field.rs
- lattices/tests/compile-fail/non_lattice_field.stderr
- lattices/tests/compile_fail.rs
- lattices/tests/macro.rs
- lattices_macro/Cargo.toml
- lattices_macro/README.md
- lattices_macro/src/lib.rs
- lattices_macro/src/snapshots/lattices_macro__test__derive_example.snap
- lattices_macro/src/snapshots/lattices_macro__test__derive_pair.snap
- lattices_macro/src/snapshots/lattices_macro__test__derive_similar_fields.snap
- precheck.bash
This adds derive macros to allow user-created macros. Each field must be a lattice.
Example usage:
```rust
struct MyLattice<KeySet, Epoch>
where
KeySet: Collection,
Epoch: Ord,
{
keys: SetUnion<KeySet>,
epoch: Max<Epoch>,
}
```
Uses `#[derive(Lattice)]` for the `lattices` library `Pair` lattice.
Also contains some cleanup in the `lattices` crate.
> feat(lattices_macro): add `#[derive(Lattice)]` derive macros, fix #1247

- datastores/gossip_kv/server/main.rs
- datastores/gossip_kv/server/model.rs
There were three options I tried here.
1. We could add another `state()` for the user table and `demux` requests over the `user` and `system` state. I have tried this, and it has led to significant, ugly code duplication.
2. Use [Mingwei's lattice macro](https://github.com/hydro-project/hydroflow/commit/b3d01c20cae2335a3da2c02343debe677f17786b) - seems like an ideal use case for the lattice since the requirements essentially call for a glorified `Pair<>`. However, there's no way to "project" lattice members out and use them in joins. Mingwei has [created an issue for this](https://github.com/hydro-project/hydroflow/issues/1263).
3. Add another nesting level with `MapUnionHashMap<Namespace, ...>` - which is what this PR does.
> feat(anna): Added support for user tables

- variadics/src/lib.rs
Depends on #1241
This isn't needed for the current GHT implementation, but is useful in general
> feat(variadics): add `iter_any_ref` and `iter_any_mut` to `VariadicsExt`

- datastores/gossip_kv/protocol/lib.rs
- datastores/gossip_kv/server/main.rs
These changes separate the server logic from the networking logic, allowing the server logic to be tested with high fidelity in a unit test.  The changes allow for an abstract replacement of `SocketAddr`, which can be used for deterministic testing of more complex scenarios in unit tests.
The first feature to use these testing capabilities is concurrent writes to the same key at the same tick, which should result in multiple values being returned from a `Get`.
> feat(anna): Deterministic testing for L0 server (and also, return multiple values for concurrent writes)

- hydroflow/tests/compile-fail/surface_demux_badclosure.stderr
- hydroflow/tests/compile-fail/surface_demuxenum_notenum.stderr
- hydroflow/tests/compile-fail/surface_demuxenum_port_extra.stderr
- hydroflow/tests/compile-fail/surface_demuxenum_port_missing.stderr
- hydroflow/tests/compile-fail/surface_demuxenum_wrongenum.stderr
- hydroflow/tests/compile-fail/surface_demuxenum_wrongfields_1.stderr
- hydroflow/tests/compile-fail/surface_demuxenum_wrongfields_2.stderr
- hydroflow/tests/compile-fail/surface_fold_keyed_generics_bad.rs.ignore
- hydroflow/tests/compile-fail/surface_partition_badclosure.stderr
- hydroflow/tests/compile-fail/surface_source_interval_badarg.stderr
- hydroflow_lang/src/graph/hydroflow_graph.rs
- hydroflow_lang/src/graph/mod.rs
- hydroflow_lang/src/graph/ops/demux.rs
- hydroflow_lang/src/graph/ops/demux_enum.rs
- hydroflow_lang/src/graph/ops/mod.rs
- hydroflow_lang/src/graph/ops/partition.rs
- hydroflow_lang/src/graph/ops/source_json.rs
- hydroflow_lang/src/graph/ops/source_stdin.rs
Inspired by fixing the spans in `demux_enum` in #1271
* re-span `#root` to `op_span` for better diagnostics
* use better span `func.inputs` in `demux` and `demux_enum`
* clippy fixups in `source_json`, `source_stdin`
* fix #1201 (for the most part)
> refactor(hydroflow_lang): improve diagnostics by re-spanning `#root`

- Cargo.lock
- datastores/gossip_kv/Cargo.toml
- datastores/gossip_kv/protocol/lib.rs
- datastores/gossip_kv/protocol/membership.rs
- datastores/gossip_kv/server/main.rs
- datastores/gossip_kv/server/membership.rs
- datastores/gossip_kv/server/server.rs
- datastores/gossip_kv/server/util.rs
* Added a member metadata type to the protocol.
* Uses JSON serialization for now to keep things human-readable.
* Some clean-up - server main.rs doesn't contain the server or the server unit tests. It is a slim layer that limits responsibility to parsing command-line arguments and wiring network I/O. Business logic and tests moved to `server.rs.`
> feat(anna): Server node adds itself to sys/members on start-up

- docs/docs/hydroflow_plus/quickstart/distributed.mdx
- docs/docs/hydroflow_plus/quickstart/structure.mdx
- docs/src/util.ts
- template/hydroflow_plus/flow/src/first_ten.rs
Also fix a bug in `docs/src/util.ts:getLines()` that would cut off the beginning of lines
> docs(hydroflow_plus): update docs for hydroflow plus, pull code from template for first two examples #1012

- datastores/gossip_kv/server/lattices/mod.rs
- datastores/gossip_kv/server/main.rs
BoundedSetLattice will be used to track infection status for a feedback-counter-based gossip implementation.
> feat(anna): Added a BoundedSetLattice Implementation.

- variadics/src/lib.rs
Renames some traits, but not a breaking change since there hasn't been a release that includes those traits.
> feat(variadics): add traits for dealing with variadics of references

- Cargo.lock
- hydro_deploy/core/Cargo.toml
- hydro_deploy/core/src/hydroflow_crate/build.rs
- hydro_deploy/core/src/hydroflow_crate/mod.rs
- hydro_deploy/core/src/hydroflow_crate/service.rs
- hydro_deploy/core/src/lib.rs
- hydro_deploy/core/src/localhost/mod.rs
- hydro_deploy/core/src/ssh.rs
- hydro_deploy/hydro_cli/Cargo.toml
- hydro_deploy/hydro_cli/src/lib.rs
* Replace mystery tuple with new `struct BuildOutput`
* Replace `Mutex` and `Arc`-infested `HashMap` with `memo-map` crate, greatly simplifying build cache typing
* Remove redundant build caching in `HydroflowCrateService`, expose and use cache parameters as `BuildParams`
* Remove `once_cell` and `async-once-cell` dependencies, use `std`'s `OnceLock`
* Add `Failed to execute command: {}` context to `perf` error message
* Cleanup some repeated `format!` expressions
> refactor(hydro_deploy): build cache cleanup

- CONTRIBUTING.md
- README.md
- docs/docs/deploy/your-first-deploy.md
- docs/docs/hydroflow/concepts/index.md
- docs/docs/hydroflow/quickstart/example_1_simplest.mdx
- docs/docs/hydroflow/quickstart/example_7_networking.mdx
- docs/docs/hydroflow/quickstart/setup.md
- docs/docs/hydroflow_plus/index.mdx
- docs/docs/hydroflow_plus/quickstart/index.mdx
- docs/docs/hydroflow_plus/quickstart/structure.mdx
- docs/src/pages/playground.js
- template/hydroflow/README.md
- template/hydroflow_plus/README.md
> docs: update cargo-generate commands, say to run `rustup update` to ensure nightly rust is installed

- hydro_deploy/core/src/hydroflow_crate/mod.rs
- hydro_deploy/core/src/hydroflow_crate/service.rs
- hydro_deploy/core/src/lib.rs
- hydro_deploy/core/src/localhost/launched_binary.rs
- hydro_deploy/core/src/ssh.rs
- hydro_deploy/core/src/util.rs
- hydro_deploy/hydro_cli/src/lib.rs
- hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs
`std::sync::Mutex` should be used as long as the lock is not held across any `.await` yield points.
STACK: #1338 ~~#1341~~
> refactor(hydro_deploy)!: replace some uses of `tokio::sync::RwLock` with `std::sync::Mutex` #430 (3/3)

- Cargo.lock
- hydro_deploy/core/Cargo.toml
- hydro_deploy/core/src/hydroflow_crate/mod.rs
- hydro_deploy/core/src/hydroflow_crate/service.rs
- hydro_deploy/core/src/lib.rs
- hydro_deploy/core/src/localhost/launched_binary.rs
- hydro_deploy/core/src/ssh.rs
- hydro_deploy/core/src/util.rs
- hydro_deploy/hydro_cli/Cargo.toml
- hydro_deploy/hydro_cli/src/lib.rs
- hydro_deploy/hydroflow_plus_cli_integration/Cargo.toml
- hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs
- hydroflow_plus_test/src/cluster/many_to_many.rs
- hydroflow_plus_test/src/cluster/simple_cluster.rs
- hydroflow_plus_test/src/distributed/first_ten.rs
- hydroflow_plus_test/src/distributed/networked.rs
- template/hydroflow_plus/flow/Cargo.toml
- template/hydroflow_plus/flow/src/first_ten_distributed.rs
> refactor(hydro_deploy)!: replace `async-channel` with `tokio::sync::mpsc::unbounded_channel`

- hydro_deploy/core/src/custom_service.rs
- hydro_deploy/core/src/hydroflow_crate/ports.rs
- hydro_deploy/core/src/hydroflow_crate/service.rs
- hydro_deploy/hydro_cli/src/lib.rs
- hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs
> refactor(hydro_deploy)!: make `HydroflowSource`, `HydroflowSink` traits use `&self` interior mutability to remove `RwLock` wrappings

- hydro_deploy/core/src/azure.rs
- hydro_deploy/core/src/custom_service.rs
- hydro_deploy/core/src/deployment.rs
- hydro_deploy/core/src/gcp.rs
- hydro_deploy/core/src/hydroflow_crate/mod.rs
- hydro_deploy/core/src/hydroflow_crate/ports.rs
- hydro_deploy/core/src/hydroflow_crate/service.rs
- hydro_deploy/core/src/lib.rs
- hydro_deploy/core/src/localhost/mod.rs
- hydro_deploy/hydro_cli/src/lib.rs
- hydro_deploy/hydroflow_plus_cli_integration/src/deploy.rs
- hydroflow_plus_test/examples/compute_pi.rs
- hydroflow_plus_test/examples/first_ten_distributed.rs
- hydroflow_plus_test/examples/map_reduce.rs
- hydroflow_plus_test/examples/perf_compute_pi.rs
- hydroflow_plus_test/examples/simple_cluster.rs
> refactor(hydro_deploy)!: make `Host` trait use `&self` interior mutability to remove `RwLock` wrappings #430

- hydro_deploy/core/src/custom_service.rs
- hydro_deploy/core/src/deployment.rs
- hydro_deploy/core/src/hydroflow_crate/service.rs
- hydro_deploy/core/src/lib.rs
#430 but still has `RwLock` wrapping
Depends on #1347
> refactor(hydro_deploy)!: make `Service::collect_resources` take `&self` instead of `&mut self`

- .cargo/config.toml
MacOS uses Rust lld, avoids this error: ld: Assertion failed: (name.size() <= maxLength), function makeSymbolStringInPlace
> fix: MacOS lld compilation failure

- hydro_deploy/core/src/terraform.rs
fix(hydro_deploy): avoid Terraform crashing on empty provider block
> fix(hydro_deploy): avoid Terraform crashing on empty provider block

- Cargo.lock
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/Cargo.toml
The original types prevented usage in cluster-to-cluster communication.
> fix(hydroflow_plus): overly restrictive input types for `send_bincode_interleaved`

- .gitignore
- Cargo.lock
- hydro_deploy/core/Cargo.toml
- hydro_deploy/core/src/azure.rs
- hydro_deploy/core/src/deployment.rs
- hydro_deploy/core/src/gcp.rs
- hydro_deploy/hydro_cli/src/lib.rs
- hydroflow_plus_test/examples/compute_pi.rs
- hydroflow_plus_test/examples/first_ten_distributed.rs
- hydroflow_plus_test/examples/map_reduce.rs
- hydroflow_plus_test/examples/perf_compute_pi.rs
- hydroflow_plus_test/examples/simple_cluster.rs
- template/hydroflow_plus/flow/examples/first_ten_distributed_gcp.rs
Adds new method `Deployment::AzureHost`
BREAKING CHANGE: Changes syntax for `Deployment::GcpComputeEngineHost`
> refactor(hydro_deploy)!: use `buildstructor` to handle excessive `Deployment` method arguments, fix #1364

- Cargo.lock
- hydro_deploy/core/Cargo.toml
- hydro_deploy/core/src/hydroflow_crate/perf_options.rs
- hydro_deploy/core/src/hydroflow_crate/service.rs
- hydro_deploy/core/src/localhost/mod.rs
- hydro_deploy/core/src/ssh.rs
- hydroflow_plus_test/examples/perf_compute_pi.rs
Depends on #1370
Fixes #1365
BREAKING CHANGE: changes PerfConfig creation and probably other stuff
> refactor(hydro_deploy)!: end-to-end flamegraph generation, fix #1365

- hydroflow/tests/snapshots/surface_cross_singleton__basic@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_cross_singleton__basic@graphvis_mermaid.snap
- hydroflow/tests/surface_cross_singleton.rs
- hydroflow_lang/src/graph/ops/cross_singleton.rs
- hydroflow_lang/src/graph/ops/mod.rs
This operator is necessary to eliminate performance bottlenecks in Paxos where cross-products result in unnecessary cloning and lack of short-circuit behavior results in values being cloned out of the internal state of `reduce_keyed`.
> feat(hydroflow): add `cross_singleton` operator

- stageleft/src/lib.rs
Previously, a `RuntimeData` could be spliced in any context even if its data type may not be valid under the required `'a` lifetime constraint. This fixed that typing bug.
Soon, we should have regression testing for this via trybuild.
> fix(stageleft): typing hole when splicing `RuntimeData`

- hydroflow_plus/src/builder/built.rs
- hydroflow_plus/src/builder/deploy.rs
- hydroflow_plus/src/ir.rs
- hydroflow_plus/src/persist_pullup.rs
- hydroflow_plus/src/profiler.rs
- hydroflow_plus/src/properties.rs
- hydroflow_plus/src/stream.rs
Cloning was unsafe because values behind a `Rc<RefCell<...>>` in the case of tee would be entangled with the old IR.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1404).
* #1405
* #1398
* __->__ #1404
> fix(hydroflow_plus): rewrite IR in place to avoid stack overflow and disable cloning

- hydroflow_lang/src/graph/ops/state.rs
BREAKING CHANGE: `state()` behaves slightly differently now
Picked out of #1406
> feat(hydroflow_lang)!: change `state()` to output a stream of only de-duplicated items

- hydro_deploy/core/src/deployment.rs
- hydro_deploy/core/src/hydroflow_crate/build.rs
- hydro_deploy/core/src/hydroflow_crate/service.rs
- hydro_deploy/core/src/progress.rs
- hydro_deploy/core/src/ssh.rs
- hydro_deploy/core/src/terraform.rs
Now, when a group only has a single active task, we skip printing a line for the group itself and instead collapse its information into the line for the inner task (recursively as necessary). This allows us to show more fine grained progress without overflowing the console.
> feat(hydro_deploy): improve progress UX by collapsing nested groups

- clippy.toml
- hydro_deploy/hydroflow_plus_deploy/src/runtime.rs
- hydroflow/src/scheduled/port.rs
- hydroflow_plus/src/lib.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/compute_pi.rs
- hydroflow_plus_test/src/cluster/map_reduce.rs
- relalg/src/lib.rs
- website_playground/src/lib.rs
BREAKING CHANGE: changes some pub-facing names. Behaviors are the same.
> style!: rename some `CLI`->`Deploy`, decapitalize acronym names

- hydroflow_plus/src/builder/mod.rs
- hydroflow_plus/src/cycle.rs
- hydroflow_plus/src/ir.rs
- hydroflow_plus/src/persist_pullup.rs
- hydroflow_plus/src/profiler.rs
- hydroflow_plus/src/properties.rs
- hydroflow_plus/src/snapshots/hydroflow_plus__persist_pullup__tests__persist_pullup_behind_tee-2.snap
- hydroflow_plus/src/snapshots/hydroflow_plus__persist_pullup__tests__persist_pullup_behind_tee.snap
- hydroflow_plus/src/snapshots/hydroflow_plus__persist_pullup__tests__persist_pullup_behind_tee@surface_graph_0.snap
- hydroflow_plus/src/snapshots/hydroflow_plus__persist_pullup__tests__persist_pullup_through_map-2.snap
- hydroflow_plus/src/snapshots/hydroflow_plus__persist_pullup__tests__persist_pullup_through_map.snap
- hydroflow_plus/src/snapshots/hydroflow_plus__persist_pullup__tests__persist_pullup_through_map@surface_graph_0.snap
- hydroflow_plus/src/snapshots/hydroflow_plus__profiler__tests__profiler_wrapping_all_operators-2.snap
- hydroflow_plus/src/snapshots/hydroflow_plus__profiler__tests__profiler_wrapping_all_operators.snap
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/compute_pi.rs
- hydroflow_plus_test/src/cluster/map_reduce.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/simple_cluster.rs
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos__tests__paxos_ir.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__simple_cluster__tests__simple_cluster.snap
- hydroflow_plus_test_local/src/local/chat_app.rs
- hydroflow_plus_test_local/src/local/compute_pi.rs
- hydroflow_plus_test_local/src/local/count_elems.rs
- hydroflow_plus_test_local/src/local/graph_reachability.rs
- hydroflow_plus_test_local/src/local/negation.rs
- hydroflow_plus_test_local/src/local/snapshots/hydroflow_plus_test_local__local__graph_reachability__tests__reachability@graphvis_dot.snap
- hydroflow_plus_test_local/src/local/snapshots/hydroflow_plus_test_local__local__graph_reachability__tests__reachability@graphvis_mermaid.snap
- hydroflow_plus_test_local/src/local/teed_join.rs
Now, by default streams exist at a "top-level" where there are no ticks and operators run over the entire collection. To perform iterative computations, developers must explicitly entire a tick domain (using `tick_batch`), and return to the outer domain (using `all_ticks`).
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1421).
* #1427
* #1425
* __->__ #1421
> feat(hydroflow_plus)!: refactor API to have no-tick semantics by default

- .idea/hydroflow.iml
- Cargo.lock
- datastores/gossip_kv/Cargo.toml
- datastores/gossip_kv/protocol/lib.rs
- datastores/gossip_kv/protocol/model.rs
- datastores/gossip_kv/server/lattices/mod.rs
- datastores/gossip_kv/server/main.rs
- datastores/gossip_kv/server/server.rs
- datastores/gossip_kv/server/util.rs
This change implements a blind gossip protocol where the gossipers don't receive (or care to receive) responses from the systems they gossip with. 
It also adds a deterministic testing framework for testing gossip.
Once request-reply is added, it can stop being blind.
> feat(anna): blind gossip

- hydro_deploy/core/src/localhost/mod.rs
- hydro_deploy/core/src/ssh.rs
- hydroflow_plus_test/examples/perf_compute_pi.rs
When kernel stacks are included, the DWARF traces can become corrupted / overflown leading to flamegraphs with broken parents. We only are interested in usermode, anyways, and can measure I/O overhead through other methods.
> fix(hydro_deploy): only record usermode events in perf

- docs/README.md
The wasp-pack build command must be run from the `website-playground` directory.
> docs: Update README.md for docs website

- hydro_deploy/core/src/deployment.rs
- hydro_deploy/hydroflow_plus_deploy/src/deploy.rs
- hydro_deploy/hydroflow_plus_deploy/src/deploy_runtime.rs
- hydro_deploy/hydroflow_plus_deploy/src/runtime.rs
- hydro_deploy/hydroflow_plus_deploy/src/trybuild.rs
- hydroflow_plus/src/builder/built.rs
- hydroflow_plus/src/builder/deploy.rs
- hydroflow_plus/src/builder/mod.rs
- hydroflow_plus/src/deploy/graphs.rs
- hydroflow_plus/src/deploy/mod.rs
- hydroflow_plus/src/ir.rs
- hydroflow_plus/src/location.rs
- hydroflow_plus/src/persist_pullup.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/examples/first_ten_distributed.rs
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__compute_pi__tests__compute_pi_ir.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__many_to_many__tests__many_to_many.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__map_reduce__tests__map_reduce_ir.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__simple_cluster__tests__simple_cluster.snap
- hydroflow_plus_test/src/distributed/first_ten.rs
- hydroflow_plus_test/src/distributed/snapshots/hydroflow_plus_test__distributed__first_ten__tests__first_ten_distributed.snap
- stageleft/src/type_name.rs
This is a key step towards being able to unit-test HF+ graphs, by being able to have controlled inputs. Outputs next.
> feat(hydroflow_plus): add API for external network inputs

- hydroflow_plus/src/singleton.rs
Discovered during a live-coding demo, we only had it for optionals before.
> fix(hydroflow_plus): add missing `sample_every` for singletons

- .github/workflows/ci.yml
- .vscode/settings.json
- Cargo.lock
- hydroflow_plus/Cargo.toml
- hydroflow_plus/src/deploy/deploy_graph.rs
- hydroflow_plus/src/deploy/deploy_runtime.rs
- hydroflow_plus/src/deploy/mod.rs
- hydroflow_plus_test/Cargo.toml
- hydroflow_plus_test/examples/paxos.rs
Previously, the default `deploy` feature would pull in Hydro Deploy and its transitive native dependencies.
Also sets up `examples/paxos.rs` with CLI flags to deploy to GCP.
> fix(hydroflow_plus): adjust default features to allow compilation to musl targets

- variadics/Cargo.toml
- variadics/src/lib.rs
- variadics/src/variadic_collections.rs
adds a number of features:
- collection types for variadics (sets, multisets) that allow search via RefVars (variadic of refs)
- into_option (convert a variadic to a variadic of options)
- into_vec (convert a variadic to a variadic of vecs)
> feat: additions to variadics including collection types

- docs/docs/hydroflow_plus/clusters.mdx
- hydroflow_plus/src/builder/mod.rs
- hydroflow_plus/src/location.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/map_reduce.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/simple_cluster.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1468).
* #1471
* __->__ #1468
> refactor(hydroflow_plus)!: move `self_id` and `members` to be APIs on cluster instead of builder

- Cargo.lock
- variadics/Cargo.toml
- variadics/src/lib.rs
- variadics/src/variadic_collections.rs
adds a number of features:
collection types for variadics (sets, multisets) that allow search via RefVars (variadic of refs)
into_option (convert a variadic to a variadic of options)
into_vec (convert a variadic to a variadic of vecs)
> feat(variadics): additions to variadics including collection types

- datastores/gossip_kv/server/Dockerfile
- datastores/gossip_kv/server/README.md
- datastores/gossip_kv/server/baseimage.Dockerfile
- datastores/gossip_kv/server/deployment/local/deployment.yaml
- datastores/gossip_kv/server/deployment/local/service.yaml
- datastores/gossip_kv/server/deployment/patch.yaml
- datastores/gossip_kv/server/main.rs
When I started, I was using the published Hydroflow. I have since switched to using local hydroflow, which means the Dockerfile needs to be updated for the build to work correctly. This posed a more significant challenge than expected, primarily because of disk space issues, which have been sorted out.
> feat(anna): Get minikube working

- .idea/hydroflow.iml
- Cargo.lock
- datastores/gossip_kv/Cargo.toml
- datastores/gossip_kv/Makefile
- datastores/gossip_kv/cli/Dockerfile
- datastores/gossip_kv/cli/main.rs
- datastores/gossip_kv/server/Dockerfile
- datastores/gossip_kv/server/README.md
- datastores/gossip_kv/server/config/default.toml
- datastores/gossip_kv/server/config/mod.rs
- datastores/gossip_kv/server/config/static/default.toml
- datastores/gossip_kv/server/deployment/local/objects.yaml
- datastores/gossip_kv/server/main.rs
- datastores/gossip_kv/server/server.rs
Editing a k8s ConfigMap now cause configuration to be reloaded across all pods where the server is running. 
```
│ 2024-10-04T01:43:21.722805Z TRACE run_async:run_available_async:run_stratum{tick=1 stratum=0}: gossip_server::config: Event: Event { kind: Modify(Name(To)), paths: ["/config/dynamic/..data"], attr:tracker: Some(1307780), attr:fla
│ 2024-10-04T01:43:21.722888Z TRACE run_async:run_available_async:run_stratum{tick=1 stratum=0}: gossip_server: Settings updated. Reloading seed nodes 
│ 2024-10-04T01:43:21.723242Z TRACE run_async:run_available_async:run_stratum{tick=1 stratum=0}: hydroflow::scheduled::graph: return=true 
│ 2024-10-04T01:43:21.723260Z TRACE run_async:run_available_async:next_stratum{current_tick_only=false}: hydroflow::scheduled::graph: Starting `next_stratum` call. …
```
> feat(anna): Hot reloadable dynamic config.

- datastores/gossip_kv/Makefile
- datastores/gossip_kv/cli/Dockerfile
- datastores/gossip_kv/server/Dockerfile
- datastores/gossip_kv/server/README.md
- datastores/gossip_kv/server/config/static/default.toml
- datastores/gossip_kv/server/deployment/local/objects.yaml
- datastores/gossip_kv/server/deployment/local/updated_seed_node_config.yaml
- datastores/gossip_kv/server/main.rs
- datastores/gossip_kv/server/membership.rs
- datastores/gossip_kv/server/server.rs
Summary of Changes:
1. Some cleanup/bug fixes with docker files.
2. Install `dig` on CLI to test DNS
3. Fixed gossip ports everywhere - using the wrong port was annoying.
4. Cluster tear-down is much faster - reduced pod termination wait from 30s (default) to 5s.
5. New static config for three servers - not planning to automate this now.
6. Gossip trigger timer wired in - this was earlier separated out for deterministic testing.
7. Not randomizing host-names at the moment - this was making testing difficult, although I think this does help in production with restarts and such.
8. Gossip assumed > 0 available peers - fixed that issue.
> feat(anna): Multi-server Anna Working Locally

- datastores/gossip_kv/Makefile
- datastores/gossip_kv/server/deployment/aws/terraform/.gitignore
- datastores/gossip_kv/server/deployment/aws/terraform/main.tf
- datastores/gossip_kv/server/deployment/aws/terraform/outputs.tf
- datastores/gossip_kv/server/deployment/aws/terraform/terraform.tf
- datastores/gossip_kv/server/deployment/aws/terraform/variables.tf
- datastores/gossip_kv/server/deployment/local/objects.yaml
Terraform scripts are used to create EKS, ECR, and K8s resources in AWS.
> feat(anna): Deploy to AWS

- Cargo.lock
- hydroflow_datalog_core/Cargo.toml
The latest Rust Sitter drops the dependency on `tree-sitter-cli`, which eliminates many transitive dependencies.
> chore(hydroflow_datalog): update rust-sitter

- hydroflow/src/util/tcp.rs
consolidate into one task to prevent races
> fix(hydroflow): cleanup temp tcp networking code, fix race condition fix #1458

- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1489).
* #1514
* #1493
* #1492
* __->__ #1489
> refactor(paxos): minor additional cleanups

- hydroflow_plus/src/cycle.rs
- hydroflow_plus/src/lib.rs
- hydroflow_plus/src/location.rs
- hydroflow_plus/src/singleton.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/paxos_kv.rs
Now, when the location is a top-level `Process` or `Cluster` that corresponds to a `NoTick`, and for streams inside a tick we wrap the location type (e.g. `Tick<Process<...>>`). This simplifies type signatures for a lot of our example code.
> refactor(hydroflow_plus)!: fold `Tick` vs `NoTick` into the location type parameter

- hydroflow/tests/snapshots/surface_cross_singleton__union_defer_tick@graphvis_dot.snap
- hydroflow/tests/snapshots/surface_cross_singleton__union_defer_tick@graphvis_mermaid.snap
- hydroflow/tests/surface_cross_singleton.rs
- hydroflow_lang/src/graph/ops/cross_singleton.rs
Adds the minimal reproducer test from @shadaj
Note this may have negative performance implications, as the singleton value now is stored in the state API (heap) instead of locally
> fix(hydroflow_lang): `cross_singleton()` forgot value if multiple runs in a tick, fix #1518

- hydroflow_plus/src/lib.rs
- hydroflow_plus/src/optional.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/paxos_kv.rs
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__compute_pi__tests__compute_pi_ir.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__compute_pi__tests__compute_pi_ir@surface_graph_1.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
Also renames `cross_singleton` to `zip` when both sides are singleton-like.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1526).
* #1527
* __->__ #1526
> refactor(hydroflow_plus)!: dedup signatures for `Singleton` and `Optional`

- hydroflow_plus/src/builder/mod.rs
- hydroflow_plus/src/ir.rs
- hydroflow_plus/src/optional.rs
- hydroflow_plus/src/singleton.rs
- hydroflow_plus/src/stream.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1540).
* #1543
* #1542
* #1541
* __->__ #1540
> refactor(hydroflow_plus): deduplicate some error messages and drop unused `Interval` IR node

- hydroflow_plus/src/builder/mod.rs
- hydroflow_plus/src/ir.rs
- hydroflow_plus/src/location/mod.rs
- hydroflow_plus/src/location/tick.rs
- hydroflow_plus/src/optional.rs
- hydroflow_plus/src/rewrites/persist_pullup.rs
- hydroflow_plus/src/rewrites/properties.rs
- hydroflow_plus/src/singleton.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/compute_pi.rs
- hydroflow_plus_test/src/cluster/map_reduce.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/paxos_kv.rs
- hydroflow_plus_test/src/cluster/simple_cluster.rs
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__compute_pi__tests__compute_pi_ir.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__compute_pi__tests__compute_pi_ir@surface_graph_0.snap
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydroflow_plus_test/src/cluster/two_pc.rs
- hydroflow_plus_test_local/src/local/chat_app.rs
- hydroflow_plus_test_local/src/local/compute_pi.rs
- hydroflow_plus_test_local/src/local/count_elems.rs
- hydroflow_plus_test_local/src/local/negation.rs
- hydroflow_plus_test_local/src/local/teed_join.rs
Previously, each location had a (semantic) global clock that drives ticks, and so all streams in a tick domain were all in the same atomic block. For future optimizations, we'd like developers to be able to place streams on the same location into different clocks to eliminate synchronization between them, which in turn would allow the computations in those separate clocks to be potentially decoupled across machines.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1550).
* #1554
* #1551
* __->__ #1550
> feat(hydroflow_plus)!: add an explicit API for creating tick contexts

- hydroflow_plus/src/location/external_process.rs
- hydroflow_plus/src/location/mod.rs
- hydroflow_plus/src/location/tick.rs
- hydroflow_plus/src/optional.rs
- hydroflow_plus/src/singleton.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/paxos_kv.rs
When looking at a prefix in an IDE, the location type argument is generally more useful.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1551).
* #1554
* __->__ #1551
> refactor(hydroflow_plus)!: location type parameter before boundedness

- docs/docs/hydroflow_plus/quickstart/clusters.mdx
- docs/docs/hydroflow_plus/quickstart/first-dataflow.mdx
- hydroflow_plus/src/builder/built.rs
- hydroflow_plus/src/builder/deploy.rs
- hydroflow_plus/src/builder/mod.rs
- hydroflow_plus/src/rewrites/profiler.rs
- hydroflow_plus/src/rewrites/properties.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/examples/compute_pi.rs
- hydroflow_plus_test/examples/first_ten_distributed.rs
- hydroflow_plus_test/examples/map_reduce.rs
- hydroflow_plus_test/examples/paxos.rs
- hydroflow_plus_test/examples/perf_compute_pi.rs
- hydroflow_plus_test/examples/simple_cluster.rs
- hydroflow_plus_test/examples/two_pc.rs
- hydroflow_plus_test/src/cluster/compute_pi.rs
- hydroflow_plus_test/src/cluster/map_reduce.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test_local/src/local/chat_app.rs
- hydroflow_plus_test_local/src/local/compute_pi.rs
- hydroflow_plus_test_local/src/local/count_elems.rs
- hydroflow_plus_test_local/src/local/first_ten.rs
- hydroflow_plus_test_local/src/local/graph_reachability.rs
- hydroflow_plus_test_local/src/local/negation.rs
- hydroflow_plus_test_local/src/local/teed_join.rs
- template/hydroflow_plus/examples/first_ten.rs
- template/hydroflow_plus/examples/first_ten_distributed.rs
- template/hydroflow_plus/examples/first_ten_distributed_gcp.rs
- template/hydroflow_plus/src/first_ten_distributed.rs
This also changes the behavior of `with_default_optimize` to be terminal, if users want to apply optimizations after these they should explicitly invoke the optimizations.
> feat(hydroflow_plus)!: implicitly apply default optimizations

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- docs/src/theme/prism-include-languages.js
- hydroflow_macro/build.rs
Main breaking change is MDX parsing, which trips up on unescaped `<` in the generated docs, so we have to adjust the generator logic.
> chore(docs): upgrade to Docusaurus v3

- RELEASING.md
Some rephrasing, extra details, after working thru with Rohit.
> ci: Update RELEASING.md

- Cargo.lock
- hydroflow_plus/Cargo.toml
- hydroflow_plus/src/builder/built.rs
- hydroflow_plus/src/builder/compiled.rs
- hydroflow_plus/src/builder/deploy.rs
- hydroflow_plus/src/builder/mod.rs
- hydroflow_plus/src/cycle.rs
- hydroflow_plus/src/ir.rs
- hydroflow_plus/src/location/cluster.rs
- hydroflow_plus/src/location/external_process.rs
- hydroflow_plus/src/location/process.rs
- hydroflow_plus/src/runtime_context.rs
- hydroflow_plus/src/staging_util.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus/tests/compile-fail/send_bincode_lifetime.rs
- hydroflow_plus/tests/compile-fail/send_bincode_lifetime.stderr
- hydroflow_plus/tests/compile_fail.rs
- hydroflow_plus_test/examples/first_ten_distributed.rs
- hydroflow_plus_test/src/distributed/first_ten.rs
- stageleft/src/lib.rs
- template/hydroflow_plus/examples/first_ten_distributed.rs
- template/hydroflow_plus/examples/first_ten_distributed_gcp.rs
- template/hydroflow_plus/src/first_ten_distributed.rs
Our lifetimes were accidentally made covariant when the lifetime `'a` was removed from the process/cluster tag type. This fixes that typing hole, and also loosens some restrictions on the lifetime of deploy environments.
> fix(hydroflow_plus): restrict lifetime parameters to be actually invariant

- hydroflow_plus/src/builder/compiled.rs
- hydroflow_plus/src/builder/deploy.rs
- hydroflow_plus/src/builder/mod.rs
- hydroflow_plus/src/deploy/deploy_graph.rs
- hydroflow_plus/src/deploy/macro_runtime.rs
- hydroflow_plus/src/deploy/trybuild.rs
- hydroflow_plus/src/lib.rs
- hydroflow_plus_test_local/src/local/chat_app.rs
- hydroflow_plus_test_local/src/local/count_elems.rs
- hydroflow_plus_test_local/src/local/graph_reachability.rs
- hydroflow_plus_test_local/src/local/negation.rs
- hydroflow_plus_test_local/src/local/teed_join.rs
- template/hydroflow_plus/src/first_ten_distributed.rs
Reduces namespace pollution when wildcard-importing `hydroflow_plus`.
> refactor(hydroflow_plus)!: don't re-export all of `hydroflow`

- hydroflow_lang/src/graph/ops/chain.rs
- hydroflow_lang/src/graph/ops/mod.rs
- hydroflow_plus/src/ir.rs
- hydroflow_plus/src/optional.rs
- hydroflow_plus/src/rewrites/persist_pullup.rs
- hydroflow_plus/src/singleton.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/paxos_kv.rs
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydroflow_plus_test_local/src/local/graph_reachability.rs
- hydroflow_plus_test_local/src/local/snapshots/hydroflow_plus_test_local__local__graph_reachability__tests__reachability@graphvis_dot.snap
- hydroflow_plus_test_local/src/local/snapshots/hydroflow_plus_test_local__local__graph_reachability__tests__reachability@graphvis_mermaid.snap
Returning a `Stream` from `union` on unbounded streams was unsound, since the order of outputs is not deterministic.
> fix(hydroflow_plus)!: rename `union` to `chain` and restrict LHS to be bounded

- hydro_deploy/core/src/progress.rs
Significantly improves the appearance of Hydroflow+ logs when the terminal causes wrapping.
> feat(hydro_deploy): use regular println when no tasks are active

- docs/package-lock.json
- docs/src/pages/playground.js
Docusaurus v3 broke Mermaid in the playground due to an API change.
> fix(docs): use async API required by Mermaid v10

- Cargo.lock
- hydroflow_plus/Cargo.toml
- hydroflow_plus/src/boundedness.rs
- hydroflow_plus/src/lib.rs
- hydroflow_plus/src/location/can_send.rs
- hydroflow_plus/src/location/cluster.rs
- hydroflow_plus/src/singleton.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/compute_pi.rs
- hydroflow_plus_test/src/cluster/map_reduce.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/paxos_kv.rs
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydroflow_plus_test/src/cluster/two_pc.rs
- hydroflow_plus_test_local/src/local/graph_reachability.rs
Previously, sending data from a `Cluster` would return a stream assumed to have deterministic contents **and** ordering, which is false. This introduces another type parameter for `Stream` which tracks whether element ordering is expected to be deterministic, and restricts operators such as `fold` and `reduce` to commutative aggregations accordingly.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1568).
* #1575
* #1574
* __->__ #1568
> feat(hydroflow_plus)!: introduce an unordered variant of streams to strengthen determinism guarantees

- hydroflow_plus/src/optional.rs
- hydroflow_plus/src/stream.rs
- hydroflow_plus_test/src/cluster/mod.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/paxos_kv.rs
- hydroflow_plus_test/src/cluster/quorum.rs
- hydroflow_plus_test/src/cluster/request_response.rs
- hydroflow_plus_test/src/cluster/snapshots/hydroflow_plus_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydroflow_plus_test_local/src/local/graph_reachability.rs
- stageleft/src/type_name.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1583).
* #1584
* __->__ #1583
> refactor(paxos): generalize quorum logic

- hydroflow_plus/src/deploy/trybuild.rs
- hydroflow_plus/src/lib.rs
- hydroflow_plus/src/location/mod.rs
- hydroflow_plus_test/src/cluster/paxos.rs
- hydroflow_plus_test/src/cluster/paxos_bench.rs
- hydroflow_plus_test/src/cluster/paxos_kv.rs
- hydroflow_plus_test/src/cluster/quorum.rs
- hydroflow_plus_test/src/cluster/request_response.rs
- hydroflow_plus_test/src/distributed/first_ten.rs
- hydroflow_plus_test_local/src/local/chat_app.rs
- hydroflow_plus_test_local/src/local/compute_pi.rs
- hydroflow_plus_test_local/src/local/count_elems.rs
- hydroflow_plus_test_local/src/local/first_ten.rs
- hydroflow_plus_test_local/src/local/graph_reachability.rs
- hydroflow_plus_test_local/src/local/negation.rs
- hydroflow_plus_test_local/src/local/teed_join.rs
Some re-exports are only useful for the macro-based API, which is deprecated in favor of trybuild anyways.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1589).
* #1590
* __->__ #1589
> refactor(hydroflow_plus)!: further reduce namespace pollution

- Cargo.lock
- hydroflow/tests/snapshots/surface_examples__example_2_simple_1.snap
- hydroflow/tests/snapshots/surface_examples__example_2_simple_2.snap
- hydroflow/tests/snapshots/surface_examples__example_3_stream.snap
- hydroflow/tests/snapshots/surface_examples__example_4_neighbors.snap
- hydroflow/tests/snapshots/surface_examples__example_5_reachability.snap
- hydroflow/tests/snapshots/surface_examples__example_6_unreachability.snap
- hydroflow/tests/snapshots/surface_examples__example_surface_flows_1_basic.snap
- hydroflow/tests/snapshots/surface_examples__example_surface_flows_2_varname.snap
- hydroflow/tests/snapshots/surface_examples__example_surface_flows_3_ports.snap
- hydroflow/tests/snapshots/surface_examples__example_surface_flows_4_context.snap
- hydroflow/tests/snapshots/surface_examples__example_syntax_hello_world.snap
- hydroflow/tests/snapshots/surface_examples__example_syntax_input.snap
- hydroflow_plus/Cargo.toml
- hydroflow_plus/src/lib.rs
- hydroflow_plus/src/rewrites/persist_pullup.rs
question is whether to pull `match_box` into the monorepo or leave it in https://github.com/hydro-project/matchbox
> refactor(hydroflow_plus): use `match_box` macro to compile on stable

- .cargo/config.toml
- .github/workflows/ci.yml
- Cargo.lock
- hydroflow/Cargo.toml
- hydroflow/src/lib.rs
- hydroflow_datalog/Cargo.toml
- hydroflow_datalog/src/lib.rs
- hydroflow_datalog_core/Cargo.toml
- hydroflow_datalog_core/src/lib.rs
- hydroflow_lang/Cargo.toml
- hydroflow_lang/build.rs
- hydroflow_lang/src/diagnostic.rs
- hydroflow_lang/src/graph/hydroflow_graph.rs
- hydroflow_lang/src/lib.rs
- hydroflow_lang/src/pretty_span.rs
- hydroflow_macro/Cargo.toml
- hydroflow_macro/build.rs
- hydroflow_macro/src/lib.rs
- hydroflow_plus/Cargo.toml
Previous PR (#1587) website build did not work because `panic = "abort"` is set on wasm, leading to aborts for `proc_macro2::Span::unwrap()` calls.
All tests except trybuild seem to pass on stable, WIP #1587 next
BREAKING CHANGE: replaces `hydroflow_lang::diagnostic::Diagnostic::emit` with `try_emit`
BREAKING CHANGE: removes features: `hydroflow/nightly`, `hydroflow_datalog/diagnostics`, `hydroflow_datalog_core/diagnostics`, `hydroflow_lang/diagnostics`, `hydroflow_macro/diagnostics`, `hydroflow_plus/diagnostics`.
> refactor!: use `cfg(nightly)` instead of feature, remove `-Z` flag, use `Diagnostic::try_emit`

- .github/workflows/ci.yml
stable tests will fail for now
> ci: test latest stable (instead of nightly), fix #1587

- .github/workflows/ci.yml
- hydroflow/src/declarative_macro.rs
- hydroflow/tests/surface_warnings.rs
- hydroflow_lang/src/diagnostic.rs
- hydroflow_lang/src/graph/hydroflow_graph.rs
Sets `TRYBUILD=overwrite` on stable, as the output messages will often not match `pinned-nightly`
Adds env `HYDROFLOW_EXPECT_WARNINGS=ignore` to allow warning tests to pass
> ci: fix stable tests

- README.md
- docs/docs/hydroflow/index.mdx
- docs/docs/hydroflow_plus/index.mdx
Here's a version of the README that has reasonable text with the name changes. The links will need to be updated to point to changes names for the relevant directories/files in the docs (which should be changed appropriately).
Feel free to copy this file and reject this PR, or merge this PR and rebase, as you see fit.
Mingwei: also adds basic redirects for the old paths
> docs: README.md hydroflow+ => hydro, hydroflow => DFIR, rewording

- .github/workflows/template.yml
- template/dfir/Cargo.toml
- template/hydro/Cargo.toml
Sorta undoes #1314, except the different now is the template repos have no active code in them, they're entirely tied to the `template/*` folder in this repo by this CI job. Testing is still done in this repo.
Actually updating the docs to the new repo URLs is still TODO
> ci: push templates to auxilary repos

- hydro_test/examples/paxos.rs
- hydro_test/src/cluster/bench_client.rs
- hydro_test/src/cluster/kv_replica.rs
- hydro_test/src/cluster/mod.rs
- hydro_test/src/cluster/paxos.rs
- hydro_test/src/cluster/paxos_bench.rs
- hydro_test/src/cluster/paxos_with_client.rs
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
Makes it possible to substitute Paxos with other sequencing protocols.
> refactor(paxos): disentangle KV replicas from Paxos

- Cargo.lock
- hydro_deploy/core/src/hydroflow_crate/build.rs
- hydro_lang/Cargo.toml
- hydro_lang/src/deploy/trybuild.rs
- hydro_lang/src/deploy/trybuild_rewriters.rs
- hydro_lang/src/lib.rs
- hydro_std/Cargo.toml
- hydro_std/src/lib.rs
- hydro_test/Cargo.toml
- hydro_test/src/lib.rs
- stageleft_tool/src/lib.rs
- template/hydro/Cargo.toml
- template/hydro/src/lib.rs
Previously, a rewrite would first turn `crate` into `crate::__staged`, and another would rewrite `crate::__staged` into `hydro_test::__staged`. The latter global rewrite is unnecessary because the stageleft logic already will use the full crate name when handling public types, so we drop it.
> fix(hydro_lang): use correct `__staged` path when rewriting `crate::` imports

- .github/workflows/build-cli.yml
> ci(hydro_cli): bump upload-artifact action to v4

- .github/workflows/build-cli.yml
Some of the matrices nest `target` under `platform`.
> fixup!: ci(hydro_cli): fix matrix clobbering the same artifact path

- hydro_lang/src/stream.rs
`Stream::cloned` is only really useful if the input has `&T` elements but we want `T`, so this updates the signature to do that.
> feat(hydro_lang): make `Stream::cloned` work with borrowed elements

- dfir_lang/src/graph/ops/join.rs
- dfir_lang/src/graph/ops/join_fused.rs
- dfir_lang/src/graph/ops/join_multiset.rs
- dfir_macro/build.rs
Previous code also inserted `\<` into code blocks. This fixes the original issue of unescaped `<`s by ensuring all op docs have them in `code blocks`, removes the escaping.
> docs: fix extraneous `\<` escaping introduced in #1558, fix #1614

- datastores/gossip_kv/kv/server.rs
- dfir_lang/src/graph/ops/state.rs
- dfir_lang/src/graph/ops/state_by.rs
Currently, state_by uses Default::default to instantiate the backing storage. Accepting a factory function will allow the storage to be tweaked per instance of state. Example usage: pre-allocating memory for the data structures.
> feat(dfir_lang): Allow state_by to use a factory function.

- hydro_deploy/core/src/hydroflow_crate/build.rs
`Display` for `ExitStatus` already includes "exit status: " prefix
> fix(hydro_deploy): improve error message when crates fail to build

- README.md
- docs/docs/hydro/correctness.md
- docs/docs/hydro/dataflow-programming.mdx
- docs/docs/hydro/index.mdx
- docs/docs/hydro/live-collections/bounded-unbounded.md
- docs/docs/hydro/live-collections/determinism.md
- docs/docs/hydro/locations/clusters.md
- docs/docs/hydro/locations/index.md
- docs/docs/hydro/ticks-atomicity/index.md
A pass of edits on the existing text.
> docs(hydro_lang): editing pass

- docs/docs/hydro/live-collections/streams.md
- docs/docs/hydro/locations/clusters.md
- docs/docs/hydro/quickstart/clusters.mdx
- hydro_lang/src/stream.rs
- hydro_std/src/compartmentalize.rs
- hydro_test/src/cluster/compute_pi.rs
- hydro_test/src/cluster/map_reduce.rs
- hydro_test/src/cluster/paxos.rs
- hydro_test/src/cluster/paxos_bench.rs
- hydro_test/src/cluster/paxos_with_client.rs
- template/hydro/src/first_ten_cluster.rs
Also address docs feedback for streams.
> refactor(hydro_lang)!: rename `_interleaved` to `_anonymous`

- hydro_test/examples/paxos.rs
- hydro_test/src/cluster/paxos.rs
- hydro_test/src/cluster/paxos_bench.rs
- hydro_test/src/cluster/paxos_with_client.rs
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
Extracts out the interface to invoking Paxos-like algorithms into a common trait.
> refactor(hydro_test): make logic for sending payloads to current leader reusable

- .cargo/config.toml
- hydro_deploy/core/src/progress.rs
Previously, some logs may have gone to stderr depending on the status of the `ProgressBar`. Also enables `rust-lld` linker on Apple Silicon to improve compilation times.
> fix(hydro_deploy): always write logs to stdout

- hydro_lang/tests/compile-fail/send_bincode_lifetime.rs
- hydro_lang/tests/compile-fail/send_bincode_lifetime.stderr
Test expected stderr stemmed from importing the wrong library, not from the actual error regarding lifetimes
> fix(hydro_lang): send_bincode_lifetime test

- .github/workflows/build-cli.yml
Broken when we switched to `rust-lld` as the default linker. Override like we do for x86_64.
> fix(hydro_cli): fix macOS aarch64 builds

- dfir_rs/src/util/deploy.rs
- hydro_deploy/hydro_cli/src/lib.rs
- hydro_deploy/hydroflow_deploy_integration/src/lib.rs
I got confused looking at my own code for client-server handshakes (in preparation for external client support). Time to do some renaming!
> refactor(hydro_deploy): improve naming of types involved with networking

- .config/nextest.toml
Nextest filter was broken accidentally by rename in #1601
> fix(dfir_rs): restore not running `two_pc_hf` test concurrently with others

- Cargo.lock
- hydro_lang/src/deploy/mod.rs
- hydro_lang/src/lib.rs
- hydro_std/src/lib.rs
- hydro_test/src/lib.rs
- hydro_test_local/Cargo.toml
- hydro_test_local/src/local/chat_app.rs
- hydro_test_local/src/local/count_elems.rs
- hydro_test_local/src/local/first_ten.rs
- hydro_test_local/src/local/graph_reachability.rs
- hydro_test_local/src/local/negation.rs
- hydro_test_local/src/local/teed_join.rs
- stageleft/src/lib.rs
- stageleft_macro/src/lib.rs
- stageleft_test/Cargo.toml
- stageleft_test/src/features.rs
- stageleft_test/src/lib.rs
- stageleft_test_macro/Cargo.toml
- stageleft_tool/Cargo.toml
- stageleft_tool/src/lib.rs
- template/hydro/src/lib.rs
- variadics_macro/Cargo.toml
Simplifies the logic for generating the public clone of the code, which eliminates the need to sprinkle `#[cfg(stageleft_runtime)]` (renamed from `#[stageleft::runtime]`) everywhere. Also adds logic to pass through `cfg` attrs when re-exporting public types.
> fix(stageleft)!: reduce where `#[cfg(stageleft_runtime)]` needs to be used

- dfir_lang/src/parse.rs
- dfir_rs/tests/compile-fail/surface_loop_cycle.rs
- dfir_rs/tests/compile-fail/surface_loop_missing_semi.rs
- dfir_rs/tests/compile-fail/surface_loop_missing_semi.stderr
- dfir_rs/tests/compile-fail/surface_loop_missing_windowing.rs
- dfir_rs/tests/compile-fail/surface_loop_multiple_window.rs
- dfir_rs/tests/compile-fail/surface_loop_source.rs
- dfir_rs/tests/surface_loop.rs
- dfir_rs/tests/surface_parser.rs
Is better for syntax highlighting.
BREAKING CHANGE: Need to add a semi colon `;` to after every `loop { ... };`.
> refactor(dfir_lang)!: require semicolons after loop braces, fix #1726

- dfir_lang/src/graph/ops/_counter.rs
- dfir_lang/src/graph/ops/mod.rs
- dfir_rs/src/scheduled/context.rs
- dfir_rs/tests/surface_counter.rs
This is the simplest possible implementation, there's a lot of room for improvement with a metrics system built into the runtime, but keeping it simple for now.
> feat(dfir_lang): add basic `_counter()` op for cardinality metrics, fix #1729

- stageleft/src/lib.rs
We have no way of generating the `__staged` variant of an `__doctest` module (in Rust 2024), so we skip adding that import. This means that any imports outside the quoted code will not function inside quoted code (existing behavior in Rust 2021).
> fix(stageleft): don't emit imports when staged code is in a doctest

- template/dfir/.gitignore
- template/hydro/.gitignore
Ignoring `Cargo.lock` was a remnant from the separate template repo, but `Cargo.lock` has always been recommended to be tracked in consuming bin crates
> chore: template `.gitignore`s, ignore `target/`, track `Cargo.lock`

- .github/workflows/audit.yml
- .github/workflows/build-cli.yml
- .github/workflows/ci.yml
- .github/workflows/examples-container.yml
- .github/workflows/release.yml
- .github/workflows/template.yml
- Cargo.lock
- dfir_lang/Cargo.toml
`actions-rs` actions are all unmaintained, trying to fix
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ci: update actions, stop using actions-rs

- .github/workflows/ci.yml
(instead of 3.2 years)
Fix #1767
Tested in my fork
> ci: only show benchmarks for last 365 days, fix #1767 [ci-bench]

- Cargo.lock
Not sure why these are out of sync, but Cargo adds them when building a fresh clone.
> chore: update lockfile with missing packages

- docs/src/pages/askai.js
The old AI assistant was set up by hand by RunLLM staff. We now have an assistant set up via their canonical self-service pipeline, under my berkeley credentials, which should be easier to manage/share.
> fix: update RunLLM assistant ID to match new account

- hydro_deploy/core/src/rust_crate/mod.rs
- hydro_lang/src/builder/deploy.rs
- hydro_lang/src/deploy/deploy_graph.rs
- hydro_lang/src/deploy/trybuild.rs
Also makes the generated `Cargo.toml` fixed regardless of the "extra Hydro features" or "test mode", by shifting them into special features defined on the trybuild repo. Overall, this results in the only dynamic piece being the generated `src/bin` files, which means that deploying the same code multiple times does not result in any recompilation.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/1779).
* #1780
* __->__ #1779
> fix(hydro_lang): fix codegen non-determinism that triggers rebuilds

- hydro_deploy/core/src/deployment.rs
- hydro_deploy/core/src/gcp.rs
- hydro_deploy/core/src/localhost/launched_binary.rs
- hydro_deploy/core/src/rust_crate/tracing_options.rs
- hydro_deploy/core/src/ssh.rs
- hydro_deploy/hydro_cli/src/lib.rs
- hydro_test/examples/perf_compute_pi.rs
- hydro_test/examples/perf_paxos.rs
BREAKING CHANGE: `startup_script` on GCP no longer exists, use `TracingOptions::setup_command` instead.
> fix(hydro_deploy)!: fix perf setup, remove GCP `startup_script`, use `TracingOptions::setup_command` instead

- hydro_lang/src/stream.rs
- hydro_test/src/cluster/snapshots/hydro_test__cluster__many_to_many__tests__many_to_many.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir@proposer_mermaid.snap
`Bytes::clone` is ~O(1), so it's much better to clone after serialization than before (O(n) serialization cost and allocations).
> feat(hydro_lang): only serialize once in broadcast

- .vscode/settings.json
- Cargo.lock
- hydro_lang/Cargo.toml
- hydro_lang/src/deploy/trybuild.rs
https://github.com/rust-lang/rust/issues/130994
> refactor(hydro_lang): use `fs2` file locking to fix stable build testing #1780

- hydro_lang/src/lib.rs
This appears to be a regression from the commit that uses fs2 on stable builds.
> fix: Enable file_lock feature in nightly builds

- hydro_lang/src/location/cluster/mod.rs
- hydro_lang/src/location/process.rs
- precheck.bash
- rust-toolchain.toml
- template/dfir/rust-toolchain.toml
- template/hydro/rust-toolchain.toml
Not going past 2024-04-05 due to rustc linker regression on windows: https://github.com/rust-lang/rust/issues/139821
> chore: update pinned nightly to 2025-04-05, clippy fixes

- .github/workflows/ci.yml
- Cargo.lock
- dfir_rs/Cargo.toml
- dfir_rs/src/scheduled/graph.rs
- dfir_rs/src/scheduled/handoff/handoff_list.rs
- dfir_rs/src/scheduled/handoff/mod.rs
- dfir_rs/src/scheduled/handoff/tee.rs
- dfir_rs/src/scheduled/handoff/vector.rs
- hydro_deploy/core/src/azure.rs
- hydro_deploy/core/src/custom_service.rs
- hydro_deploy/core/src/gcp.rs
- hydro_deploy/core/src/lib.rs
- hydro_deploy/core/src/localhost/mod.rs
- hydro_deploy/core/src/rust_crate/ports.rs
- hydro_deploy/core/src/rust_crate/service.rs
- hydro_deploy/hydro_cli/Cargo.toml
- hydro_deploy/hydro_cli/src/cli.rs
- hydro_deploy/hydro_cli/src/lib.rs
- precheck.bash
Fix #1821
https://pyo3.rs/v0.23.0/migration#from-020-to-021
BREAKING CHANGE: Now uses pyo3 0.24
> refactor(hydro_cli)!: use direct `&dyn Any` upcasting for Rust 1.86, update pyo3, fix #1821

- hydro_deploy/core/src/progress.rs
Fix #1415
Changes the display of progress to be a bit more intuitive.  
Now the format is `finished / started_or_finished / total`  
Example progress:
1. `0/1/5`
2. `1/1/5`
3. `1/5/5`
4. `3/5/5`
5. `5/5/5` (complete)
This is more natural as all numbers increase as progress increases, and all numbers are 100% when complete.
A question mark `?` will be displayed as the total if no total is given or the given total is invalid.
---
Previously displayed as: `finished / started_but_not_finished / total`
Example progress:
1. `0/1/5`
2. `1/0/5`
3. `1/4/5`
4. `3/2/5`
5. `5/0/5` (complete)
This is confusing as the `started_but_not_finished` column goes up and down as progress increases, and ends at zero.
> feat(hydro_deploy): update how progress is displayed, fix #1415

- Cargo.lock
- hydro_deploy/core/Cargo.toml
- hydro_deploy/core/src/rust_crate/build.rs
- hydro_deploy/core/src/ssh.rs
Fix #1337
Chose `blake3` which is designed to be as fast a possible, faster than MD5, SHA-1 while being more secure.
> refactor(hydro_deploy): use `blake3` hash intead of random for build `unique_id`, fix #1337

- hydro_deploy/core/src/localhost/launched_binary.rs
- hydro_deploy/core/src/rust_crate/service.rs
- hydro_deploy/core/src/ssh.rs
- hydro_deploy/core/src/util.rs
> refactor(hydro_deploy): Encapsulate stdout/stderr handling in new `PriorityBroadcast` type, fix #1357

- docs/docusaurus.config.js
Not sure why exactly this was happening, but this fixes it:
Was getting this issue on windows w/ node 23.11.0 and 24.1.0: https://github.com/facebook/docusaurus/discussions/10904
> [ERROR] Error: Expected usable value but received an empty preset, which is probably a mistake: presets typically come with `plugins` and sometimes with `settings`, but this has neither
at addPreset (file:///F:/Projects/hydroflow/docs/node_modules/unified/lib/index.js:1111:15)
at add (file:///F:/Projects/hydroflow/docs/node_modules/unified/lib/index.js:1097:11)
at addList (file:///F:/Projects/hydroflow/docs/node_modules/unified/lib/index.js:1135:11)
at Function.use (file:///F:/Projects/hydroflow/docs/node_modules/unified/lib/index.js:1074:9)
at createProcessor …
> fix(docs): fix for latest node: `docusaurus.config.js` use mjs

- hydro_lang/src/lib.rs
- hydro_lang/src/location/external_process.rs
- hydro_lang/src/location/mod.rs
- hydro_lang/src/location/tick.rs
- hydro_lang/src/optional.rs
- hydro_lang/src/singleton.rs
- hydro_lang/src/stream.rs
- hydro_lang/src/test_util.rs
- hydro_std/src/quorum.rs
- hydro_test/src/cluster/paxos.rs
This introduces an additional type paramter to `Stream` called `Retries`, which tracks the presence (or lack) of non-determinstic retries in the stream. `ExactlyOnce` means that each element has deterministic order, while `AtLeastOnce` means that there may be non-deterministic duplicates.
A `TotalOrder, AtLeastOnce` stream describes elements with consecutive duplication, but deterministic order if we ignore those immediate elements. A `NoOrder, AtLeastOnce` stream has set semantics.
Also fixes a bug in the return type for `*_keyed_*`, where the output type was previously `TotalOrder` but now is `NoOrder`. We stream the results of a keyed aggregation out of a `HashMap`, so the order will indeed be non-deterministic.
Fixes #1863
> feat(hydro_lang)!: add stream markers for tracking non-deterministic retries

- Cargo.lock
- hydro_optimize/Cargo.toml
- hydro_optimize/src/lib.rs
- hydro_test/Cargo.toml
Using `hydro_optimize` as a regular dependency in `hydro_test` results in leaking many dependencies including `hydro_deploy`, so this moves it to a dev-dependency
> chore(hydro_optimize): clean up dependencies

- Cargo.lock
- hydro_deploy/hydro_deploy_integration/Cargo.toml
- hydro_deploy/hydro_deploy_integration/src/lib.rs
This was the only use of the proc-macro version along the Hydro dependencies, we can just use the declarative macro version.
> refactor(hydro_deploy_integration): eliminate `pin-project` proc macro dependency

- dfir_rs/src/util/deploy.rs
- hydro_deploy/core/src/custom_service.rs
- hydro_deploy/hydro_deploy_examples/examples/stdout_receiver/main.rs
- hydro_deploy/hydro_deploy_examples/examples/tagged_stdout_receiver/main.rs
- hydro_deploy/hydro_deploy_examples/examples/ws_chat_server/main.rs
- hydro_deploy/hydro_deploy_integration/src/lib.rs
- hydro_lang/src/deploy/trybuild.rs
- hydro_lang/src/deploy_runtime.rs
- hydro_test/src/local/count_elems.rs
- hydro_test/src/local/negation.rs
- topolotree/src/latency_measure.rs
- topolotree/src/main.rs
- topolotree/src/pn.rs
- topolotree/src/pn_delta.rs
Before, we had a janky architecture for establishing network connections which relied on blocking on futures outside an async context, which required a multi-threaded runtime. Now, we establish all connections before launching the DFIR code, so that no blocking is required there.
Fixes #1807
> feat(hydro_deploy_integration,hydro_lang): allow running generated binaries with single-threaded Tokio runtime

- hydro_deploy/core/src/rust_crate/build.rs
sccache includes all environment variables starting with `CARGO_` in the cache key, so this would cause misses for all trybuild compilation. Along with https://github.com/mozilla/sccache/pull/2424, this improves compilation caching.
> fix(hydro_deploy): use `--target-dir` instead of environment variable to improve caching

- Cargo.lock
- dfir_rs/Cargo.toml
- hydro_deploy/hydro_deploy_integration/Cargo.toml
- hydro_lang/Cargo.toml
Now that `hydro_lang` no longer needs multi-threaded runtime, we can eliminate it from the features used in `trybuild` compilation. Minimizes Tokio features elsewhere too.
> refactor: minimize Tokio feature flags

- hydro_lang/src/deploy/trybuild.rs
- hydro_lang/src/deploy/vscode-trybuild.json
To fully compile the generated sources without error, the Stageleft environment variable needt to be passed to build scripts, so pre-configure that in workspace settings.
> feat(hydro_lang): make it easier to open trybuild-generated files with Rust Analyzer

- .vscode/settings.json
Now that we don't compile any Stageleft stuff in Rust Analyzer, we don't need to customize the default feature set.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/1950).
* #1951
* __->__ #1950
> chore: remove remaining custom VSCode config

- hydro_lang/src/builder/built.rs
- hydro_lang/src/builder/deploy.rs
- hydro_lang/src/builder/mod.rs
- hydro_lang/src/deploy/deploy_graph.rs
- hydro_lang/src/deploy/mod.rs
- hydro_lang/src/graph/render.rs
- hydro_lang/src/ir.rs
- hydro_lang/src/lib.rs
- hydro_lang/src/location/can_send.rs
- hydro_lang/src/location/external_process.rs
- hydro_lang/src/location/mod.rs
- hydro_lang/src/stream.rs
- hydro_test/src/distributed/first_ten.rs
- hydro_test/src/distributed/snapshots/hydro_test__distributed__first_ten__tests__first_ten_distributed_ir.snap
In preparation of supporting multi-connection source / sink pairs. There is no need to distinguish a single external from multiple at the location level, instead we will have separate APIs for declaring a single vs multi connection input/output.
> refactor(hydro_lang): rename `ExternalProcess` to `External`

- hydro_deploy/hydro_deploy_integration/src/lib.rs
> fix(hydro_deploy_integration): leftover logging when setting up Unix sockets

- hydro_lang/src/graph/render.rs
- hydro_lang/src/ir.rs
- hydro_lang/src/location/mod.rs
- hydro_lang/src/rewrites/persist_pullup.rs
- hydro_lang/src/stream.rs
- hydro_optimize/src/decoupler.rs
- hydro_optimize/src/snapshots/hydro_optimize__decoupler__tests__decouple_after_source_ir.snap
- hydro_optimize/src/snapshots/hydro_optimize__decoupler__tests__move_source_decouple_map_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__compute_pi__tests__compute_pi_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__compute_pi__tests__decoupled_compute_pi_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__many_to_many__tests__many_to_many_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__map_reduce__tests__map_reduce_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__simple_cluster__tests__partitioned_simple_cluster_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__simple_cluster__tests__simple_cluster_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_partition.snap
- hydro_test/src/distributed/snapshots/hydro_test__distributed__first_ten__tests__first_ten_distributed_ir.snap
First, we remove externals from `LocationId`, to ensure that a `LocationId` only is used for locations where we can concretely place compiled logic. This simplifes a lot of pattern matching where we wanted to disallow externals.
Keys on network inputs / outputs (`from_key` and `to_key`) are only relevant to external networking. We extract the logic to instantiate external network collections, so that the core logic does not need to deal with keys.
> refactor(hydro_lang): separate externals from other location kinds, clean up network operators

- hydro_lang/src/keyed_stream.rs
- hydro_lang/src/lib.rs
- hydro_lang/src/location/mod.rs
- hydro_lang/src/stream.rs
- hydro_test/examples/echo.rs
- hydro_test/examples/http_hello.rs
- hydro_test/src/external_client/echo.rs
- hydro_test/src/external_client/http_hello.rs
Previously, we would represent all key-value pairs as just a `Stream<(K, V)>`. When receiving data from multiple sources, such as external clients, this would result in interleaved `(ID, T)` pairs all smooshed into a single stream.
Because the interleaving is non-deterministic, the strongest type we could correctly give to this stream is `NoOrder`, which fails to capture that _within_ each key, the elements might be totally ordered. This introduces a new live collection type `KeyedStream`, where the stream markers apply only to elements within each key group, rather than across all elements (keys are assumed to have no order). This allows us to capture common request-response patterns with IDs without requiring any unsafe code.
> feat(hydro_lang): add `KeyedStream` to track steams with unordered keys but possibly-ordered values

- hydro_lang/src/keyed_stream.rs
- hydro_lang/src/rewrites/properties.rs
- hydro_lang/src/rewrites/snapshots/hydro_lang__rewrites__properties__tests__property_optimized.snap
- hydro_lang/src/stream.rs
- hydro_optimize/src/partition_node_analysis.rs
- hydro_std/src/bench_client/mod.rs
- hydro_std/src/quorum.rs
- hydro_test/src/cluster/map_reduce.rs
- hydro_test/src/cluster/paxos.rs
- hydro_test/src/cluster/snapshots/hydro_test__cluster__map_reduce__tests__map_reduce_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir@acceptor_mermaid.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir@proposer_mermaid.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_partition.snap
Also adds missing doctests to the aggregation APIs on `KeyedStream`.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/1984).
* #1985
* __->__ #1984
> refactor(hydro_lang,hydro_std,hydro_test): remove uses of legacy `*_keyed` APIs

- hydro_lang/src/keyed_stream.rs
- hydro_lang/src/stream.rs
- hydro_test/src/cluster/paxos.rs
By using the `MinOrder` and `MinRetries` traits to cast to a weake guarantee, we can guarantee safety through the type system even when "casting" the marker.
> refactor(hydro_lang)!: rename `Stream::union` to `Stream::interleave` and reduce local non-determinism

- hydro_deploy/hydro_deploy_integration/src/multi_connection.rs
- hydro_lang/src/keyed_singleton.rs
- hydro_lang/src/keyed_stream.rs
- hydro_lang/src/rewrites/snapshots/hydro_lang__rewrites__properties__tests__property_optimized.snap
- hydro_lang/src/stream.rs
- hydro_test/examples/http_counter.rs
- hydro_test/src/cluster/snapshots/hydro_test__cluster__map_reduce__tests__map_reduce_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_partition.snap
- hydro_test/src/external_client/http_counter.rs
- hydro_test/src/external_client/mod.rs
Also fixes incorrect output metadata for `KeyedStream::fold`, and removes `KeyedSingleton::all_ticks` for now until we a) actually need it and b) can think carefully about its semantics.
> feat(hydro_lang)!: start adding APIs for various forms of keyed streams "joins", add KVS counter server

- CITATION.cff
- README.md
- dfir_rs/README.md
- docs/docs/dfir/concepts/index.md
- docs/docs/dfir/ecosystem.md
> docs: consistently refer to Hydro as a framework

- hydro_lang/src/boundedness.rs
- hydro_lang/src/keyed_singleton.rs
- hydro_lang/src/keyed_stream.rs
- hydro_lang/src/optional.rs
- hydro_lang/src/singleton.rs
- hydro_lang/src/stream.rs
- hydro_lang/src/stream/networking.rs
- hydro_std/src/compartmentalize.rs
- hydro_test/examples/http_hello.rs
- hydro_test/src/external_client/http_counter.rs
- hydro_test/src/external_client/http_hello.rs
There are many cases where once a value is released into a `KeyedSingleton`, it will never be changes. In such cases, we can permit APIs like `.entries` even if the set of entries is growing.
We use this type to improve the API surface for looking up values for a request. Now, a `KeyedSingleton` of requests can look up values from another `KeyedSingleton`.
> feat(hydro_lang)!: refine types when values of a `KeyedSingleton` are immutable

- hydro_lang/src/builder/built.rs
- hydro_lang/src/graph/api.rs
- hydro_lang/src/graph/config.rs
- hydro_lang/src/graph/mod.rs
- hydro_lang/src/lib.rs
- hydro_test/examples/benchmark_paxos.rs
- hydro_test/examples/chat.rs
- hydro_test/examples/compartmentalized_paxos.rs
- hydro_test/examples/compute_pi.rs
- hydro_test/examples/decouple_compute_pi.rs
- hydro_test/examples/echo.rs
- hydro_test/examples/first_ten_distributed.rs
- hydro_test/examples/http_counter.rs
- hydro_test/examples/http_hello.rs
- hydro_test/examples/map_reduce.rs
- hydro_test/examples/partition_simple_cluster.rs
- hydro_test/examples/paxos.rs
- hydro_test/examples/perf_compute_pi.rs
- hydro_test/examples/perf_paxos.rs
- hydro_test/examples/simple_cluster.rs
- hydro_test/examples/two_pc.rs
Clearer name, and all the declarations in it were for configuring graph generation anyways.
> refactor(hydro_lang)!: rename `graph_util` => `graph::config`

- .github/workflows/ci.yml
- hydro_lang/src/backtrace.rs
- hydro_lang/src/ir.rs
- hydro_lang/src/lib.rs
- hydro_lang/src/location/mod.rs
- hydro_lang/src/snapshots/hydro_lang__stream__tests__backtrace_chained_ops-2.snap
- hydro_lang/src/snapshots/hydro_lang__stream__tests__backtrace_chained_ops.snap
- hydro_lang/src/stream.rs
Also cleans up the API interface, adds the `colno` field, and a unit test showing that we can precisely identify each element of chained operators.
> docs(hydro_lang): docs for `backtrace` module

- .github/workflows/ci.yml
Otherwise it defaults to the user who triggered the workflow, which for reasons I don't understand is @MingweiSamuel?
> ci: set hydro-project-bot bot to be the author of generated PRs

- hydro_lang/src/lib.rs
- hydro_lang/src/live_collections/boundedness.rs
- hydro_lang/src/live_collections/keyed_singleton.rs
- hydro_lang/src/live_collections/keyed_stream.rs
- hydro_lang/src/live_collections/mod.rs
- hydro_lang/src/live_collections/optional.rs
- hydro_lang/src/live_collections/singleton.rs
- hydro_lang/src/live_collections/stream.rs
- hydro_lang/src/live_collections/stream/networking.rs
- hydro_lang/src/location/mod.rs
- hydro_lang/src/location/tick.rs
- hydro_lang/src/test_util.rs
- hydro_std/src/compartmentalize.rs
- hydro_std/src/membership.rs
Type tags for boundedness are only used in the type parameters for live collections.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/2073).
* #2081
* #2075
* #2074
* __->__ #2073
> refactor(hydro_lang)!: move `boundedness` module under `live_collections`

- hydro_lang/src/live_collections/keyed_stream/mod.rs
- hydro_lang/src/live_collections/stream/mod.rs
Previously, `fold_early_stop` would _reset_ its state instead of terminating and ignoring future elements, which broke downstream users such as `first`.
Now, we introduce a new `generate` API that offers a more flexible API (versus scan) for iterative processing that yields elements, and use it to implement `fold_early_stop`, which fixes the bugs. We also remove the old `scan_keyed` API in favor of `KeyedStream::scan`.
There is still an issue that the `None` value for each group's generator state will be kept around indefninitely. We will need to pass around termination markers for each group to garbage collect these.
> fix(hydro_lang)!: introduce `generator` API and ensure that `fold_early_stop` actually terminates

- dfir_lang/src/graph/ops/chain_first_n.rs
- dfir_lang/src/graph/ops/mod.rs
- dfir_lang/src/graph/ops/union.rs
- hydro_lang/src/compile/ir/mod.rs
- hydro_lang/src/graph/render.rs
- hydro_lang/src/live_collections/optional.rs
- hydro_lang/src/live_collections/singleton.rs
- hydro_std/src/bench_client/mod.rs
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir@acceptor_mermaid.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir@proposer_mermaid.snap
Using `HydroNode::Chain` is very dangerous for singletons / optionals, because it can lead to cardinality > 1 within a single batch, which breaks a fundamental invariant.
This introduces a new `HydroNode::ChainFirst` operator that only emits the first value from the chain. This is paired with a new DFIR operator `chain_first` for this behavior.
We also rewrite some `Singleton` logic to use `Optional` under the hood, which reduces the places where we deal with chaining in the IR, hopefully avoiding future incidents.
> fix(hydro_lang)!: fix cardinality for `Optional::or`

- hydro_lang/src/live_collections/keyed_stream/mod.rs
- hydro_lang/src/live_collections/optional.rs
- hydro_lang/src/live_collections/singleton.rs
- hydro_lang/src/live_collections/stream/mod.rs
- hydro_std/src/bench_client/mod.rs
- hydro_test/src/cluster/compartmentalized_paxos.rs
- hydro_test/src/cluster/paxos.rs
- hydro_test/src/cluster/paxos_bench.rs
- hydro_test/src/cluster/paxos_with_client.rs
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir@acceptor_mermaid.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir@proposer_mermaid.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_ir.snap
- hydro_test/src/local/negation.rs
Eventually, we will want to change these APIs to take a "Condition" live collection instead of an optional, but this at least improves the naming for now.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydro/pull/2111).
* #2118
* #2117
* #2116
* #2115
* #2114
* #2112
* __->__ #2111
> refactor(hydro_lang)!: rename `continue_if*` to `filter_if*` and document

- dfir_rs/examples/two_pc_hf/protocol.rs
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_port_extra.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_port_extra_zero.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_port_extramissing.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_port_wrong_one.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_wrongfields_1.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_wrongfields_2.stderr
- hydro_lang/src/compile/ir/snapshots/hydro_lang__compile__ir__backtrace__tests__backtrace.snap
- hydro_lang/src/live_collections/stream/tests/snapshots/hydro_lang__live_collections__stream__tests__backtrace_chained_ops__backtrace_chained_ops-2.snap
- hydro_lang/src/live_collections/stream/tests/snapshots/hydro_lang__live_collections__stream__tests__backtrace_chained_ops__backtrace_chained_ops.snap
The line number of `core::ops::function::FnOnce::call_once` in the standard library changed.
> fix(hydro_lang): update snapshots for Rust 1.90 and remove unused types

- .github/workflows/docs.yml
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_port_extra.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_port_extra_zero.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_port_extramissing.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_port_wrong_one.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_wrongfields_1.stderr
- dfir_rs/tests/compile-fail-stable/surface_demuxenum_wrongfields_2.stderr
- hydro_lang/src/compile/ir/snapshots/hydro_lang__compile__ir__backtrace__tests__backtrace.snap
- hydro_lang/src/live_collections/stream/tests/snapshots/hydro_lang__live_collections__stream__tests__backtrace_chained_ops__backtrace_chained_ops-2.snap
- hydro_lang/src/live_collections/stream/tests/snapshots/hydro_lang__live_collections__stream__tests__backtrace_chained_ops__backtrace_chained_ops.snap
- precheck.bash
- rust-toolchain.toml
GitHub Actions is going to be flip/flopping between 1.89 and 1.90, and we have users who need support on 1.89.
Also updates precheck.bash to use nextest for _speed_.
> chore: pin Rust to 1.89

- hydro_lang/src/compile/ir/mod.rs
- hydro_lang/src/live_collections/keyed_singleton.rs
- hydro_lang/src/live_collections/keyed_stream/mod.rs
- hydro_lang/src/live_collections/optional.rs
- hydro_lang/src/live_collections/singleton.rs
- hydro_lang/src/live_collections/stream/mod.rs
- hydro_test/src/cluster/snapshots/hydro_test__cluster__paxos_bench__tests__paxos_ir.snap
- hydro_test/src/cluster/snapshots/hydro_test__cluster__two_pc_bench__tests__two_pc_ir.snap
Because the IR now includes the location of the output, we can just use that in the codegen process. This cleans up the code and also prepares us for simulator codegen, where the output DFIR will depend on the tick.
Also fixes a bug I found in top-level `unique` while refactoring, and adds a corresponding unit test.
> refactor(hydro_lang): don't pass around locations when emitting DFIR

- Cargo.lock
- hydro_lang/Cargo.toml
- hydro_lang/src/compile/ir/mod.rs
- hydro_lang/src/lib.rs
- hydro_lang/src/sim/builder.rs
- hydro_lang/src/sim/compiled.rs
- hydro_lang/src/sim/graph.rs
- hydro_lang/src/sim/runtime.rs
- hydro_lang/src/sim/tests/mod.rs
- hydro_lang/src/sim/tests/snapshots/hydro_lang__sim__tests__trace_for_fuzzed_batching.snap
#2167 addendum
two separate atomic commits:
1. get rid of duplicated code via `use<W: std::io::Write>`
2. use `std::io::empty()` instead of `Option<W>`
> refactor(hydro_lang): simplify decision logging code when replaying simulations #2167
